// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HendraaaIrwn/honda-leasing-api/internal/domain/models"
)

func newCustomer(db *gorm.DB, opts ...gen.DOOption) customer {
	_customer := customer{}

	_customer.customerDo.UseDB(db, opts...)
	_customer.customerDo.UseModel(&models.Customer{})

	tableName := _customer.customerDo.TableName()
	_customer.ALL = field.NewAsterisk(tableName)
	_customer.CustomerID = field.NewInt64(tableName, "customer_id")
	_customer.NIK = field.NewString(tableName, "nik")
	_customer.NamaLengkap = field.NewString(tableName, "nama_lengkap")
	_customer.TanggalLahir = field.NewTime(tableName, "tanggal_lahir")
	_customer.NoHP = field.NewString(tableName, "no_hp")
	_customer.Email = field.NewString(tableName, "email")
	_customer.Pekerjaan = field.NewString(tableName, "pekerjaan")
	_customer.Perusahaan = field.NewString(tableName, "perusahaan")
	_customer.Salary = field.NewFloat64(tableName, "salary")
	_customer.CreatedAt = field.NewTime(tableName, "created_at")
	_customer.UpdatedAt = field.NewTime(tableName, "updated_at")
	_customer.LocationID = field.NewInt64(tableName, "location_id")
	_customer.Location = customerHasOneLocation{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Location", "models.Location"),
		Kelurahan: struct {
			field.RelationField
			Kecamatan struct {
				field.RelationField
				Kabupaten struct {
					field.RelationField
					Province struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
						}
					}
					Kecamatan struct {
						field.RelationField
					}
				}
				Kelurahan struct {
					field.RelationField
				}
			}
			Locations struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Location.Kelurahan", "models.Kelurahan"),
			Kecamatan: struct {
				field.RelationField
				Kabupaten struct {
					field.RelationField
					Province struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
						}
					}
					Kecamatan struct {
						field.RelationField
					}
				}
				Kelurahan struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Location.Kelurahan.Kecamatan", "models.Kecamatan"),
				Kabupaten: struct {
					field.RelationField
					Province struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
						}
					}
					Kecamatan struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Location.Kelurahan.Kecamatan.Kabupaten", "models.Kabupaten"),
					Province: struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Location.Kelurahan.Kecamatan.Kabupaten.Province", "models.Province"),
						Kabupaten: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Location.Kelurahan.Kecamatan.Kabupaten.Province.Kabupaten", "models.Kabupaten"),
						},
					},
					Kecamatan: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Location.Kelurahan.Kecamatan.Kabupaten.Kecamatan", "models.Kecamatan"),
					},
				},
				Kelurahan: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Location.Kelurahan.Kecamatan.Kelurahan", "models.Kelurahan"),
				},
			},
			Locations: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Location.Kelurahan.Locations", "models.Location"),
			},
		},
	}

	_customer.LeasingContracts = customerHasManyLeasingContracts{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("LeasingContracts", "models.LeasingContract"),
		Customer: struct {
			field.RelationField
			Location struct {
				field.RelationField
			}
			LeasingContracts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("LeasingContracts.Customer", "models.Customer"),
			Location: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("LeasingContracts.Customer.Location", "models.Location"),
			},
			LeasingContracts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("LeasingContracts.Customer.LeasingContracts", "models.LeasingContract"),
			},
		},
		Motor: struct {
			field.RelationField
			MotorTypeRef struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}
			MotorAssets struct {
				field.RelationField
				Motor struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("LeasingContracts.Motor", "models.Motor"),
			MotorTypeRef: struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("LeasingContracts.Motor.MotorTypeRef", "models.MotorType"),
				Motors: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LeasingContracts.Motor.MotorTypeRef.Motors", "models.Motor"),
				},
			},
			MotorAssets: struct {
				field.RelationField
				Motor struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("LeasingContracts.Motor.MotorAssets", "models.MotorAsset"),
				Motor: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LeasingContracts.Motor.MotorAssets.Motor", "models.Motor"),
				},
			},
		},
		Product: struct {
			field.RelationField
			LeasingContracts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("LeasingContracts.Product", "models.LeasingProduct"),
			LeasingContracts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("LeasingContracts.Product.LeasingContracts", "models.LeasingContract"),
			},
		},
		LeasingTasks: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Role struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}
			LeasingAttribute struct {
				field.RelationField
				Task struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("LeasingContracts.LeasingTasks", "models.LeasingTask"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Contract", "models.LeasingContract"),
			},
			Role: struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role", "models.Role"),
				UserRoles: struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles", "models.UserRole"),
					User: struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles.User", "models.User"),
						UserOAuthProviders: struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}{
							RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles.User.UserOAuthProviders", "models.UserOAuthProvider"),
							User: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.User", "models.User"),
							},
							Provider: struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.Provider", "models.OAuthProvider"),
								UserOAuthProviders: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.Provider.UserOAuthProviders", "models.UserOAuthProvider"),
								},
							},
						},
						UserRoles: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles.User.UserRoles", "models.UserRole"),
						},
					},
					Role: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles.Role", "models.Role"),
					},
				},
				RolePermissions: struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.RolePermissions", "models.RolePermission"),
					Role: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.RolePermissions.Role", "models.Role"),
					},
					Permission: struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.RolePermissions.Permission", "models.Permission"),
						RolePermissions: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.RolePermissions.Permission.RolePermissions", "models.RolePermission"),
						},
					},
				},
			},
			LeasingAttribute: struct {
				field.RelationField
				Task struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("LeasingContracts.LeasingTasks.LeasingAttribute", "models.LeasingTaskAttribute"),
				Task: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LeasingContracts.LeasingTasks.LeasingAttribute.Task", "models.LeasingTask"),
				},
			},
		},
		PaymentSchedules: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Payments struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Schedule struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("LeasingContracts.PaymentSchedules", "models.PaymentSchedule"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("LeasingContracts.PaymentSchedules.Contract", "models.LeasingContract"),
			},
			Payments: struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Schedule struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("LeasingContracts.PaymentSchedules.Payments", "models.Payment"),
				Contract: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LeasingContracts.PaymentSchedules.Payments.Contract", "models.LeasingContract"),
				},
				Schedule: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LeasingContracts.PaymentSchedules.Payments.Schedule", "models.PaymentSchedule"),
				},
			},
		},
		Payments: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("LeasingContracts.Payments", "models.Payment"),
		},
		ContractDocuments: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("LeasingContracts.ContractDocuments", "models.LeasingContractDocument"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("LeasingContracts.ContractDocuments.Contract", "models.LeasingContract"),
			},
		},
	}

	_customer.fillFieldMap()

	return _customer
}

type customer struct {
	customerDo

	ALL          field.Asterisk
	CustomerID   field.Int64
	NIK          field.String
	NamaLengkap  field.String
	TanggalLahir field.Time
	NoHP         field.String
	Email        field.String
	Pekerjaan    field.String
	Perusahaan   field.String
	Salary       field.Float64
	CreatedAt    field.Time
	UpdatedAt    field.Time
	LocationID   field.Int64
	Location     customerHasOneLocation

	LeasingContracts customerHasManyLeasingContracts

	fieldMap map[string]field.Expr
}

func (c customer) Table(newTableName string) *customer {
	c.customerDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c customer) As(alias string) *customer {
	c.customerDo.DO = *(c.customerDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *customer) updateTableName(table string) *customer {
	c.ALL = field.NewAsterisk(table)
	c.CustomerID = field.NewInt64(table, "customer_id")
	c.NIK = field.NewString(table, "nik")
	c.NamaLengkap = field.NewString(table, "nama_lengkap")
	c.TanggalLahir = field.NewTime(table, "tanggal_lahir")
	c.NoHP = field.NewString(table, "no_hp")
	c.Email = field.NewString(table, "email")
	c.Pekerjaan = field.NewString(table, "pekerjaan")
	c.Perusahaan = field.NewString(table, "perusahaan")
	c.Salary = field.NewFloat64(table, "salary")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.LocationID = field.NewInt64(table, "location_id")

	c.fillFieldMap()

	return c
}

func (c *customer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *customer) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 14)
	c.fieldMap["customer_id"] = c.CustomerID
	c.fieldMap["nik"] = c.NIK
	c.fieldMap["nama_lengkap"] = c.NamaLengkap
	c.fieldMap["tanggal_lahir"] = c.TanggalLahir
	c.fieldMap["no_hp"] = c.NoHP
	c.fieldMap["email"] = c.Email
	c.fieldMap["pekerjaan"] = c.Pekerjaan
	c.fieldMap["perusahaan"] = c.Perusahaan
	c.fieldMap["salary"] = c.Salary
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["location_id"] = c.LocationID

}

func (c customer) clone(db *gorm.DB) customer {
	c.customerDo.ReplaceConnPool(db.Statement.ConnPool)
	c.Location.db = db.Session(&gorm.Session{Initialized: true})
	c.Location.db.Statement.ConnPool = db.Statement.ConnPool
	c.LeasingContracts.db = db.Session(&gorm.Session{Initialized: true})
	c.LeasingContracts.db.Statement.ConnPool = db.Statement.ConnPool
	return c
}

func (c customer) replaceDB(db *gorm.DB) customer {
	c.customerDo.ReplaceDB(db)
	c.Location.db = db.Session(&gorm.Session{})
	c.LeasingContracts.db = db.Session(&gorm.Session{})
	return c
}

type customerHasOneLocation struct {
	db *gorm.DB

	field.RelationField

	Kelurahan struct {
		field.RelationField
		Kecamatan struct {
			field.RelationField
			Kabupaten struct {
				field.RelationField
				Province struct {
					field.RelationField
					Kabupaten struct {
						field.RelationField
					}
				}
				Kecamatan struct {
					field.RelationField
				}
			}
			Kelurahan struct {
				field.RelationField
			}
		}
		Locations struct {
			field.RelationField
		}
	}
}

func (a customerHasOneLocation) Where(conds ...field.Expr) *customerHasOneLocation {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a customerHasOneLocation) WithContext(ctx context.Context) *customerHasOneLocation {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a customerHasOneLocation) Session(session *gorm.Session) *customerHasOneLocation {
	a.db = a.db.Session(session)
	return &a
}

func (a customerHasOneLocation) Model(m *models.Customer) *customerHasOneLocationTx {
	return &customerHasOneLocationTx{a.db.Model(m).Association(a.Name())}
}

func (a customerHasOneLocation) Unscoped() *customerHasOneLocation {
	a.db = a.db.Unscoped()
	return &a
}

type customerHasOneLocationTx struct{ tx *gorm.Association }

func (a customerHasOneLocationTx) Find() (result *models.Location, err error) {
	return result, a.tx.Find(&result)
}

func (a customerHasOneLocationTx) Append(values ...*models.Location) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a customerHasOneLocationTx) Replace(values ...*models.Location) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a customerHasOneLocationTx) Delete(values ...*models.Location) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a customerHasOneLocationTx) Clear() error {
	return a.tx.Clear()
}

func (a customerHasOneLocationTx) Count() int64 {
	return a.tx.Count()
}

func (a customerHasOneLocationTx) Unscoped() *customerHasOneLocationTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type customerHasManyLeasingContracts struct {
	db *gorm.DB

	field.RelationField

	Customer struct {
		field.RelationField
		Location struct {
			field.RelationField
		}
		LeasingContracts struct {
			field.RelationField
		}
	}
	Motor struct {
		field.RelationField
		MotorTypeRef struct {
			field.RelationField
			Motors struct {
				field.RelationField
			}
		}
		MotorAssets struct {
			field.RelationField
			Motor struct {
				field.RelationField
			}
		}
	}
	Product struct {
		field.RelationField
		LeasingContracts struct {
			field.RelationField
		}
	}
	LeasingTasks struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
		Role struct {
			field.RelationField
			UserRoles struct {
				field.RelationField
				User struct {
					field.RelationField
					UserOAuthProviders struct {
						field.RelationField
						User struct {
							field.RelationField
						}
						Provider struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}
					}
					UserRoles struct {
						field.RelationField
					}
				}
				Role struct {
					field.RelationField
				}
			}
			RolePermissions struct {
				field.RelationField
				Role struct {
					field.RelationField
				}
				Permission struct {
					field.RelationField
					RolePermissions struct {
						field.RelationField
					}
				}
			}
		}
		LeasingAttribute struct {
			field.RelationField
			Task struct {
				field.RelationField
			}
		}
	}
	PaymentSchedules struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
		Payments struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Schedule struct {
				field.RelationField
			}
		}
	}
	Payments struct {
		field.RelationField
	}
	ContractDocuments struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
	}
}

func (a customerHasManyLeasingContracts) Where(conds ...field.Expr) *customerHasManyLeasingContracts {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a customerHasManyLeasingContracts) WithContext(ctx context.Context) *customerHasManyLeasingContracts {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a customerHasManyLeasingContracts) Session(session *gorm.Session) *customerHasManyLeasingContracts {
	a.db = a.db.Session(session)
	return &a
}

func (a customerHasManyLeasingContracts) Model(m *models.Customer) *customerHasManyLeasingContractsTx {
	return &customerHasManyLeasingContractsTx{a.db.Model(m).Association(a.Name())}
}

func (a customerHasManyLeasingContracts) Unscoped() *customerHasManyLeasingContracts {
	a.db = a.db.Unscoped()
	return &a
}

type customerHasManyLeasingContractsTx struct{ tx *gorm.Association }

func (a customerHasManyLeasingContractsTx) Find() (result []*models.LeasingContract, err error) {
	return result, a.tx.Find(&result)
}

func (a customerHasManyLeasingContractsTx) Append(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a customerHasManyLeasingContractsTx) Replace(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a customerHasManyLeasingContractsTx) Delete(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a customerHasManyLeasingContractsTx) Clear() error {
	return a.tx.Clear()
}

func (a customerHasManyLeasingContractsTx) Count() int64 {
	return a.tx.Count()
}

func (a customerHasManyLeasingContractsTx) Unscoped() *customerHasManyLeasingContractsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type customerDo struct{ gen.DO }

type ICustomerDo interface {
	gen.SubQuery
	Debug() ICustomerDo
	WithContext(ctx context.Context) ICustomerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICustomerDo
	WriteDB() ICustomerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICustomerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICustomerDo
	Not(conds ...gen.Condition) ICustomerDo
	Or(conds ...gen.Condition) ICustomerDo
	Select(conds ...field.Expr) ICustomerDo
	Where(conds ...gen.Condition) ICustomerDo
	Order(conds ...field.Expr) ICustomerDo
	Distinct(cols ...field.Expr) ICustomerDo
	Omit(cols ...field.Expr) ICustomerDo
	Join(table schema.Tabler, on ...field.Expr) ICustomerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICustomerDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICustomerDo
	Group(cols ...field.Expr) ICustomerDo
	Having(conds ...gen.Condition) ICustomerDo
	Limit(limit int) ICustomerDo
	Offset(offset int) ICustomerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICustomerDo
	Unscoped() ICustomerDo
	Create(values ...*models.Customer) error
	CreateInBatches(values []*models.Customer, batchSize int) error
	Save(values ...*models.Customer) error
	First() (*models.Customer, error)
	Take() (*models.Customer, error)
	Last() (*models.Customer, error)
	Find() ([]*models.Customer, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Customer, err error)
	FindInBatches(result *[]*models.Customer, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Customer) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICustomerDo
	Assign(attrs ...field.AssignExpr) ICustomerDo
	Joins(fields ...field.RelationField) ICustomerDo
	Preload(fields ...field.RelationField) ICustomerDo
	FirstOrInit() (*models.Customer, error)
	FirstOrCreate() (*models.Customer, error)
	FindByPage(offset int, limit int) (result []*models.Customer, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICustomerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c customerDo) Debug() ICustomerDo {
	return c.withDO(c.DO.Debug())
}

func (c customerDo) WithContext(ctx context.Context) ICustomerDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c customerDo) ReadDB() ICustomerDo {
	return c.Clauses(dbresolver.Read)
}

func (c customerDo) WriteDB() ICustomerDo {
	return c.Clauses(dbresolver.Write)
}

func (c customerDo) Session(config *gorm.Session) ICustomerDo {
	return c.withDO(c.DO.Session(config))
}

func (c customerDo) Clauses(conds ...clause.Expression) ICustomerDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c customerDo) Returning(value interface{}, columns ...string) ICustomerDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c customerDo) Not(conds ...gen.Condition) ICustomerDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c customerDo) Or(conds ...gen.Condition) ICustomerDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c customerDo) Select(conds ...field.Expr) ICustomerDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c customerDo) Where(conds ...gen.Condition) ICustomerDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c customerDo) Order(conds ...field.Expr) ICustomerDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c customerDo) Distinct(cols ...field.Expr) ICustomerDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c customerDo) Omit(cols ...field.Expr) ICustomerDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c customerDo) Join(table schema.Tabler, on ...field.Expr) ICustomerDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c customerDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICustomerDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c customerDo) RightJoin(table schema.Tabler, on ...field.Expr) ICustomerDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c customerDo) Group(cols ...field.Expr) ICustomerDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c customerDo) Having(conds ...gen.Condition) ICustomerDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c customerDo) Limit(limit int) ICustomerDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c customerDo) Offset(offset int) ICustomerDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c customerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICustomerDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c customerDo) Unscoped() ICustomerDo {
	return c.withDO(c.DO.Unscoped())
}

func (c customerDo) Create(values ...*models.Customer) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c customerDo) CreateInBatches(values []*models.Customer, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c customerDo) Save(values ...*models.Customer) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c customerDo) First() (*models.Customer, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Customer), nil
	}
}

func (c customerDo) Take() (*models.Customer, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Customer), nil
	}
}

func (c customerDo) Last() (*models.Customer, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Customer), nil
	}
}

func (c customerDo) Find() ([]*models.Customer, error) {
	result, err := c.DO.Find()
	return result.([]*models.Customer), err
}

func (c customerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Customer, err error) {
	buf := make([]*models.Customer, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c customerDo) FindInBatches(result *[]*models.Customer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c customerDo) Attrs(attrs ...field.AssignExpr) ICustomerDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c customerDo) Assign(attrs ...field.AssignExpr) ICustomerDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c customerDo) Joins(fields ...field.RelationField) ICustomerDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c customerDo) Preload(fields ...field.RelationField) ICustomerDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c customerDo) FirstOrInit() (*models.Customer, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Customer), nil
	}
}

func (c customerDo) FirstOrCreate() (*models.Customer, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Customer), nil
	}
}

func (c customerDo) FindByPage(offset int, limit int) (result []*models.Customer, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c customerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c customerDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c customerDo) Delete(models ...*models.Customer) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *customerDo) withDO(do gen.Dao) *customerDo {
	c.DO = *do.(*gen.DO)
	return c
}
