// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HendraaaIrwn/honda-leasing-api/internal/domain/models"
)

func newLeasingProduct(db *gorm.DB, opts ...gen.DOOption) leasingProduct {
	_leasingProduct := leasingProduct{}

	_leasingProduct.leasingProductDo.UseDB(db, opts...)
	_leasingProduct.leasingProductDo.UseModel(&models.LeasingProduct{})

	tableName := _leasingProduct.leasingProductDo.TableName()
	_leasingProduct.ALL = field.NewAsterisk(tableName)
	_leasingProduct.ProductID = field.NewInt64(tableName, "product_id")
	_leasingProduct.KodeProduk = field.NewString(tableName, "kode_produk")
	_leasingProduct.NamaProduk = field.NewString(tableName, "nama_produk")
	_leasingProduct.TenorBulan = field.NewInt16(tableName, "tenor_bulan")
	_leasingProduct.DPPersenMin = field.NewFloat64(tableName, "dp_persen_min")
	_leasingProduct.DPPersenMax = field.NewFloat64(tableName, "dp_persen_max")
	_leasingProduct.BungaFlat = field.NewFloat64(tableName, "bunga_flat")
	_leasingProduct.AdminFee = field.NewFloat64(tableName, "admin_fee")
	_leasingProduct.Asuransi = field.NewBool(tableName, "asuransi")
	_leasingProduct.CreatedAt = field.NewTime(tableName, "created_at")
	_leasingProduct.LeasingContracts = leasingProductHasManyLeasingContracts{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("LeasingContracts", "models.LeasingContract"),
		Customer: struct {
			field.RelationField
			Location struct {
				field.RelationField
				Kelurahan struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}
			}
			LeasingContracts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("LeasingContracts.Customer", "models.Customer"),
			Location: struct {
				field.RelationField
				Kelurahan struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("LeasingContracts.Customer.Location", "models.Location"),
				Kelurahan: struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("LeasingContracts.Customer.Location.Kelurahan", "models.Kelurahan"),
					Kecamatan: struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("LeasingContracts.Customer.Location.Kelurahan.Kecamatan", "models.Kecamatan"),
						Kabupaten: struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("LeasingContracts.Customer.Location.Kelurahan.Kecamatan.Kabupaten", "models.Kabupaten"),
							Province: struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("LeasingContracts.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Province", "models.Province"),
								Kabupaten: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("LeasingContracts.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Province.Kabupaten", "models.Kabupaten"),
								},
							},
							Kecamatan: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("LeasingContracts.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Kecamatan", "models.Kecamatan"),
							},
						},
						Kelurahan: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("LeasingContracts.Customer.Location.Kelurahan.Kecamatan.Kelurahan", "models.Kelurahan"),
						},
					},
					Locations: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("LeasingContracts.Customer.Location.Kelurahan.Locations", "models.Location"),
					},
				},
			},
			LeasingContracts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("LeasingContracts.Customer.LeasingContracts", "models.LeasingContract"),
			},
		},
		Motor: struct {
			field.RelationField
			MotorTypeRef struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}
			MotorAssets struct {
				field.RelationField
				Motor struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("LeasingContracts.Motor", "models.Motor"),
			MotorTypeRef: struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("LeasingContracts.Motor.MotorTypeRef", "models.MotorType"),
				Motors: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LeasingContracts.Motor.MotorTypeRef.Motors", "models.Motor"),
				},
			},
			MotorAssets: struct {
				field.RelationField
				Motor struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("LeasingContracts.Motor.MotorAssets", "models.MotorAsset"),
				Motor: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LeasingContracts.Motor.MotorAssets.Motor", "models.Motor"),
				},
			},
		},
		Product: struct {
			field.RelationField
			LeasingContracts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("LeasingContracts.Product", "models.LeasingProduct"),
			LeasingContracts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("LeasingContracts.Product.LeasingContracts", "models.LeasingContract"),
			},
		},
		LeasingTasks: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Role struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}
			LeasingAttribute struct {
				field.RelationField
				Task struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("LeasingContracts.LeasingTasks", "models.LeasingTask"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Contract", "models.LeasingContract"),
			},
			Role: struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role", "models.Role"),
				UserRoles: struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles", "models.UserRole"),
					User: struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles.User", "models.User"),
						UserOAuthProviders: struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}{
							RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles.User.UserOAuthProviders", "models.UserOAuthProvider"),
							User: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.User", "models.User"),
							},
							Provider: struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.Provider", "models.OAuthProvider"),
								UserOAuthProviders: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.Provider.UserOAuthProviders", "models.UserOAuthProvider"),
								},
							},
						},
						UserRoles: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles.User.UserRoles", "models.UserRole"),
						},
					},
					Role: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.UserRoles.Role", "models.Role"),
					},
				},
				RolePermissions: struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.RolePermissions", "models.RolePermission"),
					Role: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.RolePermissions.Role", "models.Role"),
					},
					Permission: struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.RolePermissions.Permission", "models.Permission"),
						RolePermissions: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("LeasingContracts.LeasingTasks.Role.RolePermissions.Permission.RolePermissions", "models.RolePermission"),
						},
					},
				},
			},
			LeasingAttribute: struct {
				field.RelationField
				Task struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("LeasingContracts.LeasingTasks.LeasingAttribute", "models.LeasingTaskAttribute"),
				Task: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LeasingContracts.LeasingTasks.LeasingAttribute.Task", "models.LeasingTask"),
				},
			},
		},
		PaymentSchedules: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Payments struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Schedule struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("LeasingContracts.PaymentSchedules", "models.PaymentSchedule"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("LeasingContracts.PaymentSchedules.Contract", "models.LeasingContract"),
			},
			Payments: struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Schedule struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("LeasingContracts.PaymentSchedules.Payments", "models.Payment"),
				Contract: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LeasingContracts.PaymentSchedules.Payments.Contract", "models.LeasingContract"),
				},
				Schedule: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LeasingContracts.PaymentSchedules.Payments.Schedule", "models.PaymentSchedule"),
				},
			},
		},
		Payments: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("LeasingContracts.Payments", "models.Payment"),
		},
		ContractDocuments: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("LeasingContracts.ContractDocuments", "models.LeasingContractDocument"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("LeasingContracts.ContractDocuments.Contract", "models.LeasingContract"),
			},
		},
	}

	_leasingProduct.fillFieldMap()

	return _leasingProduct
}

type leasingProduct struct {
	leasingProductDo

	ALL              field.Asterisk
	ProductID        field.Int64
	KodeProduk       field.String
	NamaProduk       field.String
	TenorBulan       field.Int16
	DPPersenMin      field.Float64
	DPPersenMax      field.Float64
	BungaFlat        field.Float64
	AdminFee         field.Float64
	Asuransi         field.Bool
	CreatedAt        field.Time
	LeasingContracts leasingProductHasManyLeasingContracts

	fieldMap map[string]field.Expr
}

func (l leasingProduct) Table(newTableName string) *leasingProduct {
	l.leasingProductDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l leasingProduct) As(alias string) *leasingProduct {
	l.leasingProductDo.DO = *(l.leasingProductDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *leasingProduct) updateTableName(table string) *leasingProduct {
	l.ALL = field.NewAsterisk(table)
	l.ProductID = field.NewInt64(table, "product_id")
	l.KodeProduk = field.NewString(table, "kode_produk")
	l.NamaProduk = field.NewString(table, "nama_produk")
	l.TenorBulan = field.NewInt16(table, "tenor_bulan")
	l.DPPersenMin = field.NewFloat64(table, "dp_persen_min")
	l.DPPersenMax = field.NewFloat64(table, "dp_persen_max")
	l.BungaFlat = field.NewFloat64(table, "bunga_flat")
	l.AdminFee = field.NewFloat64(table, "admin_fee")
	l.Asuransi = field.NewBool(table, "asuransi")
	l.CreatedAt = field.NewTime(table, "created_at")

	l.fillFieldMap()

	return l
}

func (l *leasingProduct) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *leasingProduct) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 11)
	l.fieldMap["product_id"] = l.ProductID
	l.fieldMap["kode_produk"] = l.KodeProduk
	l.fieldMap["nama_produk"] = l.NamaProduk
	l.fieldMap["tenor_bulan"] = l.TenorBulan
	l.fieldMap["dp_persen_min"] = l.DPPersenMin
	l.fieldMap["dp_persen_max"] = l.DPPersenMax
	l.fieldMap["bunga_flat"] = l.BungaFlat
	l.fieldMap["admin_fee"] = l.AdminFee
	l.fieldMap["asuransi"] = l.Asuransi
	l.fieldMap["created_at"] = l.CreatedAt

}

func (l leasingProduct) clone(db *gorm.DB) leasingProduct {
	l.leasingProductDo.ReplaceConnPool(db.Statement.ConnPool)
	l.LeasingContracts.db = db.Session(&gorm.Session{Initialized: true})
	l.LeasingContracts.db.Statement.ConnPool = db.Statement.ConnPool
	return l
}

func (l leasingProduct) replaceDB(db *gorm.DB) leasingProduct {
	l.leasingProductDo.ReplaceDB(db)
	l.LeasingContracts.db = db.Session(&gorm.Session{})
	return l
}

type leasingProductHasManyLeasingContracts struct {
	db *gorm.DB

	field.RelationField

	Customer struct {
		field.RelationField
		Location struct {
			field.RelationField
			Kelurahan struct {
				field.RelationField
				Kecamatan struct {
					field.RelationField
					Kabupaten struct {
						field.RelationField
						Province struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
							}
						}
						Kecamatan struct {
							field.RelationField
						}
					}
					Kelurahan struct {
						field.RelationField
					}
				}
				Locations struct {
					field.RelationField
				}
			}
		}
		LeasingContracts struct {
			field.RelationField
		}
	}
	Motor struct {
		field.RelationField
		MotorTypeRef struct {
			field.RelationField
			Motors struct {
				field.RelationField
			}
		}
		MotorAssets struct {
			field.RelationField
			Motor struct {
				field.RelationField
			}
		}
	}
	Product struct {
		field.RelationField
		LeasingContracts struct {
			field.RelationField
		}
	}
	LeasingTasks struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
		Role struct {
			field.RelationField
			UserRoles struct {
				field.RelationField
				User struct {
					field.RelationField
					UserOAuthProviders struct {
						field.RelationField
						User struct {
							field.RelationField
						}
						Provider struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}
					}
					UserRoles struct {
						field.RelationField
					}
				}
				Role struct {
					field.RelationField
				}
			}
			RolePermissions struct {
				field.RelationField
				Role struct {
					field.RelationField
				}
				Permission struct {
					field.RelationField
					RolePermissions struct {
						field.RelationField
					}
				}
			}
		}
		LeasingAttribute struct {
			field.RelationField
			Task struct {
				field.RelationField
			}
		}
	}
	PaymentSchedules struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
		Payments struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Schedule struct {
				field.RelationField
			}
		}
	}
	Payments struct {
		field.RelationField
	}
	ContractDocuments struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
	}
}

func (a leasingProductHasManyLeasingContracts) Where(conds ...field.Expr) *leasingProductHasManyLeasingContracts {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a leasingProductHasManyLeasingContracts) WithContext(ctx context.Context) *leasingProductHasManyLeasingContracts {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a leasingProductHasManyLeasingContracts) Session(session *gorm.Session) *leasingProductHasManyLeasingContracts {
	a.db = a.db.Session(session)
	return &a
}

func (a leasingProductHasManyLeasingContracts) Model(m *models.LeasingProduct) *leasingProductHasManyLeasingContractsTx {
	return &leasingProductHasManyLeasingContractsTx{a.db.Model(m).Association(a.Name())}
}

func (a leasingProductHasManyLeasingContracts) Unscoped() *leasingProductHasManyLeasingContracts {
	a.db = a.db.Unscoped()
	return &a
}

type leasingProductHasManyLeasingContractsTx struct{ tx *gorm.Association }

func (a leasingProductHasManyLeasingContractsTx) Find() (result []*models.LeasingContract, err error) {
	return result, a.tx.Find(&result)
}

func (a leasingProductHasManyLeasingContractsTx) Append(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a leasingProductHasManyLeasingContractsTx) Replace(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a leasingProductHasManyLeasingContractsTx) Delete(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a leasingProductHasManyLeasingContractsTx) Clear() error {
	return a.tx.Clear()
}

func (a leasingProductHasManyLeasingContractsTx) Count() int64 {
	return a.tx.Count()
}

func (a leasingProductHasManyLeasingContractsTx) Unscoped() *leasingProductHasManyLeasingContractsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type leasingProductDo struct{ gen.DO }

type ILeasingProductDo interface {
	gen.SubQuery
	Debug() ILeasingProductDo
	WithContext(ctx context.Context) ILeasingProductDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILeasingProductDo
	WriteDB() ILeasingProductDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILeasingProductDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILeasingProductDo
	Not(conds ...gen.Condition) ILeasingProductDo
	Or(conds ...gen.Condition) ILeasingProductDo
	Select(conds ...field.Expr) ILeasingProductDo
	Where(conds ...gen.Condition) ILeasingProductDo
	Order(conds ...field.Expr) ILeasingProductDo
	Distinct(cols ...field.Expr) ILeasingProductDo
	Omit(cols ...field.Expr) ILeasingProductDo
	Join(table schema.Tabler, on ...field.Expr) ILeasingProductDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingProductDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILeasingProductDo
	Group(cols ...field.Expr) ILeasingProductDo
	Having(conds ...gen.Condition) ILeasingProductDo
	Limit(limit int) ILeasingProductDo
	Offset(offset int) ILeasingProductDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingProductDo
	Unscoped() ILeasingProductDo
	Create(values ...*models.LeasingProduct) error
	CreateInBatches(values []*models.LeasingProduct, batchSize int) error
	Save(values ...*models.LeasingProduct) error
	First() (*models.LeasingProduct, error)
	Take() (*models.LeasingProduct, error)
	Last() (*models.LeasingProduct, error)
	Find() ([]*models.LeasingProduct, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LeasingProduct, err error)
	FindInBatches(result *[]*models.LeasingProduct, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.LeasingProduct) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILeasingProductDo
	Assign(attrs ...field.AssignExpr) ILeasingProductDo
	Joins(fields ...field.RelationField) ILeasingProductDo
	Preload(fields ...field.RelationField) ILeasingProductDo
	FirstOrInit() (*models.LeasingProduct, error)
	FirstOrCreate() (*models.LeasingProduct, error)
	FindByPage(offset int, limit int) (result []*models.LeasingProduct, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILeasingProductDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l leasingProductDo) Debug() ILeasingProductDo {
	return l.withDO(l.DO.Debug())
}

func (l leasingProductDo) WithContext(ctx context.Context) ILeasingProductDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l leasingProductDo) ReadDB() ILeasingProductDo {
	return l.Clauses(dbresolver.Read)
}

func (l leasingProductDo) WriteDB() ILeasingProductDo {
	return l.Clauses(dbresolver.Write)
}

func (l leasingProductDo) Session(config *gorm.Session) ILeasingProductDo {
	return l.withDO(l.DO.Session(config))
}

func (l leasingProductDo) Clauses(conds ...clause.Expression) ILeasingProductDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l leasingProductDo) Returning(value interface{}, columns ...string) ILeasingProductDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l leasingProductDo) Not(conds ...gen.Condition) ILeasingProductDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l leasingProductDo) Or(conds ...gen.Condition) ILeasingProductDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l leasingProductDo) Select(conds ...field.Expr) ILeasingProductDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l leasingProductDo) Where(conds ...gen.Condition) ILeasingProductDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l leasingProductDo) Order(conds ...field.Expr) ILeasingProductDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l leasingProductDo) Distinct(cols ...field.Expr) ILeasingProductDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l leasingProductDo) Omit(cols ...field.Expr) ILeasingProductDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l leasingProductDo) Join(table schema.Tabler, on ...field.Expr) ILeasingProductDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l leasingProductDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingProductDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l leasingProductDo) RightJoin(table schema.Tabler, on ...field.Expr) ILeasingProductDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l leasingProductDo) Group(cols ...field.Expr) ILeasingProductDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l leasingProductDo) Having(conds ...gen.Condition) ILeasingProductDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l leasingProductDo) Limit(limit int) ILeasingProductDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l leasingProductDo) Offset(offset int) ILeasingProductDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l leasingProductDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingProductDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l leasingProductDo) Unscoped() ILeasingProductDo {
	return l.withDO(l.DO.Unscoped())
}

func (l leasingProductDo) Create(values ...*models.LeasingProduct) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l leasingProductDo) CreateInBatches(values []*models.LeasingProduct, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l leasingProductDo) Save(values ...*models.LeasingProduct) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l leasingProductDo) First() (*models.LeasingProduct, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingProduct), nil
	}
}

func (l leasingProductDo) Take() (*models.LeasingProduct, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingProduct), nil
	}
}

func (l leasingProductDo) Last() (*models.LeasingProduct, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingProduct), nil
	}
}

func (l leasingProductDo) Find() ([]*models.LeasingProduct, error) {
	result, err := l.DO.Find()
	return result.([]*models.LeasingProduct), err
}

func (l leasingProductDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LeasingProduct, err error) {
	buf := make([]*models.LeasingProduct, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l leasingProductDo) FindInBatches(result *[]*models.LeasingProduct, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l leasingProductDo) Attrs(attrs ...field.AssignExpr) ILeasingProductDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l leasingProductDo) Assign(attrs ...field.AssignExpr) ILeasingProductDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l leasingProductDo) Joins(fields ...field.RelationField) ILeasingProductDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l leasingProductDo) Preload(fields ...field.RelationField) ILeasingProductDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l leasingProductDo) FirstOrInit() (*models.LeasingProduct, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingProduct), nil
	}
}

func (l leasingProductDo) FirstOrCreate() (*models.LeasingProduct, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingProduct), nil
	}
}

func (l leasingProductDo) FindByPage(offset int, limit int) (result []*models.LeasingProduct, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l leasingProductDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l leasingProductDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l leasingProductDo) Delete(models ...*models.LeasingProduct) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *leasingProductDo) withDO(do gen.Dao) *leasingProductDo {
	l.DO = *do.(*gen.DO)
	return l
}
