// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HendraaaIrwn/honda-leasing-api/internal/domain/models"
)

func newLeasingContract(db *gorm.DB, opts ...gen.DOOption) leasingContract {
	_leasingContract := leasingContract{}

	_leasingContract.leasingContractDo.UseDB(db, opts...)
	_leasingContract.leasingContractDo.UseModel(&models.LeasingContract{})

	tableName := _leasingContract.leasingContractDo.TableName()
	_leasingContract.ALL = field.NewAsterisk(tableName)
	_leasingContract.ContractID = field.NewInt64(tableName, "contract_id")
	_leasingContract.ContractNumber = field.NewString(tableName, "contract_number")
	_leasingContract.RequestDate = field.NewTime(tableName, "request_date")
	_leasingContract.TanggalAkad = field.NewTime(tableName, "tanggal_akad")
	_leasingContract.TanggalMulaiCicil = field.NewTime(tableName, "tanggal_mulai_cicil")
	_leasingContract.TenorBulan = field.NewInt16(tableName, "tenor_bulan")
	_leasingContract.NilaiKendaraan = field.NewFloat64(tableName, "nilai_kendaraan")
	_leasingContract.DPDibayar = field.NewFloat64(tableName, "dp_dibayar")
	_leasingContract.PokokPinjaman = field.NewFloat64(tableName, "pokok_pinjaman")
	_leasingContract.TotalPinjaman = field.NewFloat64(tableName, "total_pinjaman")
	_leasingContract.CicilanPerBulan = field.NewFloat64(tableName, "cicilan_per_bulan")
	_leasingContract.Status = field.NewString(tableName, "status")
	_leasingContract.CreatedAt = field.NewTime(tableName, "created_at")
	_leasingContract.UpdatedAt = field.NewTime(tableName, "updated_at")
	_leasingContract.CustomerID = field.NewInt64(tableName, "customer_id")
	_leasingContract.MotorID = field.NewInt64(tableName, "motor_id")
	_leasingContract.ProductID = field.NewInt64(tableName, "product_id")
	_leasingContract.Customer = leasingContractHasOneCustomer{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Customer", "models.Customer"),
		Location: struct {
			field.RelationField
			Kelurahan struct {
				field.RelationField
				Kecamatan struct {
					field.RelationField
					Kabupaten struct {
						field.RelationField
						Province struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
							}
						}
						Kecamatan struct {
							field.RelationField
						}
					}
					Kelurahan struct {
						field.RelationField
					}
				}
				Locations struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Customer.Location", "models.Location"),
			Kelurahan: struct {
				field.RelationField
				Kecamatan struct {
					field.RelationField
					Kabupaten struct {
						field.RelationField
						Province struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
							}
						}
						Kecamatan struct {
							field.RelationField
						}
					}
					Kelurahan struct {
						field.RelationField
					}
				}
				Locations struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Customer.Location.Kelurahan", "models.Kelurahan"),
				Kecamatan: struct {
					field.RelationField
					Kabupaten struct {
						field.RelationField
						Province struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
							}
						}
						Kecamatan struct {
							field.RelationField
						}
					}
					Kelurahan struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Customer.Location.Kelurahan.Kecamatan", "models.Kecamatan"),
					Kabupaten: struct {
						field.RelationField
						Province struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
							}
						}
						Kecamatan struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Customer.Location.Kelurahan.Kecamatan.Kabupaten", "models.Kabupaten"),
						Province: struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Customer.Location.Kelurahan.Kecamatan.Kabupaten.Province", "models.Province"),
							Kabupaten: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Customer.Location.Kelurahan.Kecamatan.Kabupaten.Province.Kabupaten", "models.Kabupaten"),
							},
						},
						Kecamatan: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Customer.Location.Kelurahan.Kecamatan.Kabupaten.Kecamatan", "models.Kecamatan"),
						},
					},
					Kelurahan: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Customer.Location.Kelurahan.Kecamatan.Kelurahan", "models.Kelurahan"),
					},
				},
				Locations: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Customer.Location.Kelurahan.Locations", "models.Location"),
				},
			},
		},
		LeasingContracts: struct {
			field.RelationField
			Customer struct {
				field.RelationField
			}
			Motor struct {
				field.RelationField
				MotorTypeRef struct {
					field.RelationField
					Motors struct {
						field.RelationField
					}
				}
				MotorAssets struct {
					field.RelationField
					Motor struct {
						field.RelationField
					}
				}
			}
			Product struct {
				field.RelationField
				LeasingContracts struct {
					field.RelationField
				}
			}
			LeasingTasks struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Role struct {
					field.RelationField
					UserRoles struct {
						field.RelationField
						User struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
								User struct {
									field.RelationField
								}
								Provider struct {
									field.RelationField
									UserOAuthProviders struct {
										field.RelationField
									}
								}
							}
							UserRoles struct {
								field.RelationField
							}
						}
						Role struct {
							field.RelationField
						}
					}
					RolePermissions struct {
						field.RelationField
						Role struct {
							field.RelationField
						}
						Permission struct {
							field.RelationField
							RolePermissions struct {
								field.RelationField
							}
						}
					}
				}
				LeasingAttribute struct {
					field.RelationField
					Task struct {
						field.RelationField
					}
				}
			}
			PaymentSchedules struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Payments struct {
					field.RelationField
					Contract struct {
						field.RelationField
					}
					Schedule struct {
						field.RelationField
					}
				}
			}
			Payments struct {
				field.RelationField
			}
			ContractDocuments struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Customer.LeasingContracts", "models.LeasingContract"),
			Customer: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Customer.LeasingContracts.Customer", "models.Customer"),
			},
			Motor: struct {
				field.RelationField
				MotorTypeRef struct {
					field.RelationField
					Motors struct {
						field.RelationField
					}
				}
				MotorAssets struct {
					field.RelationField
					Motor struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Customer.LeasingContracts.Motor", "models.Motor"),
				MotorTypeRef: struct {
					field.RelationField
					Motors struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Customer.LeasingContracts.Motor.MotorTypeRef", "models.MotorType"),
					Motors: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Customer.LeasingContracts.Motor.MotorTypeRef.Motors", "models.Motor"),
					},
				},
				MotorAssets: struct {
					field.RelationField
					Motor struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Customer.LeasingContracts.Motor.MotorAssets", "models.MotorAsset"),
					Motor: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Customer.LeasingContracts.Motor.MotorAssets.Motor", "models.Motor"),
					},
				},
			},
			Product: struct {
				field.RelationField
				LeasingContracts struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Customer.LeasingContracts.Product", "models.LeasingProduct"),
				LeasingContracts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Customer.LeasingContracts.Product.LeasingContracts", "models.LeasingContract"),
				},
			},
			LeasingTasks: struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Role struct {
					field.RelationField
					UserRoles struct {
						field.RelationField
						User struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
								User struct {
									field.RelationField
								}
								Provider struct {
									field.RelationField
									UserOAuthProviders struct {
										field.RelationField
									}
								}
							}
							UserRoles struct {
								field.RelationField
							}
						}
						Role struct {
							field.RelationField
						}
					}
					RolePermissions struct {
						field.RelationField
						Role struct {
							field.RelationField
						}
						Permission struct {
							field.RelationField
							RolePermissions struct {
								field.RelationField
							}
						}
					}
				}
				LeasingAttribute struct {
					field.RelationField
					Task struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks", "models.LeasingTask"),
				Contract: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.Contract", "models.LeasingContract"),
				},
				Role: struct {
					field.RelationField
					UserRoles struct {
						field.RelationField
						User struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
								User struct {
									field.RelationField
								}
								Provider struct {
									field.RelationField
									UserOAuthProviders struct {
										field.RelationField
									}
								}
							}
							UserRoles struct {
								field.RelationField
							}
						}
						Role struct {
							field.RelationField
						}
					}
					RolePermissions struct {
						field.RelationField
						Role struct {
							field.RelationField
						}
						Permission struct {
							field.RelationField
							RolePermissions struct {
								field.RelationField
							}
						}
					}
				}{
					RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.Role", "models.Role"),
					UserRoles: struct {
						field.RelationField
						User struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
								User struct {
									field.RelationField
								}
								Provider struct {
									field.RelationField
									UserOAuthProviders struct {
										field.RelationField
									}
								}
							}
							UserRoles struct {
								field.RelationField
							}
						}
						Role struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.Role.UserRoles", "models.UserRole"),
						User: struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
								User struct {
									field.RelationField
								}
								Provider struct {
									field.RelationField
									UserOAuthProviders struct {
										field.RelationField
									}
								}
							}
							UserRoles struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.Role.UserRoles.User", "models.User"),
							UserOAuthProviders: struct {
								field.RelationField
								User struct {
									field.RelationField
								}
								Provider struct {
									field.RelationField
									UserOAuthProviders struct {
										field.RelationField
									}
								}
							}{
								RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.Role.UserRoles.User.UserOAuthProviders", "models.UserOAuthProvider"),
								User: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.User", "models.User"),
								},
								Provider: struct {
									field.RelationField
									UserOAuthProviders struct {
										field.RelationField
									}
								}{
									RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.Provider", "models.OAuthProvider"),
									UserOAuthProviders: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.Provider.UserOAuthProviders", "models.UserOAuthProvider"),
									},
								},
							},
							UserRoles: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.Role.UserRoles.User.UserRoles", "models.UserRole"),
							},
						},
						Role: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.Role.UserRoles.Role", "models.Role"),
						},
					},
					RolePermissions: struct {
						field.RelationField
						Role struct {
							field.RelationField
						}
						Permission struct {
							field.RelationField
							RolePermissions struct {
								field.RelationField
							}
						}
					}{
						RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.Role.RolePermissions", "models.RolePermission"),
						Role: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.Role.RolePermissions.Role", "models.Role"),
						},
						Permission: struct {
							field.RelationField
							RolePermissions struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.Role.RolePermissions.Permission", "models.Permission"),
							RolePermissions: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.Role.RolePermissions.Permission.RolePermissions", "models.RolePermission"),
							},
						},
					},
				},
				LeasingAttribute: struct {
					field.RelationField
					Task struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.LeasingAttribute", "models.LeasingTaskAttribute"),
					Task: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Customer.LeasingContracts.LeasingTasks.LeasingAttribute.Task", "models.LeasingTask"),
					},
				},
			},
			PaymentSchedules: struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Payments struct {
					field.RelationField
					Contract struct {
						field.RelationField
					}
					Schedule struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Customer.LeasingContracts.PaymentSchedules", "models.PaymentSchedule"),
				Contract: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Customer.LeasingContracts.PaymentSchedules.Contract", "models.LeasingContract"),
				},
				Payments: struct {
					field.RelationField
					Contract struct {
						field.RelationField
					}
					Schedule struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Customer.LeasingContracts.PaymentSchedules.Payments", "models.Payment"),
					Contract: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Customer.LeasingContracts.PaymentSchedules.Payments.Contract", "models.LeasingContract"),
					},
					Schedule: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Customer.LeasingContracts.PaymentSchedules.Payments.Schedule", "models.PaymentSchedule"),
					},
				},
			},
			Payments: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Customer.LeasingContracts.Payments", "models.Payment"),
			},
			ContractDocuments: struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Customer.LeasingContracts.ContractDocuments", "models.LeasingContractDocument"),
				Contract: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Customer.LeasingContracts.ContractDocuments.Contract", "models.LeasingContract"),
				},
			},
		},
	}

	_leasingContract.Motor = leasingContractHasOneMotor{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Motor", "models.Motor"),
	}

	_leasingContract.Product = leasingContractHasOneProduct{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Product", "models.LeasingProduct"),
	}

	_leasingContract.LeasingTasks = leasingContractHasManyLeasingTasks{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("LeasingTasks", "models.LeasingTask"),
	}

	_leasingContract.PaymentSchedules = leasingContractHasManyPaymentSchedules{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("PaymentSchedules", "models.PaymentSchedule"),
	}

	_leasingContract.Payments = leasingContractHasManyPayments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Payments", "models.Payment"),
	}

	_leasingContract.ContractDocuments = leasingContractHasManyContractDocuments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ContractDocuments", "models.LeasingContractDocument"),
	}

	_leasingContract.fillFieldMap()

	return _leasingContract
}

type leasingContract struct {
	leasingContractDo

	ALL               field.Asterisk
	ContractID        field.Int64
	ContractNumber    field.String
	RequestDate       field.Time
	TanggalAkad       field.Time
	TanggalMulaiCicil field.Time
	TenorBulan        field.Int16
	NilaiKendaraan    field.Float64
	DPDibayar         field.Float64
	PokokPinjaman     field.Float64
	TotalPinjaman     field.Float64
	CicilanPerBulan   field.Float64
	Status            field.String
	CreatedAt         field.Time
	UpdatedAt         field.Time
	CustomerID        field.Int64
	MotorID           field.Int64
	ProductID         field.Int64
	Customer          leasingContractHasOneCustomer

	Motor leasingContractHasOneMotor

	Product leasingContractHasOneProduct

	LeasingTasks leasingContractHasManyLeasingTasks

	PaymentSchedules leasingContractHasManyPaymentSchedules

	Payments leasingContractHasManyPayments

	ContractDocuments leasingContractHasManyContractDocuments

	fieldMap map[string]field.Expr
}

func (l leasingContract) Table(newTableName string) *leasingContract {
	l.leasingContractDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l leasingContract) As(alias string) *leasingContract {
	l.leasingContractDo.DO = *(l.leasingContractDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *leasingContract) updateTableName(table string) *leasingContract {
	l.ALL = field.NewAsterisk(table)
	l.ContractID = field.NewInt64(table, "contract_id")
	l.ContractNumber = field.NewString(table, "contract_number")
	l.RequestDate = field.NewTime(table, "request_date")
	l.TanggalAkad = field.NewTime(table, "tanggal_akad")
	l.TanggalMulaiCicil = field.NewTime(table, "tanggal_mulai_cicil")
	l.TenorBulan = field.NewInt16(table, "tenor_bulan")
	l.NilaiKendaraan = field.NewFloat64(table, "nilai_kendaraan")
	l.DPDibayar = field.NewFloat64(table, "dp_dibayar")
	l.PokokPinjaman = field.NewFloat64(table, "pokok_pinjaman")
	l.TotalPinjaman = field.NewFloat64(table, "total_pinjaman")
	l.CicilanPerBulan = field.NewFloat64(table, "cicilan_per_bulan")
	l.Status = field.NewString(table, "status")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")
	l.CustomerID = field.NewInt64(table, "customer_id")
	l.MotorID = field.NewInt64(table, "motor_id")
	l.ProductID = field.NewInt64(table, "product_id")

	l.fillFieldMap()

	return l
}

func (l *leasingContract) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *leasingContract) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 24)
	l.fieldMap["contract_id"] = l.ContractID
	l.fieldMap["contract_number"] = l.ContractNumber
	l.fieldMap["request_date"] = l.RequestDate
	l.fieldMap["tanggal_akad"] = l.TanggalAkad
	l.fieldMap["tanggal_mulai_cicil"] = l.TanggalMulaiCicil
	l.fieldMap["tenor_bulan"] = l.TenorBulan
	l.fieldMap["nilai_kendaraan"] = l.NilaiKendaraan
	l.fieldMap["dp_dibayar"] = l.DPDibayar
	l.fieldMap["pokok_pinjaman"] = l.PokokPinjaman
	l.fieldMap["total_pinjaman"] = l.TotalPinjaman
	l.fieldMap["cicilan_per_bulan"] = l.CicilanPerBulan
	l.fieldMap["status"] = l.Status
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
	l.fieldMap["customer_id"] = l.CustomerID
	l.fieldMap["motor_id"] = l.MotorID
	l.fieldMap["product_id"] = l.ProductID

}

func (l leasingContract) clone(db *gorm.DB) leasingContract {
	l.leasingContractDo.ReplaceConnPool(db.Statement.ConnPool)
	l.Customer.db = db.Session(&gorm.Session{Initialized: true})
	l.Customer.db.Statement.ConnPool = db.Statement.ConnPool
	l.Motor.db = db.Session(&gorm.Session{Initialized: true})
	l.Motor.db.Statement.ConnPool = db.Statement.ConnPool
	l.Product.db = db.Session(&gorm.Session{Initialized: true})
	l.Product.db.Statement.ConnPool = db.Statement.ConnPool
	l.LeasingTasks.db = db.Session(&gorm.Session{Initialized: true})
	l.LeasingTasks.db.Statement.ConnPool = db.Statement.ConnPool
	l.PaymentSchedules.db = db.Session(&gorm.Session{Initialized: true})
	l.PaymentSchedules.db.Statement.ConnPool = db.Statement.ConnPool
	l.Payments.db = db.Session(&gorm.Session{Initialized: true})
	l.Payments.db.Statement.ConnPool = db.Statement.ConnPool
	l.ContractDocuments.db = db.Session(&gorm.Session{Initialized: true})
	l.ContractDocuments.db.Statement.ConnPool = db.Statement.ConnPool
	return l
}

func (l leasingContract) replaceDB(db *gorm.DB) leasingContract {
	l.leasingContractDo.ReplaceDB(db)
	l.Customer.db = db.Session(&gorm.Session{})
	l.Motor.db = db.Session(&gorm.Session{})
	l.Product.db = db.Session(&gorm.Session{})
	l.LeasingTasks.db = db.Session(&gorm.Session{})
	l.PaymentSchedules.db = db.Session(&gorm.Session{})
	l.Payments.db = db.Session(&gorm.Session{})
	l.ContractDocuments.db = db.Session(&gorm.Session{})
	return l
}

type leasingContractHasOneCustomer struct {
	db *gorm.DB

	field.RelationField

	Location struct {
		field.RelationField
		Kelurahan struct {
			field.RelationField
			Kecamatan struct {
				field.RelationField
				Kabupaten struct {
					field.RelationField
					Province struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
						}
					}
					Kecamatan struct {
						field.RelationField
					}
				}
				Kelurahan struct {
					field.RelationField
				}
			}
			Locations struct {
				field.RelationField
			}
		}
	}
	LeasingContracts struct {
		field.RelationField
		Customer struct {
			field.RelationField
		}
		Motor struct {
			field.RelationField
			MotorTypeRef struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}
			MotorAssets struct {
				field.RelationField
				Motor struct {
					field.RelationField
				}
			}
		}
		Product struct {
			field.RelationField
			LeasingContracts struct {
				field.RelationField
			}
		}
		LeasingTasks struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Role struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}
			LeasingAttribute struct {
				field.RelationField
				Task struct {
					field.RelationField
				}
			}
		}
		PaymentSchedules struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Payments struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Schedule struct {
					field.RelationField
				}
			}
		}
		Payments struct {
			field.RelationField
		}
		ContractDocuments struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
		}
	}
}

func (a leasingContractHasOneCustomer) Where(conds ...field.Expr) *leasingContractHasOneCustomer {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a leasingContractHasOneCustomer) WithContext(ctx context.Context) *leasingContractHasOneCustomer {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a leasingContractHasOneCustomer) Session(session *gorm.Session) *leasingContractHasOneCustomer {
	a.db = a.db.Session(session)
	return &a
}

func (a leasingContractHasOneCustomer) Model(m *models.LeasingContract) *leasingContractHasOneCustomerTx {
	return &leasingContractHasOneCustomerTx{a.db.Model(m).Association(a.Name())}
}

func (a leasingContractHasOneCustomer) Unscoped() *leasingContractHasOneCustomer {
	a.db = a.db.Unscoped()
	return &a
}

type leasingContractHasOneCustomerTx struct{ tx *gorm.Association }

func (a leasingContractHasOneCustomerTx) Find() (result *models.Customer, err error) {
	return result, a.tx.Find(&result)
}

func (a leasingContractHasOneCustomerTx) Append(values ...*models.Customer) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a leasingContractHasOneCustomerTx) Replace(values ...*models.Customer) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a leasingContractHasOneCustomerTx) Delete(values ...*models.Customer) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a leasingContractHasOneCustomerTx) Clear() error {
	return a.tx.Clear()
}

func (a leasingContractHasOneCustomerTx) Count() int64 {
	return a.tx.Count()
}

func (a leasingContractHasOneCustomerTx) Unscoped() *leasingContractHasOneCustomerTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type leasingContractHasOneMotor struct {
	db *gorm.DB

	field.RelationField
}

func (a leasingContractHasOneMotor) Where(conds ...field.Expr) *leasingContractHasOneMotor {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a leasingContractHasOneMotor) WithContext(ctx context.Context) *leasingContractHasOneMotor {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a leasingContractHasOneMotor) Session(session *gorm.Session) *leasingContractHasOneMotor {
	a.db = a.db.Session(session)
	return &a
}

func (a leasingContractHasOneMotor) Model(m *models.LeasingContract) *leasingContractHasOneMotorTx {
	return &leasingContractHasOneMotorTx{a.db.Model(m).Association(a.Name())}
}

func (a leasingContractHasOneMotor) Unscoped() *leasingContractHasOneMotor {
	a.db = a.db.Unscoped()
	return &a
}

type leasingContractHasOneMotorTx struct{ tx *gorm.Association }

func (a leasingContractHasOneMotorTx) Find() (result *models.Motor, err error) {
	return result, a.tx.Find(&result)
}

func (a leasingContractHasOneMotorTx) Append(values ...*models.Motor) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a leasingContractHasOneMotorTx) Replace(values ...*models.Motor) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a leasingContractHasOneMotorTx) Delete(values ...*models.Motor) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a leasingContractHasOneMotorTx) Clear() error {
	return a.tx.Clear()
}

func (a leasingContractHasOneMotorTx) Count() int64 {
	return a.tx.Count()
}

func (a leasingContractHasOneMotorTx) Unscoped() *leasingContractHasOneMotorTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type leasingContractHasOneProduct struct {
	db *gorm.DB

	field.RelationField
}

func (a leasingContractHasOneProduct) Where(conds ...field.Expr) *leasingContractHasOneProduct {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a leasingContractHasOneProduct) WithContext(ctx context.Context) *leasingContractHasOneProduct {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a leasingContractHasOneProduct) Session(session *gorm.Session) *leasingContractHasOneProduct {
	a.db = a.db.Session(session)
	return &a
}

func (a leasingContractHasOneProduct) Model(m *models.LeasingContract) *leasingContractHasOneProductTx {
	return &leasingContractHasOneProductTx{a.db.Model(m).Association(a.Name())}
}

func (a leasingContractHasOneProduct) Unscoped() *leasingContractHasOneProduct {
	a.db = a.db.Unscoped()
	return &a
}

type leasingContractHasOneProductTx struct{ tx *gorm.Association }

func (a leasingContractHasOneProductTx) Find() (result *models.LeasingProduct, err error) {
	return result, a.tx.Find(&result)
}

func (a leasingContractHasOneProductTx) Append(values ...*models.LeasingProduct) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a leasingContractHasOneProductTx) Replace(values ...*models.LeasingProduct) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a leasingContractHasOneProductTx) Delete(values ...*models.LeasingProduct) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a leasingContractHasOneProductTx) Clear() error {
	return a.tx.Clear()
}

func (a leasingContractHasOneProductTx) Count() int64 {
	return a.tx.Count()
}

func (a leasingContractHasOneProductTx) Unscoped() *leasingContractHasOneProductTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type leasingContractHasManyLeasingTasks struct {
	db *gorm.DB

	field.RelationField
}

func (a leasingContractHasManyLeasingTasks) Where(conds ...field.Expr) *leasingContractHasManyLeasingTasks {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a leasingContractHasManyLeasingTasks) WithContext(ctx context.Context) *leasingContractHasManyLeasingTasks {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a leasingContractHasManyLeasingTasks) Session(session *gorm.Session) *leasingContractHasManyLeasingTasks {
	a.db = a.db.Session(session)
	return &a
}

func (a leasingContractHasManyLeasingTasks) Model(m *models.LeasingContract) *leasingContractHasManyLeasingTasksTx {
	return &leasingContractHasManyLeasingTasksTx{a.db.Model(m).Association(a.Name())}
}

func (a leasingContractHasManyLeasingTasks) Unscoped() *leasingContractHasManyLeasingTasks {
	a.db = a.db.Unscoped()
	return &a
}

type leasingContractHasManyLeasingTasksTx struct{ tx *gorm.Association }

func (a leasingContractHasManyLeasingTasksTx) Find() (result []*models.LeasingTask, err error) {
	return result, a.tx.Find(&result)
}

func (a leasingContractHasManyLeasingTasksTx) Append(values ...*models.LeasingTask) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a leasingContractHasManyLeasingTasksTx) Replace(values ...*models.LeasingTask) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a leasingContractHasManyLeasingTasksTx) Delete(values ...*models.LeasingTask) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a leasingContractHasManyLeasingTasksTx) Clear() error {
	return a.tx.Clear()
}

func (a leasingContractHasManyLeasingTasksTx) Count() int64 {
	return a.tx.Count()
}

func (a leasingContractHasManyLeasingTasksTx) Unscoped() *leasingContractHasManyLeasingTasksTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type leasingContractHasManyPaymentSchedules struct {
	db *gorm.DB

	field.RelationField
}

func (a leasingContractHasManyPaymentSchedules) Where(conds ...field.Expr) *leasingContractHasManyPaymentSchedules {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a leasingContractHasManyPaymentSchedules) WithContext(ctx context.Context) *leasingContractHasManyPaymentSchedules {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a leasingContractHasManyPaymentSchedules) Session(session *gorm.Session) *leasingContractHasManyPaymentSchedules {
	a.db = a.db.Session(session)
	return &a
}

func (a leasingContractHasManyPaymentSchedules) Model(m *models.LeasingContract) *leasingContractHasManyPaymentSchedulesTx {
	return &leasingContractHasManyPaymentSchedulesTx{a.db.Model(m).Association(a.Name())}
}

func (a leasingContractHasManyPaymentSchedules) Unscoped() *leasingContractHasManyPaymentSchedules {
	a.db = a.db.Unscoped()
	return &a
}

type leasingContractHasManyPaymentSchedulesTx struct{ tx *gorm.Association }

func (a leasingContractHasManyPaymentSchedulesTx) Find() (result []*models.PaymentSchedule, err error) {
	return result, a.tx.Find(&result)
}

func (a leasingContractHasManyPaymentSchedulesTx) Append(values ...*models.PaymentSchedule) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a leasingContractHasManyPaymentSchedulesTx) Replace(values ...*models.PaymentSchedule) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a leasingContractHasManyPaymentSchedulesTx) Delete(values ...*models.PaymentSchedule) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a leasingContractHasManyPaymentSchedulesTx) Clear() error {
	return a.tx.Clear()
}

func (a leasingContractHasManyPaymentSchedulesTx) Count() int64 {
	return a.tx.Count()
}

func (a leasingContractHasManyPaymentSchedulesTx) Unscoped() *leasingContractHasManyPaymentSchedulesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type leasingContractHasManyPayments struct {
	db *gorm.DB

	field.RelationField
}

func (a leasingContractHasManyPayments) Where(conds ...field.Expr) *leasingContractHasManyPayments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a leasingContractHasManyPayments) WithContext(ctx context.Context) *leasingContractHasManyPayments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a leasingContractHasManyPayments) Session(session *gorm.Session) *leasingContractHasManyPayments {
	a.db = a.db.Session(session)
	return &a
}

func (a leasingContractHasManyPayments) Model(m *models.LeasingContract) *leasingContractHasManyPaymentsTx {
	return &leasingContractHasManyPaymentsTx{a.db.Model(m).Association(a.Name())}
}

func (a leasingContractHasManyPayments) Unscoped() *leasingContractHasManyPayments {
	a.db = a.db.Unscoped()
	return &a
}

type leasingContractHasManyPaymentsTx struct{ tx *gorm.Association }

func (a leasingContractHasManyPaymentsTx) Find() (result []*models.Payment, err error) {
	return result, a.tx.Find(&result)
}

func (a leasingContractHasManyPaymentsTx) Append(values ...*models.Payment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a leasingContractHasManyPaymentsTx) Replace(values ...*models.Payment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a leasingContractHasManyPaymentsTx) Delete(values ...*models.Payment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a leasingContractHasManyPaymentsTx) Clear() error {
	return a.tx.Clear()
}

func (a leasingContractHasManyPaymentsTx) Count() int64 {
	return a.tx.Count()
}

func (a leasingContractHasManyPaymentsTx) Unscoped() *leasingContractHasManyPaymentsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type leasingContractHasManyContractDocuments struct {
	db *gorm.DB

	field.RelationField
}

func (a leasingContractHasManyContractDocuments) Where(conds ...field.Expr) *leasingContractHasManyContractDocuments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a leasingContractHasManyContractDocuments) WithContext(ctx context.Context) *leasingContractHasManyContractDocuments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a leasingContractHasManyContractDocuments) Session(session *gorm.Session) *leasingContractHasManyContractDocuments {
	a.db = a.db.Session(session)
	return &a
}

func (a leasingContractHasManyContractDocuments) Model(m *models.LeasingContract) *leasingContractHasManyContractDocumentsTx {
	return &leasingContractHasManyContractDocumentsTx{a.db.Model(m).Association(a.Name())}
}

func (a leasingContractHasManyContractDocuments) Unscoped() *leasingContractHasManyContractDocuments {
	a.db = a.db.Unscoped()
	return &a
}

type leasingContractHasManyContractDocumentsTx struct{ tx *gorm.Association }

func (a leasingContractHasManyContractDocumentsTx) Find() (result []*models.LeasingContractDocument, err error) {
	return result, a.tx.Find(&result)
}

func (a leasingContractHasManyContractDocumentsTx) Append(values ...*models.LeasingContractDocument) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a leasingContractHasManyContractDocumentsTx) Replace(values ...*models.LeasingContractDocument) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a leasingContractHasManyContractDocumentsTx) Delete(values ...*models.LeasingContractDocument) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a leasingContractHasManyContractDocumentsTx) Clear() error {
	return a.tx.Clear()
}

func (a leasingContractHasManyContractDocumentsTx) Count() int64 {
	return a.tx.Count()
}

func (a leasingContractHasManyContractDocumentsTx) Unscoped() *leasingContractHasManyContractDocumentsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type leasingContractDo struct{ gen.DO }

type ILeasingContractDo interface {
	gen.SubQuery
	Debug() ILeasingContractDo
	WithContext(ctx context.Context) ILeasingContractDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILeasingContractDo
	WriteDB() ILeasingContractDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILeasingContractDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILeasingContractDo
	Not(conds ...gen.Condition) ILeasingContractDo
	Or(conds ...gen.Condition) ILeasingContractDo
	Select(conds ...field.Expr) ILeasingContractDo
	Where(conds ...gen.Condition) ILeasingContractDo
	Order(conds ...field.Expr) ILeasingContractDo
	Distinct(cols ...field.Expr) ILeasingContractDo
	Omit(cols ...field.Expr) ILeasingContractDo
	Join(table schema.Tabler, on ...field.Expr) ILeasingContractDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDo
	Group(cols ...field.Expr) ILeasingContractDo
	Having(conds ...gen.Condition) ILeasingContractDo
	Limit(limit int) ILeasingContractDo
	Offset(offset int) ILeasingContractDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingContractDo
	Unscoped() ILeasingContractDo
	Create(values ...*models.LeasingContract) error
	CreateInBatches(values []*models.LeasingContract, batchSize int) error
	Save(values ...*models.LeasingContract) error
	First() (*models.LeasingContract, error)
	Take() (*models.LeasingContract, error)
	Last() (*models.LeasingContract, error)
	Find() ([]*models.LeasingContract, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LeasingContract, err error)
	FindInBatches(result *[]*models.LeasingContract, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.LeasingContract) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILeasingContractDo
	Assign(attrs ...field.AssignExpr) ILeasingContractDo
	Joins(fields ...field.RelationField) ILeasingContractDo
	Preload(fields ...field.RelationField) ILeasingContractDo
	FirstOrInit() (*models.LeasingContract, error)
	FirstOrCreate() (*models.LeasingContract, error)
	FindByPage(offset int, limit int) (result []*models.LeasingContract, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILeasingContractDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l leasingContractDo) Debug() ILeasingContractDo {
	return l.withDO(l.DO.Debug())
}

func (l leasingContractDo) WithContext(ctx context.Context) ILeasingContractDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l leasingContractDo) ReadDB() ILeasingContractDo {
	return l.Clauses(dbresolver.Read)
}

func (l leasingContractDo) WriteDB() ILeasingContractDo {
	return l.Clauses(dbresolver.Write)
}

func (l leasingContractDo) Session(config *gorm.Session) ILeasingContractDo {
	return l.withDO(l.DO.Session(config))
}

func (l leasingContractDo) Clauses(conds ...clause.Expression) ILeasingContractDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l leasingContractDo) Returning(value interface{}, columns ...string) ILeasingContractDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l leasingContractDo) Not(conds ...gen.Condition) ILeasingContractDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l leasingContractDo) Or(conds ...gen.Condition) ILeasingContractDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l leasingContractDo) Select(conds ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l leasingContractDo) Where(conds ...gen.Condition) ILeasingContractDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l leasingContractDo) Order(conds ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l leasingContractDo) Distinct(cols ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l leasingContractDo) Omit(cols ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l leasingContractDo) Join(table schema.Tabler, on ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l leasingContractDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l leasingContractDo) RightJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l leasingContractDo) Group(cols ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l leasingContractDo) Having(conds ...gen.Condition) ILeasingContractDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l leasingContractDo) Limit(limit int) ILeasingContractDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l leasingContractDo) Offset(offset int) ILeasingContractDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l leasingContractDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingContractDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l leasingContractDo) Unscoped() ILeasingContractDo {
	return l.withDO(l.DO.Unscoped())
}

func (l leasingContractDo) Create(values ...*models.LeasingContract) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l leasingContractDo) CreateInBatches(values []*models.LeasingContract, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l leasingContractDo) Save(values ...*models.LeasingContract) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l leasingContractDo) First() (*models.LeasingContract, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingContract), nil
	}
}

func (l leasingContractDo) Take() (*models.LeasingContract, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingContract), nil
	}
}

func (l leasingContractDo) Last() (*models.LeasingContract, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingContract), nil
	}
}

func (l leasingContractDo) Find() ([]*models.LeasingContract, error) {
	result, err := l.DO.Find()
	return result.([]*models.LeasingContract), err
}

func (l leasingContractDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LeasingContract, err error) {
	buf := make([]*models.LeasingContract, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l leasingContractDo) FindInBatches(result *[]*models.LeasingContract, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l leasingContractDo) Attrs(attrs ...field.AssignExpr) ILeasingContractDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l leasingContractDo) Assign(attrs ...field.AssignExpr) ILeasingContractDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l leasingContractDo) Joins(fields ...field.RelationField) ILeasingContractDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l leasingContractDo) Preload(fields ...field.RelationField) ILeasingContractDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l leasingContractDo) FirstOrInit() (*models.LeasingContract, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingContract), nil
	}
}

func (l leasingContractDo) FirstOrCreate() (*models.LeasingContract, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingContract), nil
	}
}

func (l leasingContractDo) FindByPage(offset int, limit int) (result []*models.LeasingContract, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l leasingContractDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l leasingContractDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l leasingContractDo) Delete(models ...*models.LeasingContract) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *leasingContractDo) withDO(do gen.Dao) *leasingContractDo {
	l.DO = *do.(*gen.DO)
	return l
}
