// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HendraaaIrwn/honda-leasing-api/internal/domain/models"
)

func newLeasingTaskAttribute(db *gorm.DB, opts ...gen.DOOption) leasingTaskAttribute {
	_leasingTaskAttribute := leasingTaskAttribute{}

	_leasingTaskAttribute.leasingTaskAttributeDo.UseDB(db, opts...)
	_leasingTaskAttribute.leasingTaskAttributeDo.UseModel(&models.LeasingTaskAttribute{})

	tableName := _leasingTaskAttribute.leasingTaskAttributeDo.TableName()
	_leasingTaskAttribute.ALL = field.NewAsterisk(tableName)
	_leasingTaskAttribute.TasaID = field.NewInt64(tableName, "tasa_id")
	_leasingTaskAttribute.TasaName = field.NewString(tableName, "tasa_name")
	_leasingTaskAttribute.TasaValue = field.NewString(tableName, "tasa_value")
	_leasingTaskAttribute.TasaStatus = field.NewString(tableName, "tasa_status")
	_leasingTaskAttribute.TasaLetaID = field.NewInt64(tableName, "tasa_leta_id")
	_leasingTaskAttribute.Task = leasingTaskAttributeBelongsToTask{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Task", "models.LeasingTask"),
		Contract: struct {
			field.RelationField
			Customer struct {
				field.RelationField
				Location struct {
					field.RelationField
					Kelurahan struct {
						field.RelationField
						Kecamatan struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
								Province struct {
									field.RelationField
									Kabupaten struct {
										field.RelationField
									}
								}
								Kecamatan struct {
									field.RelationField
								}
							}
							Kelurahan struct {
								field.RelationField
							}
						}
						Locations struct {
							field.RelationField
						}
					}
				}
				LeasingContracts struct {
					field.RelationField
				}
			}
			Motor struct {
				field.RelationField
				MotorTypeRef struct {
					field.RelationField
					Motors struct {
						field.RelationField
					}
				}
				MotorAssets struct {
					field.RelationField
					Motor struct {
						field.RelationField
					}
				}
			}
			Product struct {
				field.RelationField
				LeasingContracts struct {
					field.RelationField
				}
			}
			LeasingTasks struct {
				field.RelationField
			}
			PaymentSchedules struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Payments struct {
					field.RelationField
					Contract struct {
						field.RelationField
					}
					Schedule struct {
						field.RelationField
					}
				}
			}
			Payments struct {
				field.RelationField
			}
			ContractDocuments struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Task.Contract", "models.LeasingContract"),
			Customer: struct {
				field.RelationField
				Location struct {
					field.RelationField
					Kelurahan struct {
						field.RelationField
						Kecamatan struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
								Province struct {
									field.RelationField
									Kabupaten struct {
										field.RelationField
									}
								}
								Kecamatan struct {
									field.RelationField
								}
							}
							Kelurahan struct {
								field.RelationField
							}
						}
						Locations struct {
							field.RelationField
						}
					}
				}
				LeasingContracts struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Task.Contract.Customer", "models.Customer"),
				Location: struct {
					field.RelationField
					Kelurahan struct {
						field.RelationField
						Kecamatan struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
								Province struct {
									field.RelationField
									Kabupaten struct {
										field.RelationField
									}
								}
								Kecamatan struct {
									field.RelationField
								}
							}
							Kelurahan struct {
								field.RelationField
							}
						}
						Locations struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("Task.Contract.Customer.Location", "models.Location"),
					Kelurahan: struct {
						field.RelationField
						Kecamatan struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
								Province struct {
									field.RelationField
									Kabupaten struct {
										field.RelationField
									}
								}
								Kecamatan struct {
									field.RelationField
								}
							}
							Kelurahan struct {
								field.RelationField
							}
						}
						Locations struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Task.Contract.Customer.Location.Kelurahan", "models.Kelurahan"),
						Kecamatan: struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
								Province struct {
									field.RelationField
									Kabupaten struct {
										field.RelationField
									}
								}
								Kecamatan struct {
									field.RelationField
								}
							}
							Kelurahan struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Task.Contract.Customer.Location.Kelurahan.Kecamatan", "models.Kecamatan"),
							Kabupaten: struct {
								field.RelationField
								Province struct {
									field.RelationField
									Kabupaten struct {
										field.RelationField
									}
								}
								Kecamatan struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Task.Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten", "models.Kabupaten"),
								Province: struct {
									field.RelationField
									Kabupaten struct {
										field.RelationField
									}
								}{
									RelationField: field.NewRelation("Task.Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Province", "models.Province"),
									Kabupaten: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("Task.Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Province.Kabupaten", "models.Kabupaten"),
									},
								},
								Kecamatan: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Task.Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Kecamatan", "models.Kecamatan"),
								},
							},
							Kelurahan: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Task.Contract.Customer.Location.Kelurahan.Kecamatan.Kelurahan", "models.Kelurahan"),
							},
						},
						Locations: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Task.Contract.Customer.Location.Kelurahan.Locations", "models.Location"),
						},
					},
				},
				LeasingContracts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Task.Contract.Customer.LeasingContracts", "models.LeasingContract"),
				},
			},
			Motor: struct {
				field.RelationField
				MotorTypeRef struct {
					field.RelationField
					Motors struct {
						field.RelationField
					}
				}
				MotorAssets struct {
					field.RelationField
					Motor struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Task.Contract.Motor", "models.Motor"),
				MotorTypeRef: struct {
					field.RelationField
					Motors struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Task.Contract.Motor.MotorTypeRef", "models.MotorType"),
					Motors: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Task.Contract.Motor.MotorTypeRef.Motors", "models.Motor"),
					},
				},
				MotorAssets: struct {
					field.RelationField
					Motor struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Task.Contract.Motor.MotorAssets", "models.MotorAsset"),
					Motor: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Task.Contract.Motor.MotorAssets.Motor", "models.Motor"),
					},
				},
			},
			Product: struct {
				field.RelationField
				LeasingContracts struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Task.Contract.Product", "models.LeasingProduct"),
				LeasingContracts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Task.Contract.Product.LeasingContracts", "models.LeasingContract"),
				},
			},
			LeasingTasks: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Task.Contract.LeasingTasks", "models.LeasingTask"),
			},
			PaymentSchedules: struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Payments struct {
					field.RelationField
					Contract struct {
						field.RelationField
					}
					Schedule struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Task.Contract.PaymentSchedules", "models.PaymentSchedule"),
				Contract: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Task.Contract.PaymentSchedules.Contract", "models.LeasingContract"),
				},
				Payments: struct {
					field.RelationField
					Contract struct {
						field.RelationField
					}
					Schedule struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Task.Contract.PaymentSchedules.Payments", "models.Payment"),
					Contract: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Task.Contract.PaymentSchedules.Payments.Contract", "models.LeasingContract"),
					},
					Schedule: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Task.Contract.PaymentSchedules.Payments.Schedule", "models.PaymentSchedule"),
					},
				},
			},
			Payments: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Task.Contract.Payments", "models.Payment"),
			},
			ContractDocuments: struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Task.Contract.ContractDocuments", "models.LeasingContractDocument"),
				Contract: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Task.Contract.ContractDocuments.Contract", "models.LeasingContract"),
				},
			},
		},
		Role: struct {
			field.RelationField
			UserRoles struct {
				field.RelationField
				User struct {
					field.RelationField
					UserOAuthProviders struct {
						field.RelationField
						User struct {
							field.RelationField
						}
						Provider struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}
					}
					UserRoles struct {
						field.RelationField
					}
				}
				Role struct {
					field.RelationField
				}
			}
			RolePermissions struct {
				field.RelationField
				Role struct {
					field.RelationField
				}
				Permission struct {
					field.RelationField
					RolePermissions struct {
						field.RelationField
					}
				}
			}
		}{
			RelationField: field.NewRelation("Task.Role", "models.Role"),
			UserRoles: struct {
				field.RelationField
				User struct {
					field.RelationField
					UserOAuthProviders struct {
						field.RelationField
						User struct {
							field.RelationField
						}
						Provider struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}
					}
					UserRoles struct {
						field.RelationField
					}
				}
				Role struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Task.Role.UserRoles", "models.UserRole"),
				User: struct {
					field.RelationField
					UserOAuthProviders struct {
						field.RelationField
						User struct {
							field.RelationField
						}
						Provider struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}
					}
					UserRoles struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Task.Role.UserRoles.User", "models.User"),
					UserOAuthProviders: struct {
						field.RelationField
						User struct {
							field.RelationField
						}
						Provider struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}
					}{
						RelationField: field.NewRelation("Task.Role.UserRoles.User.UserOAuthProviders", "models.UserOAuthProvider"),
						User: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Task.Role.UserRoles.User.UserOAuthProviders.User", "models.User"),
						},
						Provider: struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Task.Role.UserRoles.User.UserOAuthProviders.Provider", "models.OAuthProvider"),
							UserOAuthProviders: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Task.Role.UserRoles.User.UserOAuthProviders.Provider.UserOAuthProviders", "models.UserOAuthProvider"),
							},
						},
					},
					UserRoles: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Task.Role.UserRoles.User.UserRoles", "models.UserRole"),
					},
				},
				Role: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Task.Role.UserRoles.Role", "models.Role"),
				},
			},
			RolePermissions: struct {
				field.RelationField
				Role struct {
					field.RelationField
				}
				Permission struct {
					field.RelationField
					RolePermissions struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Task.Role.RolePermissions", "models.RolePermission"),
				Role: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Task.Role.RolePermissions.Role", "models.Role"),
				},
				Permission: struct {
					field.RelationField
					RolePermissions struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Task.Role.RolePermissions.Permission", "models.Permission"),
					RolePermissions: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Task.Role.RolePermissions.Permission.RolePermissions", "models.RolePermission"),
					},
				},
			},
		},
		LeasingAttribute: struct {
			field.RelationField
			Task struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Task.LeasingAttribute", "models.LeasingTaskAttribute"),
			Task: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Task.LeasingAttribute.Task", "models.LeasingTask"),
			},
		},
	}

	_leasingTaskAttribute.fillFieldMap()

	return _leasingTaskAttribute
}

type leasingTaskAttribute struct {
	leasingTaskAttributeDo

	ALL        field.Asterisk
	TasaID     field.Int64
	TasaName   field.String
	TasaValue  field.String
	TasaStatus field.String
	TasaLetaID field.Int64
	Task       leasingTaskAttributeBelongsToTask

	fieldMap map[string]field.Expr
}

func (l leasingTaskAttribute) Table(newTableName string) *leasingTaskAttribute {
	l.leasingTaskAttributeDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l leasingTaskAttribute) As(alias string) *leasingTaskAttribute {
	l.leasingTaskAttributeDo.DO = *(l.leasingTaskAttributeDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *leasingTaskAttribute) updateTableName(table string) *leasingTaskAttribute {
	l.ALL = field.NewAsterisk(table)
	l.TasaID = field.NewInt64(table, "tasa_id")
	l.TasaName = field.NewString(table, "tasa_name")
	l.TasaValue = field.NewString(table, "tasa_value")
	l.TasaStatus = field.NewString(table, "tasa_status")
	l.TasaLetaID = field.NewInt64(table, "tasa_leta_id")

	l.fillFieldMap()

	return l
}

func (l *leasingTaskAttribute) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *leasingTaskAttribute) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 6)
	l.fieldMap["tasa_id"] = l.TasaID
	l.fieldMap["tasa_name"] = l.TasaName
	l.fieldMap["tasa_value"] = l.TasaValue
	l.fieldMap["tasa_status"] = l.TasaStatus
	l.fieldMap["tasa_leta_id"] = l.TasaLetaID

}

func (l leasingTaskAttribute) clone(db *gorm.DB) leasingTaskAttribute {
	l.leasingTaskAttributeDo.ReplaceConnPool(db.Statement.ConnPool)
	l.Task.db = db.Session(&gorm.Session{Initialized: true})
	l.Task.db.Statement.ConnPool = db.Statement.ConnPool
	return l
}

func (l leasingTaskAttribute) replaceDB(db *gorm.DB) leasingTaskAttribute {
	l.leasingTaskAttributeDo.ReplaceDB(db)
	l.Task.db = db.Session(&gorm.Session{})
	return l
}

type leasingTaskAttributeBelongsToTask struct {
	db *gorm.DB

	field.RelationField

	Contract struct {
		field.RelationField
		Customer struct {
			field.RelationField
			Location struct {
				field.RelationField
				Kelurahan struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}
			}
			LeasingContracts struct {
				field.RelationField
			}
		}
		Motor struct {
			field.RelationField
			MotorTypeRef struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}
			MotorAssets struct {
				field.RelationField
				Motor struct {
					field.RelationField
				}
			}
		}
		Product struct {
			field.RelationField
			LeasingContracts struct {
				field.RelationField
			}
		}
		LeasingTasks struct {
			field.RelationField
		}
		PaymentSchedules struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Payments struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Schedule struct {
					field.RelationField
				}
			}
		}
		Payments struct {
			field.RelationField
		}
		ContractDocuments struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
		}
	}
	Role struct {
		field.RelationField
		UserRoles struct {
			field.RelationField
			User struct {
				field.RelationField
				UserOAuthProviders struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					Provider struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
						}
					}
				}
				UserRoles struct {
					field.RelationField
				}
			}
			Role struct {
				field.RelationField
			}
		}
		RolePermissions struct {
			field.RelationField
			Role struct {
				field.RelationField
			}
			Permission struct {
				field.RelationField
				RolePermissions struct {
					field.RelationField
				}
			}
		}
	}
	LeasingAttribute struct {
		field.RelationField
		Task struct {
			field.RelationField
		}
	}
}

func (a leasingTaskAttributeBelongsToTask) Where(conds ...field.Expr) *leasingTaskAttributeBelongsToTask {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a leasingTaskAttributeBelongsToTask) WithContext(ctx context.Context) *leasingTaskAttributeBelongsToTask {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a leasingTaskAttributeBelongsToTask) Session(session *gorm.Session) *leasingTaskAttributeBelongsToTask {
	a.db = a.db.Session(session)
	return &a
}

func (a leasingTaskAttributeBelongsToTask) Model(m *models.LeasingTaskAttribute) *leasingTaskAttributeBelongsToTaskTx {
	return &leasingTaskAttributeBelongsToTaskTx{a.db.Model(m).Association(a.Name())}
}

func (a leasingTaskAttributeBelongsToTask) Unscoped() *leasingTaskAttributeBelongsToTask {
	a.db = a.db.Unscoped()
	return &a
}

type leasingTaskAttributeBelongsToTaskTx struct{ tx *gorm.Association }

func (a leasingTaskAttributeBelongsToTaskTx) Find() (result *models.LeasingTask, err error) {
	return result, a.tx.Find(&result)
}

func (a leasingTaskAttributeBelongsToTaskTx) Append(values ...*models.LeasingTask) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a leasingTaskAttributeBelongsToTaskTx) Replace(values ...*models.LeasingTask) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a leasingTaskAttributeBelongsToTaskTx) Delete(values ...*models.LeasingTask) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a leasingTaskAttributeBelongsToTaskTx) Clear() error {
	return a.tx.Clear()
}

func (a leasingTaskAttributeBelongsToTaskTx) Count() int64 {
	return a.tx.Count()
}

func (a leasingTaskAttributeBelongsToTaskTx) Unscoped() *leasingTaskAttributeBelongsToTaskTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type leasingTaskAttributeDo struct{ gen.DO }

type ILeasingTaskAttributeDo interface {
	gen.SubQuery
	Debug() ILeasingTaskAttributeDo
	WithContext(ctx context.Context) ILeasingTaskAttributeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILeasingTaskAttributeDo
	WriteDB() ILeasingTaskAttributeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILeasingTaskAttributeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILeasingTaskAttributeDo
	Not(conds ...gen.Condition) ILeasingTaskAttributeDo
	Or(conds ...gen.Condition) ILeasingTaskAttributeDo
	Select(conds ...field.Expr) ILeasingTaskAttributeDo
	Where(conds ...gen.Condition) ILeasingTaskAttributeDo
	Order(conds ...field.Expr) ILeasingTaskAttributeDo
	Distinct(cols ...field.Expr) ILeasingTaskAttributeDo
	Omit(cols ...field.Expr) ILeasingTaskAttributeDo
	Join(table schema.Tabler, on ...field.Expr) ILeasingTaskAttributeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskAttributeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskAttributeDo
	Group(cols ...field.Expr) ILeasingTaskAttributeDo
	Having(conds ...gen.Condition) ILeasingTaskAttributeDo
	Limit(limit int) ILeasingTaskAttributeDo
	Offset(offset int) ILeasingTaskAttributeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingTaskAttributeDo
	Unscoped() ILeasingTaskAttributeDo
	Create(values ...*models.LeasingTaskAttribute) error
	CreateInBatches(values []*models.LeasingTaskAttribute, batchSize int) error
	Save(values ...*models.LeasingTaskAttribute) error
	First() (*models.LeasingTaskAttribute, error)
	Take() (*models.LeasingTaskAttribute, error)
	Last() (*models.LeasingTaskAttribute, error)
	Find() ([]*models.LeasingTaskAttribute, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LeasingTaskAttribute, err error)
	FindInBatches(result *[]*models.LeasingTaskAttribute, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.LeasingTaskAttribute) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILeasingTaskAttributeDo
	Assign(attrs ...field.AssignExpr) ILeasingTaskAttributeDo
	Joins(fields ...field.RelationField) ILeasingTaskAttributeDo
	Preload(fields ...field.RelationField) ILeasingTaskAttributeDo
	FirstOrInit() (*models.LeasingTaskAttribute, error)
	FirstOrCreate() (*models.LeasingTaskAttribute, error)
	FindByPage(offset int, limit int) (result []*models.LeasingTaskAttribute, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILeasingTaskAttributeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l leasingTaskAttributeDo) Debug() ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Debug())
}

func (l leasingTaskAttributeDo) WithContext(ctx context.Context) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l leasingTaskAttributeDo) ReadDB() ILeasingTaskAttributeDo {
	return l.Clauses(dbresolver.Read)
}

func (l leasingTaskAttributeDo) WriteDB() ILeasingTaskAttributeDo {
	return l.Clauses(dbresolver.Write)
}

func (l leasingTaskAttributeDo) Session(config *gorm.Session) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Session(config))
}

func (l leasingTaskAttributeDo) Clauses(conds ...clause.Expression) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l leasingTaskAttributeDo) Returning(value interface{}, columns ...string) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l leasingTaskAttributeDo) Not(conds ...gen.Condition) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l leasingTaskAttributeDo) Or(conds ...gen.Condition) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l leasingTaskAttributeDo) Select(conds ...field.Expr) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l leasingTaskAttributeDo) Where(conds ...gen.Condition) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l leasingTaskAttributeDo) Order(conds ...field.Expr) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l leasingTaskAttributeDo) Distinct(cols ...field.Expr) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l leasingTaskAttributeDo) Omit(cols ...field.Expr) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l leasingTaskAttributeDo) Join(table schema.Tabler, on ...field.Expr) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l leasingTaskAttributeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l leasingTaskAttributeDo) RightJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l leasingTaskAttributeDo) Group(cols ...field.Expr) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l leasingTaskAttributeDo) Having(conds ...gen.Condition) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l leasingTaskAttributeDo) Limit(limit int) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l leasingTaskAttributeDo) Offset(offset int) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l leasingTaskAttributeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l leasingTaskAttributeDo) Unscoped() ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Unscoped())
}

func (l leasingTaskAttributeDo) Create(values ...*models.LeasingTaskAttribute) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l leasingTaskAttributeDo) CreateInBatches(values []*models.LeasingTaskAttribute, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l leasingTaskAttributeDo) Save(values ...*models.LeasingTaskAttribute) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l leasingTaskAttributeDo) First() (*models.LeasingTaskAttribute, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTaskAttribute), nil
	}
}

func (l leasingTaskAttributeDo) Take() (*models.LeasingTaskAttribute, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTaskAttribute), nil
	}
}

func (l leasingTaskAttributeDo) Last() (*models.LeasingTaskAttribute, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTaskAttribute), nil
	}
}

func (l leasingTaskAttributeDo) Find() ([]*models.LeasingTaskAttribute, error) {
	result, err := l.DO.Find()
	return result.([]*models.LeasingTaskAttribute), err
}

func (l leasingTaskAttributeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LeasingTaskAttribute, err error) {
	buf := make([]*models.LeasingTaskAttribute, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l leasingTaskAttributeDo) FindInBatches(result *[]*models.LeasingTaskAttribute, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l leasingTaskAttributeDo) Attrs(attrs ...field.AssignExpr) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l leasingTaskAttributeDo) Assign(attrs ...field.AssignExpr) ILeasingTaskAttributeDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l leasingTaskAttributeDo) Joins(fields ...field.RelationField) ILeasingTaskAttributeDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l leasingTaskAttributeDo) Preload(fields ...field.RelationField) ILeasingTaskAttributeDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l leasingTaskAttributeDo) FirstOrInit() (*models.LeasingTaskAttribute, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTaskAttribute), nil
	}
}

func (l leasingTaskAttributeDo) FirstOrCreate() (*models.LeasingTaskAttribute, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTaskAttribute), nil
	}
}

func (l leasingTaskAttributeDo) FindByPage(offset int, limit int) (result []*models.LeasingTaskAttribute, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l leasingTaskAttributeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l leasingTaskAttributeDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l leasingTaskAttributeDo) Delete(models ...*models.LeasingTaskAttribute) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *leasingTaskAttributeDo) withDO(do gen.Dao) *leasingTaskAttributeDo {
	l.DO = *do.(*gen.DO)
	return l
}
