// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HendraaaIrwn/honda-leasing-api/internal/domain/models"
)

func newLeasingTask(db *gorm.DB, opts ...gen.DOOption) leasingTask {
	_leasingTask := leasingTask{}

	_leasingTask.leasingTaskDo.UseDB(db, opts...)
	_leasingTask.leasingTaskDo.UseModel(&models.LeasingTask{})

	tableName := _leasingTask.leasingTaskDo.TableName()
	_leasingTask.ALL = field.NewAsterisk(tableName)
	_leasingTask.TaskID = field.NewInt64(tableName, "task_id")
	_leasingTask.TaskName = field.NewString(tableName, "task_name")
	_leasingTask.StartDate = field.NewTime(tableName, "startdate")
	_leasingTask.EndDate = field.NewTime(tableName, "enddate")
	_leasingTask.ActualStartDate = field.NewTime(tableName, "actual_startdate")
	_leasingTask.ActualEndDate = field.NewTime(tableName, "actual_enddate")
	_leasingTask.SequenceNo = field.NewInt(tableName, "sequence_no")
	_leasingTask.Status = field.NewString(tableName, "status")
	_leasingTask.ContractID = field.NewInt64(tableName, "contract_id")
	_leasingTask.RoleID = field.NewInt64(tableName, "role_id")
	_leasingTask.Contract = leasingTaskHasOneContract{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Contract", "models.LeasingContract"),
		Customer: struct {
			field.RelationField
			Location struct {
				field.RelationField
				Kelurahan struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}
			}
			LeasingContracts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Contract.Customer", "models.Customer"),
			Location: struct {
				field.RelationField
				Kelurahan struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Contract.Customer.Location", "models.Location"),
				Kelurahan: struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan", "models.Kelurahan"),
					Kecamatan: struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan", "models.Kecamatan"),
						Kabupaten: struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten", "models.Kabupaten"),
							Province: struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Province", "models.Province"),
								Kabupaten: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Province.Kabupaten", "models.Kabupaten"),
								},
							},
							Kecamatan: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Kecamatan", "models.Kecamatan"),
							},
						},
						Kelurahan: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kelurahan", "models.Kelurahan"),
						},
					},
					Locations: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Locations", "models.Location"),
					},
				},
			},
			LeasingContracts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.Customer.LeasingContracts", "models.LeasingContract"),
			},
		},
		Motor: struct {
			field.RelationField
			MotorTypeRef struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}
			MotorAssets struct {
				field.RelationField
				Motor struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Contract.Motor", "models.Motor"),
			MotorTypeRef: struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.Motor.MotorTypeRef", "models.MotorType"),
				Motors: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.Motor.MotorTypeRef.Motors", "models.Motor"),
				},
			},
			MotorAssets: struct {
				field.RelationField
				Motor struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.Motor.MotorAssets", "models.MotorAsset"),
				Motor: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.Motor.MotorAssets.Motor", "models.Motor"),
				},
			},
		},
		Product: struct {
			field.RelationField
			LeasingContracts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Contract.Product", "models.LeasingProduct"),
			LeasingContracts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.Product.LeasingContracts", "models.LeasingContract"),
			},
		},
		LeasingTasks: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Role struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}
			LeasingAttribute struct {
				field.RelationField
				Task struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Contract.LeasingTasks", "models.LeasingTask"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.LeasingTasks.Contract", "models.LeasingContract"),
			},
			Role: struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("Contract.LeasingTasks.Role", "models.Role"),
				UserRoles: struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles", "models.UserRole"),
					User: struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User", "models.User"),
						UserOAuthProviders: struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}{
							RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders", "models.UserOAuthProvider"),
							User: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.User", "models.User"),
							},
							Provider: struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.Provider", "models.OAuthProvider"),
								UserOAuthProviders: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.Provider.UserOAuthProviders", "models.UserOAuthProvider"),
								},
							},
						},
						UserRoles: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserRoles", "models.UserRole"),
						},
					},
					Role: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.Role", "models.Role"),
					},
				},
				RolePermissions: struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions", "models.RolePermission"),
					Role: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions.Role", "models.Role"),
					},
					Permission: struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions.Permission", "models.Permission"),
						RolePermissions: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions.Permission.RolePermissions", "models.RolePermission"),
						},
					},
				},
			},
			LeasingAttribute: struct {
				field.RelationField
				Task struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.LeasingTasks.LeasingAttribute", "models.LeasingTaskAttribute"),
				Task: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.LeasingTasks.LeasingAttribute.Task", "models.LeasingTask"),
				},
			},
		},
		PaymentSchedules: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Payments struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Schedule struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Contract.PaymentSchedules", "models.PaymentSchedule"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.PaymentSchedules.Contract", "models.LeasingContract"),
			},
			Payments: struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Schedule struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.PaymentSchedules.Payments", "models.Payment"),
				Contract: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.PaymentSchedules.Payments.Contract", "models.LeasingContract"),
				},
				Schedule: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.PaymentSchedules.Payments.Schedule", "models.PaymentSchedule"),
				},
			},
		},
		Payments: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Contract.Payments", "models.Payment"),
		},
		ContractDocuments: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Contract.ContractDocuments", "models.LeasingContractDocument"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.ContractDocuments.Contract", "models.LeasingContract"),
			},
		},
	}

	_leasingTask.Role = leasingTaskHasOneRole{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Role", "models.Role"),
	}

	_leasingTask.LeasingAttribute = leasingTaskHasManyLeasingAttribute{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("LeasingAttribute", "models.LeasingTaskAttribute"),
	}

	_leasingTask.fillFieldMap()

	return _leasingTask
}

type leasingTask struct {
	leasingTaskDo

	ALL             field.Asterisk
	TaskID          field.Int64
	TaskName        field.String
	StartDate       field.Time
	EndDate         field.Time
	ActualStartDate field.Time
	ActualEndDate   field.Time
	SequenceNo      field.Int
	Status          field.String
	ContractID      field.Int64
	RoleID          field.Int64
	Contract        leasingTaskHasOneContract

	Role leasingTaskHasOneRole

	LeasingAttribute leasingTaskHasManyLeasingAttribute

	fieldMap map[string]field.Expr
}

func (l leasingTask) Table(newTableName string) *leasingTask {
	l.leasingTaskDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l leasingTask) As(alias string) *leasingTask {
	l.leasingTaskDo.DO = *(l.leasingTaskDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *leasingTask) updateTableName(table string) *leasingTask {
	l.ALL = field.NewAsterisk(table)
	l.TaskID = field.NewInt64(table, "task_id")
	l.TaskName = field.NewString(table, "task_name")
	l.StartDate = field.NewTime(table, "startdate")
	l.EndDate = field.NewTime(table, "enddate")
	l.ActualStartDate = field.NewTime(table, "actual_startdate")
	l.ActualEndDate = field.NewTime(table, "actual_enddate")
	l.SequenceNo = field.NewInt(table, "sequence_no")
	l.Status = field.NewString(table, "status")
	l.ContractID = field.NewInt64(table, "contract_id")
	l.RoleID = field.NewInt64(table, "role_id")

	l.fillFieldMap()

	return l
}

func (l *leasingTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *leasingTask) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 13)
	l.fieldMap["task_id"] = l.TaskID
	l.fieldMap["task_name"] = l.TaskName
	l.fieldMap["startdate"] = l.StartDate
	l.fieldMap["enddate"] = l.EndDate
	l.fieldMap["actual_startdate"] = l.ActualStartDate
	l.fieldMap["actual_enddate"] = l.ActualEndDate
	l.fieldMap["sequence_no"] = l.SequenceNo
	l.fieldMap["status"] = l.Status
	l.fieldMap["contract_id"] = l.ContractID
	l.fieldMap["role_id"] = l.RoleID

}

func (l leasingTask) clone(db *gorm.DB) leasingTask {
	l.leasingTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	l.Contract.db = db.Session(&gorm.Session{Initialized: true})
	l.Contract.db.Statement.ConnPool = db.Statement.ConnPool
	l.Role.db = db.Session(&gorm.Session{Initialized: true})
	l.Role.db.Statement.ConnPool = db.Statement.ConnPool
	l.LeasingAttribute.db = db.Session(&gorm.Session{Initialized: true})
	l.LeasingAttribute.db.Statement.ConnPool = db.Statement.ConnPool
	return l
}

func (l leasingTask) replaceDB(db *gorm.DB) leasingTask {
	l.leasingTaskDo.ReplaceDB(db)
	l.Contract.db = db.Session(&gorm.Session{})
	l.Role.db = db.Session(&gorm.Session{})
	l.LeasingAttribute.db = db.Session(&gorm.Session{})
	return l
}

type leasingTaskHasOneContract struct {
	db *gorm.DB

	field.RelationField

	Customer struct {
		field.RelationField
		Location struct {
			field.RelationField
			Kelurahan struct {
				field.RelationField
				Kecamatan struct {
					field.RelationField
					Kabupaten struct {
						field.RelationField
						Province struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
							}
						}
						Kecamatan struct {
							field.RelationField
						}
					}
					Kelurahan struct {
						field.RelationField
					}
				}
				Locations struct {
					field.RelationField
				}
			}
		}
		LeasingContracts struct {
			field.RelationField
		}
	}
	Motor struct {
		field.RelationField
		MotorTypeRef struct {
			field.RelationField
			Motors struct {
				field.RelationField
			}
		}
		MotorAssets struct {
			field.RelationField
			Motor struct {
				field.RelationField
			}
		}
	}
	Product struct {
		field.RelationField
		LeasingContracts struct {
			field.RelationField
		}
	}
	LeasingTasks struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
		Role struct {
			field.RelationField
			UserRoles struct {
				field.RelationField
				User struct {
					field.RelationField
					UserOAuthProviders struct {
						field.RelationField
						User struct {
							field.RelationField
						}
						Provider struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}
					}
					UserRoles struct {
						field.RelationField
					}
				}
				Role struct {
					field.RelationField
				}
			}
			RolePermissions struct {
				field.RelationField
				Role struct {
					field.RelationField
				}
				Permission struct {
					field.RelationField
					RolePermissions struct {
						field.RelationField
					}
				}
			}
		}
		LeasingAttribute struct {
			field.RelationField
			Task struct {
				field.RelationField
			}
		}
	}
	PaymentSchedules struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
		Payments struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Schedule struct {
				field.RelationField
			}
		}
	}
	Payments struct {
		field.RelationField
	}
	ContractDocuments struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
	}
}

func (a leasingTaskHasOneContract) Where(conds ...field.Expr) *leasingTaskHasOneContract {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a leasingTaskHasOneContract) WithContext(ctx context.Context) *leasingTaskHasOneContract {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a leasingTaskHasOneContract) Session(session *gorm.Session) *leasingTaskHasOneContract {
	a.db = a.db.Session(session)
	return &a
}

func (a leasingTaskHasOneContract) Model(m *models.LeasingTask) *leasingTaskHasOneContractTx {
	return &leasingTaskHasOneContractTx{a.db.Model(m).Association(a.Name())}
}

func (a leasingTaskHasOneContract) Unscoped() *leasingTaskHasOneContract {
	a.db = a.db.Unscoped()
	return &a
}

type leasingTaskHasOneContractTx struct{ tx *gorm.Association }

func (a leasingTaskHasOneContractTx) Find() (result *models.LeasingContract, err error) {
	return result, a.tx.Find(&result)
}

func (a leasingTaskHasOneContractTx) Append(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a leasingTaskHasOneContractTx) Replace(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a leasingTaskHasOneContractTx) Delete(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a leasingTaskHasOneContractTx) Clear() error {
	return a.tx.Clear()
}

func (a leasingTaskHasOneContractTx) Count() int64 {
	return a.tx.Count()
}

func (a leasingTaskHasOneContractTx) Unscoped() *leasingTaskHasOneContractTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type leasingTaskHasOneRole struct {
	db *gorm.DB

	field.RelationField
}

func (a leasingTaskHasOneRole) Where(conds ...field.Expr) *leasingTaskHasOneRole {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a leasingTaskHasOneRole) WithContext(ctx context.Context) *leasingTaskHasOneRole {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a leasingTaskHasOneRole) Session(session *gorm.Session) *leasingTaskHasOneRole {
	a.db = a.db.Session(session)
	return &a
}

func (a leasingTaskHasOneRole) Model(m *models.LeasingTask) *leasingTaskHasOneRoleTx {
	return &leasingTaskHasOneRoleTx{a.db.Model(m).Association(a.Name())}
}

func (a leasingTaskHasOneRole) Unscoped() *leasingTaskHasOneRole {
	a.db = a.db.Unscoped()
	return &a
}

type leasingTaskHasOneRoleTx struct{ tx *gorm.Association }

func (a leasingTaskHasOneRoleTx) Find() (result *models.Role, err error) {
	return result, a.tx.Find(&result)
}

func (a leasingTaskHasOneRoleTx) Append(values ...*models.Role) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a leasingTaskHasOneRoleTx) Replace(values ...*models.Role) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a leasingTaskHasOneRoleTx) Delete(values ...*models.Role) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a leasingTaskHasOneRoleTx) Clear() error {
	return a.tx.Clear()
}

func (a leasingTaskHasOneRoleTx) Count() int64 {
	return a.tx.Count()
}

func (a leasingTaskHasOneRoleTx) Unscoped() *leasingTaskHasOneRoleTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type leasingTaskHasManyLeasingAttribute struct {
	db *gorm.DB

	field.RelationField
}

func (a leasingTaskHasManyLeasingAttribute) Where(conds ...field.Expr) *leasingTaskHasManyLeasingAttribute {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a leasingTaskHasManyLeasingAttribute) WithContext(ctx context.Context) *leasingTaskHasManyLeasingAttribute {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a leasingTaskHasManyLeasingAttribute) Session(session *gorm.Session) *leasingTaskHasManyLeasingAttribute {
	a.db = a.db.Session(session)
	return &a
}

func (a leasingTaskHasManyLeasingAttribute) Model(m *models.LeasingTask) *leasingTaskHasManyLeasingAttributeTx {
	return &leasingTaskHasManyLeasingAttributeTx{a.db.Model(m).Association(a.Name())}
}

func (a leasingTaskHasManyLeasingAttribute) Unscoped() *leasingTaskHasManyLeasingAttribute {
	a.db = a.db.Unscoped()
	return &a
}

type leasingTaskHasManyLeasingAttributeTx struct{ tx *gorm.Association }

func (a leasingTaskHasManyLeasingAttributeTx) Find() (result []*models.LeasingTaskAttribute, err error) {
	return result, a.tx.Find(&result)
}

func (a leasingTaskHasManyLeasingAttributeTx) Append(values ...*models.LeasingTaskAttribute) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a leasingTaskHasManyLeasingAttributeTx) Replace(values ...*models.LeasingTaskAttribute) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a leasingTaskHasManyLeasingAttributeTx) Delete(values ...*models.LeasingTaskAttribute) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a leasingTaskHasManyLeasingAttributeTx) Clear() error {
	return a.tx.Clear()
}

func (a leasingTaskHasManyLeasingAttributeTx) Count() int64 {
	return a.tx.Count()
}

func (a leasingTaskHasManyLeasingAttributeTx) Unscoped() *leasingTaskHasManyLeasingAttributeTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type leasingTaskDo struct{ gen.DO }

type ILeasingTaskDo interface {
	gen.SubQuery
	Debug() ILeasingTaskDo
	WithContext(ctx context.Context) ILeasingTaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILeasingTaskDo
	WriteDB() ILeasingTaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILeasingTaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILeasingTaskDo
	Not(conds ...gen.Condition) ILeasingTaskDo
	Or(conds ...gen.Condition) ILeasingTaskDo
	Select(conds ...field.Expr) ILeasingTaskDo
	Where(conds ...gen.Condition) ILeasingTaskDo
	Order(conds ...field.Expr) ILeasingTaskDo
	Distinct(cols ...field.Expr) ILeasingTaskDo
	Omit(cols ...field.Expr) ILeasingTaskDo
	Join(table schema.Tabler, on ...field.Expr) ILeasingTaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskDo
	Group(cols ...field.Expr) ILeasingTaskDo
	Having(conds ...gen.Condition) ILeasingTaskDo
	Limit(limit int) ILeasingTaskDo
	Offset(offset int) ILeasingTaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingTaskDo
	Unscoped() ILeasingTaskDo
	Create(values ...*models.LeasingTask) error
	CreateInBatches(values []*models.LeasingTask, batchSize int) error
	Save(values ...*models.LeasingTask) error
	First() (*models.LeasingTask, error)
	Take() (*models.LeasingTask, error)
	Last() (*models.LeasingTask, error)
	Find() ([]*models.LeasingTask, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LeasingTask, err error)
	FindInBatches(result *[]*models.LeasingTask, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.LeasingTask) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILeasingTaskDo
	Assign(attrs ...field.AssignExpr) ILeasingTaskDo
	Joins(fields ...field.RelationField) ILeasingTaskDo
	Preload(fields ...field.RelationField) ILeasingTaskDo
	FirstOrInit() (*models.LeasingTask, error)
	FirstOrCreate() (*models.LeasingTask, error)
	FindByPage(offset int, limit int) (result []*models.LeasingTask, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILeasingTaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l leasingTaskDo) Debug() ILeasingTaskDo {
	return l.withDO(l.DO.Debug())
}

func (l leasingTaskDo) WithContext(ctx context.Context) ILeasingTaskDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l leasingTaskDo) ReadDB() ILeasingTaskDo {
	return l.Clauses(dbresolver.Read)
}

func (l leasingTaskDo) WriteDB() ILeasingTaskDo {
	return l.Clauses(dbresolver.Write)
}

func (l leasingTaskDo) Session(config *gorm.Session) ILeasingTaskDo {
	return l.withDO(l.DO.Session(config))
}

func (l leasingTaskDo) Clauses(conds ...clause.Expression) ILeasingTaskDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l leasingTaskDo) Returning(value interface{}, columns ...string) ILeasingTaskDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l leasingTaskDo) Not(conds ...gen.Condition) ILeasingTaskDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l leasingTaskDo) Or(conds ...gen.Condition) ILeasingTaskDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l leasingTaskDo) Select(conds ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l leasingTaskDo) Where(conds ...gen.Condition) ILeasingTaskDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l leasingTaskDo) Order(conds ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l leasingTaskDo) Distinct(cols ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l leasingTaskDo) Omit(cols ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l leasingTaskDo) Join(table schema.Tabler, on ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l leasingTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l leasingTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l leasingTaskDo) Group(cols ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l leasingTaskDo) Having(conds ...gen.Condition) ILeasingTaskDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l leasingTaskDo) Limit(limit int) ILeasingTaskDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l leasingTaskDo) Offset(offset int) ILeasingTaskDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l leasingTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingTaskDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l leasingTaskDo) Unscoped() ILeasingTaskDo {
	return l.withDO(l.DO.Unscoped())
}

func (l leasingTaskDo) Create(values ...*models.LeasingTask) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l leasingTaskDo) CreateInBatches(values []*models.LeasingTask, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l leasingTaskDo) Save(values ...*models.LeasingTask) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l leasingTaskDo) First() (*models.LeasingTask, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTask), nil
	}
}

func (l leasingTaskDo) Take() (*models.LeasingTask, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTask), nil
	}
}

func (l leasingTaskDo) Last() (*models.LeasingTask, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTask), nil
	}
}

func (l leasingTaskDo) Find() ([]*models.LeasingTask, error) {
	result, err := l.DO.Find()
	return result.([]*models.LeasingTask), err
}

func (l leasingTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LeasingTask, err error) {
	buf := make([]*models.LeasingTask, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l leasingTaskDo) FindInBatches(result *[]*models.LeasingTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l leasingTaskDo) Attrs(attrs ...field.AssignExpr) ILeasingTaskDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l leasingTaskDo) Assign(attrs ...field.AssignExpr) ILeasingTaskDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l leasingTaskDo) Joins(fields ...field.RelationField) ILeasingTaskDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l leasingTaskDo) Preload(fields ...field.RelationField) ILeasingTaskDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l leasingTaskDo) FirstOrInit() (*models.LeasingTask, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTask), nil
	}
}

func (l leasingTaskDo) FirstOrCreate() (*models.LeasingTask, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTask), nil
	}
}

func (l leasingTaskDo) FindByPage(offset int, limit int) (result []*models.LeasingTask, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l leasingTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l leasingTaskDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l leasingTaskDo) Delete(models ...*models.LeasingTask) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *leasingTaskDo) withDO(do gen.Dao) *leasingTaskDo {
	l.DO = *do.(*gen.DO)
	return l
}
