// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HendraaaIrwn/honda-leasing-api/internal/domain/models"
)

func newLeasingContractDocument(db *gorm.DB, opts ...gen.DOOption) leasingContractDocument {
	_leasingContractDocument := leasingContractDocument{}

	_leasingContractDocument.leasingContractDocumentDo.UseDB(db, opts...)
	_leasingContractDocument.leasingContractDocumentDo.UseModel(&models.LeasingContractDocument{})

	tableName := _leasingContractDocument.leasingContractDocumentDo.TableName()
	_leasingContractDocument.ALL = field.NewAsterisk(tableName)
	_leasingContractDocument.LocID = field.NewInt64(tableName, "loc_id")
	_leasingContractDocument.FileName = field.NewString(tableName, "file_name")
	_leasingContractDocument.FileSize = field.NewFloat64(tableName, "file_size")
	_leasingContractDocument.FileType = field.NewString(tableName, "file_type")
	_leasingContractDocument.FileURL = field.NewString(tableName, "file_url")
	_leasingContractDocument.ContractID = field.NewInt64(tableName, "contract_id")
	_leasingContractDocument.Contract = leasingContractDocumentHasOneContract{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Contract", "models.LeasingContract"),
		Customer: struct {
			field.RelationField
			Location struct {
				field.RelationField
				Kelurahan struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}
			}
			LeasingContracts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Contract.Customer", "models.Customer"),
			Location: struct {
				field.RelationField
				Kelurahan struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Contract.Customer.Location", "models.Location"),
				Kelurahan: struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan", "models.Kelurahan"),
					Kecamatan: struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan", "models.Kecamatan"),
						Kabupaten: struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten", "models.Kabupaten"),
							Province: struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Province", "models.Province"),
								Kabupaten: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Province.Kabupaten", "models.Kabupaten"),
								},
							},
							Kecamatan: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Kecamatan", "models.Kecamatan"),
							},
						},
						Kelurahan: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kelurahan", "models.Kelurahan"),
						},
					},
					Locations: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Locations", "models.Location"),
					},
				},
			},
			LeasingContracts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.Customer.LeasingContracts", "models.LeasingContract"),
			},
		},
		Motor: struct {
			field.RelationField
			MotorTypeRef struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}
			MotorAssets struct {
				field.RelationField
				Motor struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Contract.Motor", "models.Motor"),
			MotorTypeRef: struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.Motor.MotorTypeRef", "models.MotorType"),
				Motors: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.Motor.MotorTypeRef.Motors", "models.Motor"),
				},
			},
			MotorAssets: struct {
				field.RelationField
				Motor struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.Motor.MotorAssets", "models.MotorAsset"),
				Motor: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.Motor.MotorAssets.Motor", "models.Motor"),
				},
			},
		},
		Product: struct {
			field.RelationField
			LeasingContracts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Contract.Product", "models.LeasingProduct"),
			LeasingContracts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.Product.LeasingContracts", "models.LeasingContract"),
			},
		},
		LeasingTasks: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Role struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}
			LeasingAttribute struct {
				field.RelationField
				Task struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Contract.LeasingTasks", "models.LeasingTask"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.LeasingTasks.Contract", "models.LeasingContract"),
			},
			Role: struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("Contract.LeasingTasks.Role", "models.Role"),
				UserRoles: struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles", "models.UserRole"),
					User: struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User", "models.User"),
						UserOAuthProviders: struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}{
							RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders", "models.UserOAuthProvider"),
							User: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.User", "models.User"),
							},
							Provider: struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.Provider", "models.OAuthProvider"),
								UserOAuthProviders: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.Provider.UserOAuthProviders", "models.UserOAuthProvider"),
								},
							},
						},
						UserRoles: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserRoles", "models.UserRole"),
						},
					},
					Role: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.Role", "models.Role"),
					},
				},
				RolePermissions: struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions", "models.RolePermission"),
					Role: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions.Role", "models.Role"),
					},
					Permission: struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions.Permission", "models.Permission"),
						RolePermissions: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions.Permission.RolePermissions", "models.RolePermission"),
						},
					},
				},
			},
			LeasingAttribute: struct {
				field.RelationField
				Task struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.LeasingTasks.LeasingAttribute", "models.LeasingTaskAttribute"),
				Task: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.LeasingTasks.LeasingAttribute.Task", "models.LeasingTask"),
				},
			},
		},
		PaymentSchedules: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Payments struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Schedule struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Contract.PaymentSchedules", "models.PaymentSchedule"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.PaymentSchedules.Contract", "models.LeasingContract"),
			},
			Payments: struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Schedule struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.PaymentSchedules.Payments", "models.Payment"),
				Contract: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.PaymentSchedules.Payments.Contract", "models.LeasingContract"),
				},
				Schedule: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.PaymentSchedules.Payments.Schedule", "models.PaymentSchedule"),
				},
			},
		},
		Payments: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Contract.Payments", "models.Payment"),
		},
		ContractDocuments: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Contract.ContractDocuments", "models.LeasingContractDocument"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.ContractDocuments.Contract", "models.LeasingContract"),
			},
		},
	}

	_leasingContractDocument.fillFieldMap()

	return _leasingContractDocument
}

type leasingContractDocument struct {
	leasingContractDocumentDo

	ALL        field.Asterisk
	LocID      field.Int64
	FileName   field.String
	FileSize   field.Float64
	FileType   field.String
	FileURL    field.String
	ContractID field.Int64
	Contract   leasingContractDocumentHasOneContract

	fieldMap map[string]field.Expr
}

func (l leasingContractDocument) Table(newTableName string) *leasingContractDocument {
	l.leasingContractDocumentDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l leasingContractDocument) As(alias string) *leasingContractDocument {
	l.leasingContractDocumentDo.DO = *(l.leasingContractDocumentDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *leasingContractDocument) updateTableName(table string) *leasingContractDocument {
	l.ALL = field.NewAsterisk(table)
	l.LocID = field.NewInt64(table, "loc_id")
	l.FileName = field.NewString(table, "file_name")
	l.FileSize = field.NewFloat64(table, "file_size")
	l.FileType = field.NewString(table, "file_type")
	l.FileURL = field.NewString(table, "file_url")
	l.ContractID = field.NewInt64(table, "contract_id")

	l.fillFieldMap()

	return l
}

func (l *leasingContractDocument) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *leasingContractDocument) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 7)
	l.fieldMap["loc_id"] = l.LocID
	l.fieldMap["file_name"] = l.FileName
	l.fieldMap["file_size"] = l.FileSize
	l.fieldMap["file_type"] = l.FileType
	l.fieldMap["file_url"] = l.FileURL
	l.fieldMap["contract_id"] = l.ContractID

}

func (l leasingContractDocument) clone(db *gorm.DB) leasingContractDocument {
	l.leasingContractDocumentDo.ReplaceConnPool(db.Statement.ConnPool)
	l.Contract.db = db.Session(&gorm.Session{Initialized: true})
	l.Contract.db.Statement.ConnPool = db.Statement.ConnPool
	return l
}

func (l leasingContractDocument) replaceDB(db *gorm.DB) leasingContractDocument {
	l.leasingContractDocumentDo.ReplaceDB(db)
	l.Contract.db = db.Session(&gorm.Session{})
	return l
}

type leasingContractDocumentHasOneContract struct {
	db *gorm.DB

	field.RelationField

	Customer struct {
		field.RelationField
		Location struct {
			field.RelationField
			Kelurahan struct {
				field.RelationField
				Kecamatan struct {
					field.RelationField
					Kabupaten struct {
						field.RelationField
						Province struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
							}
						}
						Kecamatan struct {
							field.RelationField
						}
					}
					Kelurahan struct {
						field.RelationField
					}
				}
				Locations struct {
					field.RelationField
				}
			}
		}
		LeasingContracts struct {
			field.RelationField
		}
	}
	Motor struct {
		field.RelationField
		MotorTypeRef struct {
			field.RelationField
			Motors struct {
				field.RelationField
			}
		}
		MotorAssets struct {
			field.RelationField
			Motor struct {
				field.RelationField
			}
		}
	}
	Product struct {
		field.RelationField
		LeasingContracts struct {
			field.RelationField
		}
	}
	LeasingTasks struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
		Role struct {
			field.RelationField
			UserRoles struct {
				field.RelationField
				User struct {
					field.RelationField
					UserOAuthProviders struct {
						field.RelationField
						User struct {
							field.RelationField
						}
						Provider struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}
					}
					UserRoles struct {
						field.RelationField
					}
				}
				Role struct {
					field.RelationField
				}
			}
			RolePermissions struct {
				field.RelationField
				Role struct {
					field.RelationField
				}
				Permission struct {
					field.RelationField
					RolePermissions struct {
						field.RelationField
					}
				}
			}
		}
		LeasingAttribute struct {
			field.RelationField
			Task struct {
				field.RelationField
			}
		}
	}
	PaymentSchedules struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
		Payments struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Schedule struct {
				field.RelationField
			}
		}
	}
	Payments struct {
		field.RelationField
	}
	ContractDocuments struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
	}
}

func (a leasingContractDocumentHasOneContract) Where(conds ...field.Expr) *leasingContractDocumentHasOneContract {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a leasingContractDocumentHasOneContract) WithContext(ctx context.Context) *leasingContractDocumentHasOneContract {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a leasingContractDocumentHasOneContract) Session(session *gorm.Session) *leasingContractDocumentHasOneContract {
	a.db = a.db.Session(session)
	return &a
}

func (a leasingContractDocumentHasOneContract) Model(m *models.LeasingContractDocument) *leasingContractDocumentHasOneContractTx {
	return &leasingContractDocumentHasOneContractTx{a.db.Model(m).Association(a.Name())}
}

func (a leasingContractDocumentHasOneContract) Unscoped() *leasingContractDocumentHasOneContract {
	a.db = a.db.Unscoped()
	return &a
}

type leasingContractDocumentHasOneContractTx struct{ tx *gorm.Association }

func (a leasingContractDocumentHasOneContractTx) Find() (result *models.LeasingContract, err error) {
	return result, a.tx.Find(&result)
}

func (a leasingContractDocumentHasOneContractTx) Append(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a leasingContractDocumentHasOneContractTx) Replace(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a leasingContractDocumentHasOneContractTx) Delete(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a leasingContractDocumentHasOneContractTx) Clear() error {
	return a.tx.Clear()
}

func (a leasingContractDocumentHasOneContractTx) Count() int64 {
	return a.tx.Count()
}

func (a leasingContractDocumentHasOneContractTx) Unscoped() *leasingContractDocumentHasOneContractTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type leasingContractDocumentDo struct{ gen.DO }

type ILeasingContractDocumentDo interface {
	gen.SubQuery
	Debug() ILeasingContractDocumentDo
	WithContext(ctx context.Context) ILeasingContractDocumentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILeasingContractDocumentDo
	WriteDB() ILeasingContractDocumentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILeasingContractDocumentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILeasingContractDocumentDo
	Not(conds ...gen.Condition) ILeasingContractDocumentDo
	Or(conds ...gen.Condition) ILeasingContractDocumentDo
	Select(conds ...field.Expr) ILeasingContractDocumentDo
	Where(conds ...gen.Condition) ILeasingContractDocumentDo
	Order(conds ...field.Expr) ILeasingContractDocumentDo
	Distinct(cols ...field.Expr) ILeasingContractDocumentDo
	Omit(cols ...field.Expr) ILeasingContractDocumentDo
	Join(table schema.Tabler, on ...field.Expr) ILeasingContractDocumentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDocumentDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDocumentDo
	Group(cols ...field.Expr) ILeasingContractDocumentDo
	Having(conds ...gen.Condition) ILeasingContractDocumentDo
	Limit(limit int) ILeasingContractDocumentDo
	Offset(offset int) ILeasingContractDocumentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingContractDocumentDo
	Unscoped() ILeasingContractDocumentDo
	Create(values ...*models.LeasingContractDocument) error
	CreateInBatches(values []*models.LeasingContractDocument, batchSize int) error
	Save(values ...*models.LeasingContractDocument) error
	First() (*models.LeasingContractDocument, error)
	Take() (*models.LeasingContractDocument, error)
	Last() (*models.LeasingContractDocument, error)
	Find() ([]*models.LeasingContractDocument, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LeasingContractDocument, err error)
	FindInBatches(result *[]*models.LeasingContractDocument, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.LeasingContractDocument) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILeasingContractDocumentDo
	Assign(attrs ...field.AssignExpr) ILeasingContractDocumentDo
	Joins(fields ...field.RelationField) ILeasingContractDocumentDo
	Preload(fields ...field.RelationField) ILeasingContractDocumentDo
	FirstOrInit() (*models.LeasingContractDocument, error)
	FirstOrCreate() (*models.LeasingContractDocument, error)
	FindByPage(offset int, limit int) (result []*models.LeasingContractDocument, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILeasingContractDocumentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l leasingContractDocumentDo) Debug() ILeasingContractDocumentDo {
	return l.withDO(l.DO.Debug())
}

func (l leasingContractDocumentDo) WithContext(ctx context.Context) ILeasingContractDocumentDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l leasingContractDocumentDo) ReadDB() ILeasingContractDocumentDo {
	return l.Clauses(dbresolver.Read)
}

func (l leasingContractDocumentDo) WriteDB() ILeasingContractDocumentDo {
	return l.Clauses(dbresolver.Write)
}

func (l leasingContractDocumentDo) Session(config *gorm.Session) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Session(config))
}

func (l leasingContractDocumentDo) Clauses(conds ...clause.Expression) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l leasingContractDocumentDo) Returning(value interface{}, columns ...string) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l leasingContractDocumentDo) Not(conds ...gen.Condition) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l leasingContractDocumentDo) Or(conds ...gen.Condition) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l leasingContractDocumentDo) Select(conds ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l leasingContractDocumentDo) Where(conds ...gen.Condition) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l leasingContractDocumentDo) Order(conds ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l leasingContractDocumentDo) Distinct(cols ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l leasingContractDocumentDo) Omit(cols ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l leasingContractDocumentDo) Join(table schema.Tabler, on ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l leasingContractDocumentDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l leasingContractDocumentDo) RightJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l leasingContractDocumentDo) Group(cols ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l leasingContractDocumentDo) Having(conds ...gen.Condition) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l leasingContractDocumentDo) Limit(limit int) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l leasingContractDocumentDo) Offset(offset int) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l leasingContractDocumentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l leasingContractDocumentDo) Unscoped() ILeasingContractDocumentDo {
	return l.withDO(l.DO.Unscoped())
}

func (l leasingContractDocumentDo) Create(values ...*models.LeasingContractDocument) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l leasingContractDocumentDo) CreateInBatches(values []*models.LeasingContractDocument, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l leasingContractDocumentDo) Save(values ...*models.LeasingContractDocument) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l leasingContractDocumentDo) First() (*models.LeasingContractDocument, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingContractDocument), nil
	}
}

func (l leasingContractDocumentDo) Take() (*models.LeasingContractDocument, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingContractDocument), nil
	}
}

func (l leasingContractDocumentDo) Last() (*models.LeasingContractDocument, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingContractDocument), nil
	}
}

func (l leasingContractDocumentDo) Find() ([]*models.LeasingContractDocument, error) {
	result, err := l.DO.Find()
	return result.([]*models.LeasingContractDocument), err
}

func (l leasingContractDocumentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LeasingContractDocument, err error) {
	buf := make([]*models.LeasingContractDocument, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l leasingContractDocumentDo) FindInBatches(result *[]*models.LeasingContractDocument, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l leasingContractDocumentDo) Attrs(attrs ...field.AssignExpr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l leasingContractDocumentDo) Assign(attrs ...field.AssignExpr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l leasingContractDocumentDo) Joins(fields ...field.RelationField) ILeasingContractDocumentDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l leasingContractDocumentDo) Preload(fields ...field.RelationField) ILeasingContractDocumentDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l leasingContractDocumentDo) FirstOrInit() (*models.LeasingContractDocument, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingContractDocument), nil
	}
}

func (l leasingContractDocumentDo) FirstOrCreate() (*models.LeasingContractDocument, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingContractDocument), nil
	}
}

func (l leasingContractDocumentDo) FindByPage(offset int, limit int) (result []*models.LeasingContractDocument, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l leasingContractDocumentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l leasingContractDocumentDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l leasingContractDocumentDo) Delete(models ...*models.LeasingContractDocument) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *leasingContractDocumentDo) withDO(do gen.Dao) *leasingContractDocumentDo {
	l.DO = *do.(*gen.DO)
	return l
}
