// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HendraaaIrwn/honda-leasing-api/internal/domain/models"
)

func newMotor(db *gorm.DB, opts ...gen.DOOption) motor {
	_motor := motor{}

	_motor.motorDo.UseDB(db, opts...)
	_motor.motorDo.UseModel(&models.Motor{})

	tableName := _motor.motorDo.TableName()
	_motor.ALL = field.NewAsterisk(tableName)
	_motor.MotorID = field.NewInt64(tableName, "motor_id")
	_motor.Merk = field.NewString(tableName, "merk")
	_motor.MotorType = field.NewString(tableName, "motor_type")
	_motor.Tahun = field.NewInt16(tableName, "tahun")
	_motor.Warna = field.NewString(tableName, "warna")
	_motor.NomorRangka = field.NewString(tableName, "nomor_rangka")
	_motor.NomorMesin = field.NewString(tableName, "nomor_mesin")
	_motor.CCMesin = field.NewString(tableName, "cc_mesin")
	_motor.NomorPolisi = field.NewString(tableName, "nomor_polisi")
	_motor.StatusUnit = field.NewString(tableName, "status_unit")
	_motor.HargaOTR = field.NewFloat64(tableName, "harga_otr")
	_motor.CreatedAt = field.NewTime(tableName, "created_at")
	_motor.MotorMotyID = field.NewInt64(tableName, "motor_moty_id")
	_motor.MotorAssets = motorHasManyMotorAssets{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("MotorAssets", "models.MotorAsset"),
		Motor: struct {
			field.RelationField
			MotorTypeRef struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}
			MotorAssets struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("MotorAssets.Motor", "models.Motor"),
			MotorTypeRef: struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("MotorAssets.Motor.MotorTypeRef", "models.MotorType"),
				Motors: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("MotorAssets.Motor.MotorTypeRef.Motors", "models.Motor"),
				},
			},
			MotorAssets: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("MotorAssets.Motor.MotorAssets", "models.MotorAsset"),
			},
		},
	}

	_motor.MotorTypeRef = motorBelongsToMotorTypeRef{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("MotorTypeRef", "models.MotorType"),
	}

	_motor.fillFieldMap()

	return _motor
}

type motor struct {
	motorDo

	ALL         field.Asterisk
	MotorID     field.Int64
	Merk        field.String
	MotorType   field.String
	Tahun       field.Int16
	Warna       field.String
	NomorRangka field.String
	NomorMesin  field.String
	CCMesin     field.String
	NomorPolisi field.String
	StatusUnit  field.String
	HargaOTR    field.Float64
	CreatedAt   field.Time
	MotorMotyID field.Int64
	MotorAssets motorHasManyMotorAssets

	MotorTypeRef motorBelongsToMotorTypeRef

	fieldMap map[string]field.Expr
}

func (m motor) Table(newTableName string) *motor {
	m.motorDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m motor) As(alias string) *motor {
	m.motorDo.DO = *(m.motorDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *motor) updateTableName(table string) *motor {
	m.ALL = field.NewAsterisk(table)
	m.MotorID = field.NewInt64(table, "motor_id")
	m.Merk = field.NewString(table, "merk")
	m.MotorType = field.NewString(table, "motor_type")
	m.Tahun = field.NewInt16(table, "tahun")
	m.Warna = field.NewString(table, "warna")
	m.NomorRangka = field.NewString(table, "nomor_rangka")
	m.NomorMesin = field.NewString(table, "nomor_mesin")
	m.CCMesin = field.NewString(table, "cc_mesin")
	m.NomorPolisi = field.NewString(table, "nomor_polisi")
	m.StatusUnit = field.NewString(table, "status_unit")
	m.HargaOTR = field.NewFloat64(table, "harga_otr")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.MotorMotyID = field.NewInt64(table, "motor_moty_id")

	m.fillFieldMap()

	return m
}

func (m *motor) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *motor) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 15)
	m.fieldMap["motor_id"] = m.MotorID
	m.fieldMap["merk"] = m.Merk
	m.fieldMap["motor_type"] = m.MotorType
	m.fieldMap["tahun"] = m.Tahun
	m.fieldMap["warna"] = m.Warna
	m.fieldMap["nomor_rangka"] = m.NomorRangka
	m.fieldMap["nomor_mesin"] = m.NomorMesin
	m.fieldMap["cc_mesin"] = m.CCMesin
	m.fieldMap["nomor_polisi"] = m.NomorPolisi
	m.fieldMap["status_unit"] = m.StatusUnit
	m.fieldMap["harga_otr"] = m.HargaOTR
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["motor_moty_id"] = m.MotorMotyID

}

func (m motor) clone(db *gorm.DB) motor {
	m.motorDo.ReplaceConnPool(db.Statement.ConnPool)
	m.MotorAssets.db = db.Session(&gorm.Session{Initialized: true})
	m.MotorAssets.db.Statement.ConnPool = db.Statement.ConnPool
	m.MotorTypeRef.db = db.Session(&gorm.Session{Initialized: true})
	m.MotorTypeRef.db.Statement.ConnPool = db.Statement.ConnPool
	return m
}

func (m motor) replaceDB(db *gorm.DB) motor {
	m.motorDo.ReplaceDB(db)
	m.MotorAssets.db = db.Session(&gorm.Session{})
	m.MotorTypeRef.db = db.Session(&gorm.Session{})
	return m
}

type motorHasManyMotorAssets struct {
	db *gorm.DB

	field.RelationField

	Motor struct {
		field.RelationField
		MotorTypeRef struct {
			field.RelationField
			Motors struct {
				field.RelationField
			}
		}
		MotorAssets struct {
			field.RelationField
		}
	}
}

func (a motorHasManyMotorAssets) Where(conds ...field.Expr) *motorHasManyMotorAssets {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a motorHasManyMotorAssets) WithContext(ctx context.Context) *motorHasManyMotorAssets {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a motorHasManyMotorAssets) Session(session *gorm.Session) *motorHasManyMotorAssets {
	a.db = a.db.Session(session)
	return &a
}

func (a motorHasManyMotorAssets) Model(m *models.Motor) *motorHasManyMotorAssetsTx {
	return &motorHasManyMotorAssetsTx{a.db.Model(m).Association(a.Name())}
}

func (a motorHasManyMotorAssets) Unscoped() *motorHasManyMotorAssets {
	a.db = a.db.Unscoped()
	return &a
}

type motorHasManyMotorAssetsTx struct{ tx *gorm.Association }

func (a motorHasManyMotorAssetsTx) Find() (result []*models.MotorAsset, err error) {
	return result, a.tx.Find(&result)
}

func (a motorHasManyMotorAssetsTx) Append(values ...*models.MotorAsset) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a motorHasManyMotorAssetsTx) Replace(values ...*models.MotorAsset) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a motorHasManyMotorAssetsTx) Delete(values ...*models.MotorAsset) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a motorHasManyMotorAssetsTx) Clear() error {
	return a.tx.Clear()
}

func (a motorHasManyMotorAssetsTx) Count() int64 {
	return a.tx.Count()
}

func (a motorHasManyMotorAssetsTx) Unscoped() *motorHasManyMotorAssetsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type motorBelongsToMotorTypeRef struct {
	db *gorm.DB

	field.RelationField
}

func (a motorBelongsToMotorTypeRef) Where(conds ...field.Expr) *motorBelongsToMotorTypeRef {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a motorBelongsToMotorTypeRef) WithContext(ctx context.Context) *motorBelongsToMotorTypeRef {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a motorBelongsToMotorTypeRef) Session(session *gorm.Session) *motorBelongsToMotorTypeRef {
	a.db = a.db.Session(session)
	return &a
}

func (a motorBelongsToMotorTypeRef) Model(m *models.Motor) *motorBelongsToMotorTypeRefTx {
	return &motorBelongsToMotorTypeRefTx{a.db.Model(m).Association(a.Name())}
}

func (a motorBelongsToMotorTypeRef) Unscoped() *motorBelongsToMotorTypeRef {
	a.db = a.db.Unscoped()
	return &a
}

type motorBelongsToMotorTypeRefTx struct{ tx *gorm.Association }

func (a motorBelongsToMotorTypeRefTx) Find() (result *models.MotorType, err error) {
	return result, a.tx.Find(&result)
}

func (a motorBelongsToMotorTypeRefTx) Append(values ...*models.MotorType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a motorBelongsToMotorTypeRefTx) Replace(values ...*models.MotorType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a motorBelongsToMotorTypeRefTx) Delete(values ...*models.MotorType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a motorBelongsToMotorTypeRefTx) Clear() error {
	return a.tx.Clear()
}

func (a motorBelongsToMotorTypeRefTx) Count() int64 {
	return a.tx.Count()
}

func (a motorBelongsToMotorTypeRefTx) Unscoped() *motorBelongsToMotorTypeRefTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type motorDo struct{ gen.DO }

type IMotorDo interface {
	gen.SubQuery
	Debug() IMotorDo
	WithContext(ctx context.Context) IMotorDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMotorDo
	WriteDB() IMotorDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMotorDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMotorDo
	Not(conds ...gen.Condition) IMotorDo
	Or(conds ...gen.Condition) IMotorDo
	Select(conds ...field.Expr) IMotorDo
	Where(conds ...gen.Condition) IMotorDo
	Order(conds ...field.Expr) IMotorDo
	Distinct(cols ...field.Expr) IMotorDo
	Omit(cols ...field.Expr) IMotorDo
	Join(table schema.Tabler, on ...field.Expr) IMotorDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMotorDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMotorDo
	Group(cols ...field.Expr) IMotorDo
	Having(conds ...gen.Condition) IMotorDo
	Limit(limit int) IMotorDo
	Offset(offset int) IMotorDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMotorDo
	Unscoped() IMotorDo
	Create(values ...*models.Motor) error
	CreateInBatches(values []*models.Motor, batchSize int) error
	Save(values ...*models.Motor) error
	First() (*models.Motor, error)
	Take() (*models.Motor, error)
	Last() (*models.Motor, error)
	Find() ([]*models.Motor, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Motor, err error)
	FindInBatches(result *[]*models.Motor, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Motor) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMotorDo
	Assign(attrs ...field.AssignExpr) IMotorDo
	Joins(fields ...field.RelationField) IMotorDo
	Preload(fields ...field.RelationField) IMotorDo
	FirstOrInit() (*models.Motor, error)
	FirstOrCreate() (*models.Motor, error)
	FindByPage(offset int, limit int) (result []*models.Motor, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMotorDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m motorDo) Debug() IMotorDo {
	return m.withDO(m.DO.Debug())
}

func (m motorDo) WithContext(ctx context.Context) IMotorDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m motorDo) ReadDB() IMotorDo {
	return m.Clauses(dbresolver.Read)
}

func (m motorDo) WriteDB() IMotorDo {
	return m.Clauses(dbresolver.Write)
}

func (m motorDo) Session(config *gorm.Session) IMotorDo {
	return m.withDO(m.DO.Session(config))
}

func (m motorDo) Clauses(conds ...clause.Expression) IMotorDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m motorDo) Returning(value interface{}, columns ...string) IMotorDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m motorDo) Not(conds ...gen.Condition) IMotorDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m motorDo) Or(conds ...gen.Condition) IMotorDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m motorDo) Select(conds ...field.Expr) IMotorDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m motorDo) Where(conds ...gen.Condition) IMotorDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m motorDo) Order(conds ...field.Expr) IMotorDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m motorDo) Distinct(cols ...field.Expr) IMotorDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m motorDo) Omit(cols ...field.Expr) IMotorDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m motorDo) Join(table schema.Tabler, on ...field.Expr) IMotorDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m motorDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMotorDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m motorDo) RightJoin(table schema.Tabler, on ...field.Expr) IMotorDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m motorDo) Group(cols ...field.Expr) IMotorDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m motorDo) Having(conds ...gen.Condition) IMotorDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m motorDo) Limit(limit int) IMotorDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m motorDo) Offset(offset int) IMotorDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m motorDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMotorDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m motorDo) Unscoped() IMotorDo {
	return m.withDO(m.DO.Unscoped())
}

func (m motorDo) Create(values ...*models.Motor) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m motorDo) CreateInBatches(values []*models.Motor, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m motorDo) Save(values ...*models.Motor) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m motorDo) First() (*models.Motor, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Motor), nil
	}
}

func (m motorDo) Take() (*models.Motor, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Motor), nil
	}
}

func (m motorDo) Last() (*models.Motor, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Motor), nil
	}
}

func (m motorDo) Find() ([]*models.Motor, error) {
	result, err := m.DO.Find()
	return result.([]*models.Motor), err
}

func (m motorDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Motor, err error) {
	buf := make([]*models.Motor, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m motorDo) FindInBatches(result *[]*models.Motor, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m motorDo) Attrs(attrs ...field.AssignExpr) IMotorDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m motorDo) Assign(attrs ...field.AssignExpr) IMotorDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m motorDo) Joins(fields ...field.RelationField) IMotorDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m motorDo) Preload(fields ...field.RelationField) IMotorDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m motorDo) FirstOrInit() (*models.Motor, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Motor), nil
	}
}

func (m motorDo) FirstOrCreate() (*models.Motor, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Motor), nil
	}
}

func (m motorDo) FindByPage(offset int, limit int) (result []*models.Motor, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m motorDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m motorDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m motorDo) Delete(models ...*models.Motor) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *motorDo) withDO(do gen.Dao) *motorDo {
	m.DO = *do.(*gen.DO)
	return m
}
