// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HendraaaIrwn/honda-leasing-api/internal/domain/models"
)

func newOAuthProvider(db *gorm.DB, opts ...gen.DOOption) oAuthProvider {
	_oAuthProvider := oAuthProvider{}

	_oAuthProvider.oAuthProviderDo.UseDB(db, opts...)
	_oAuthProvider.oAuthProviderDo.UseModel(&models.OAuthProvider{})

	tableName := _oAuthProvider.oAuthProviderDo.TableName()
	_oAuthProvider.ALL = field.NewAsterisk(tableName)
	_oAuthProvider.ProviderID = field.NewInt64(tableName, "provider_id")
	_oAuthProvider.ProviderName = field.NewString(tableName, "provider_name")
	_oAuthProvider.ClientID = field.NewString(tableName, "client_id")
	_oAuthProvider.ClientSecret = field.NewString(tableName, "client_secret")
	_oAuthProvider.RedirectURI = field.NewString(tableName, "redirect_uri")
	_oAuthProvider.IssuerURL = field.NewString(tableName, "issuer_url")
	_oAuthProvider.Active = field.NewBool(tableName, "active")
	_oAuthProvider.UserOAuthProviders = oAuthProviderHasManyUserOAuthProviders{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("UserOAuthProviders", "models.UserOAuthProvider"),
		User: struct {
			field.RelationField
			UserOAuthProviders struct {
				field.RelationField
			}
			UserRoles struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Role struct {
					field.RelationField
					UserRoles struct {
						field.RelationField
					}
					RolePermissions struct {
						field.RelationField
						Role struct {
							field.RelationField
						}
						Permission struct {
							field.RelationField
							RolePermissions struct {
								field.RelationField
							}
						}
					}
				}
			}
		}{
			RelationField: field.NewRelation("UserOAuthProviders.User", "models.User"),
			UserOAuthProviders: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("UserOAuthProviders.User.UserOAuthProviders", "models.UserOAuthProvider"),
			},
			UserRoles: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Role struct {
					field.RelationField
					UserRoles struct {
						field.RelationField
					}
					RolePermissions struct {
						field.RelationField
						Role struct {
							field.RelationField
						}
						Permission struct {
							field.RelationField
							RolePermissions struct {
								field.RelationField
							}
						}
					}
				}
			}{
				RelationField: field.NewRelation("UserOAuthProviders.User.UserRoles", "models.UserRole"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("UserOAuthProviders.User.UserRoles.User", "models.User"),
				},
				Role: struct {
					field.RelationField
					UserRoles struct {
						field.RelationField
					}
					RolePermissions struct {
						field.RelationField
						Role struct {
							field.RelationField
						}
						Permission struct {
							field.RelationField
							RolePermissions struct {
								field.RelationField
							}
						}
					}
				}{
					RelationField: field.NewRelation("UserOAuthProviders.User.UserRoles.Role", "models.Role"),
					UserRoles: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("UserOAuthProviders.User.UserRoles.Role.UserRoles", "models.UserRole"),
					},
					RolePermissions: struct {
						field.RelationField
						Role struct {
							field.RelationField
						}
						Permission struct {
							field.RelationField
							RolePermissions struct {
								field.RelationField
							}
						}
					}{
						RelationField: field.NewRelation("UserOAuthProviders.User.UserRoles.Role.RolePermissions", "models.RolePermission"),
						Role: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("UserOAuthProviders.User.UserRoles.Role.RolePermissions.Role", "models.Role"),
						},
						Permission: struct {
							field.RelationField
							RolePermissions struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("UserOAuthProviders.User.UserRoles.Role.RolePermissions.Permission", "models.Permission"),
							RolePermissions: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("UserOAuthProviders.User.UserRoles.Role.RolePermissions.Permission.RolePermissions", "models.RolePermission"),
							},
						},
					},
				},
			},
		},
		Provider: struct {
			field.RelationField
			UserOAuthProviders struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("UserOAuthProviders.Provider", "models.OAuthProvider"),
			UserOAuthProviders: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("UserOAuthProviders.Provider.UserOAuthProviders", "models.UserOAuthProvider"),
			},
		},
	}

	_oAuthProvider.fillFieldMap()

	return _oAuthProvider
}

type oAuthProvider struct {
	oAuthProviderDo

	ALL                field.Asterisk
	ProviderID         field.Int64
	ProviderName       field.String
	ClientID           field.String
	ClientSecret       field.String
	RedirectURI        field.String
	IssuerURL          field.String
	Active             field.Bool
	UserOAuthProviders oAuthProviderHasManyUserOAuthProviders

	fieldMap map[string]field.Expr
}

func (o oAuthProvider) Table(newTableName string) *oAuthProvider {
	o.oAuthProviderDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o oAuthProvider) As(alias string) *oAuthProvider {
	o.oAuthProviderDo.DO = *(o.oAuthProviderDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *oAuthProvider) updateTableName(table string) *oAuthProvider {
	o.ALL = field.NewAsterisk(table)
	o.ProviderID = field.NewInt64(table, "provider_id")
	o.ProviderName = field.NewString(table, "provider_name")
	o.ClientID = field.NewString(table, "client_id")
	o.ClientSecret = field.NewString(table, "client_secret")
	o.RedirectURI = field.NewString(table, "redirect_uri")
	o.IssuerURL = field.NewString(table, "issuer_url")
	o.Active = field.NewBool(table, "active")

	o.fillFieldMap()

	return o
}

func (o *oAuthProvider) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *oAuthProvider) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 8)
	o.fieldMap["provider_id"] = o.ProviderID
	o.fieldMap["provider_name"] = o.ProviderName
	o.fieldMap["client_id"] = o.ClientID
	o.fieldMap["client_secret"] = o.ClientSecret
	o.fieldMap["redirect_uri"] = o.RedirectURI
	o.fieldMap["issuer_url"] = o.IssuerURL
	o.fieldMap["active"] = o.Active

}

func (o oAuthProvider) clone(db *gorm.DB) oAuthProvider {
	o.oAuthProviderDo.ReplaceConnPool(db.Statement.ConnPool)
	o.UserOAuthProviders.db = db.Session(&gorm.Session{Initialized: true})
	o.UserOAuthProviders.db.Statement.ConnPool = db.Statement.ConnPool
	return o
}

func (o oAuthProvider) replaceDB(db *gorm.DB) oAuthProvider {
	o.oAuthProviderDo.ReplaceDB(db)
	o.UserOAuthProviders.db = db.Session(&gorm.Session{})
	return o
}

type oAuthProviderHasManyUserOAuthProviders struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
		UserOAuthProviders struct {
			field.RelationField
		}
		UserRoles struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Role struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}
		}
	}
	Provider struct {
		field.RelationField
		UserOAuthProviders struct {
			field.RelationField
		}
	}
}

func (a oAuthProviderHasManyUserOAuthProviders) Where(conds ...field.Expr) *oAuthProviderHasManyUserOAuthProviders {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a oAuthProviderHasManyUserOAuthProviders) WithContext(ctx context.Context) *oAuthProviderHasManyUserOAuthProviders {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a oAuthProviderHasManyUserOAuthProviders) Session(session *gorm.Session) *oAuthProviderHasManyUserOAuthProviders {
	a.db = a.db.Session(session)
	return &a
}

func (a oAuthProviderHasManyUserOAuthProviders) Model(m *models.OAuthProvider) *oAuthProviderHasManyUserOAuthProvidersTx {
	return &oAuthProviderHasManyUserOAuthProvidersTx{a.db.Model(m).Association(a.Name())}
}

func (a oAuthProviderHasManyUserOAuthProviders) Unscoped() *oAuthProviderHasManyUserOAuthProviders {
	a.db = a.db.Unscoped()
	return &a
}

type oAuthProviderHasManyUserOAuthProvidersTx struct{ tx *gorm.Association }

func (a oAuthProviderHasManyUserOAuthProvidersTx) Find() (result []*models.UserOAuthProvider, err error) {
	return result, a.tx.Find(&result)
}

func (a oAuthProviderHasManyUserOAuthProvidersTx) Append(values ...*models.UserOAuthProvider) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a oAuthProviderHasManyUserOAuthProvidersTx) Replace(values ...*models.UserOAuthProvider) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a oAuthProviderHasManyUserOAuthProvidersTx) Delete(values ...*models.UserOAuthProvider) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a oAuthProviderHasManyUserOAuthProvidersTx) Clear() error {
	return a.tx.Clear()
}

func (a oAuthProviderHasManyUserOAuthProvidersTx) Count() int64 {
	return a.tx.Count()
}

func (a oAuthProviderHasManyUserOAuthProvidersTx) Unscoped() *oAuthProviderHasManyUserOAuthProvidersTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type oAuthProviderDo struct{ gen.DO }

type IOAuthProviderDo interface {
	gen.SubQuery
	Debug() IOAuthProviderDo
	WithContext(ctx context.Context) IOAuthProviderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOAuthProviderDo
	WriteDB() IOAuthProviderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOAuthProviderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOAuthProviderDo
	Not(conds ...gen.Condition) IOAuthProviderDo
	Or(conds ...gen.Condition) IOAuthProviderDo
	Select(conds ...field.Expr) IOAuthProviderDo
	Where(conds ...gen.Condition) IOAuthProviderDo
	Order(conds ...field.Expr) IOAuthProviderDo
	Distinct(cols ...field.Expr) IOAuthProviderDo
	Omit(cols ...field.Expr) IOAuthProviderDo
	Join(table schema.Tabler, on ...field.Expr) IOAuthProviderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOAuthProviderDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOAuthProviderDo
	Group(cols ...field.Expr) IOAuthProviderDo
	Having(conds ...gen.Condition) IOAuthProviderDo
	Limit(limit int) IOAuthProviderDo
	Offset(offset int) IOAuthProviderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOAuthProviderDo
	Unscoped() IOAuthProviderDo
	Create(values ...*models.OAuthProvider) error
	CreateInBatches(values []*models.OAuthProvider, batchSize int) error
	Save(values ...*models.OAuthProvider) error
	First() (*models.OAuthProvider, error)
	Take() (*models.OAuthProvider, error)
	Last() (*models.OAuthProvider, error)
	Find() ([]*models.OAuthProvider, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.OAuthProvider, err error)
	FindInBatches(result *[]*models.OAuthProvider, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.OAuthProvider) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOAuthProviderDo
	Assign(attrs ...field.AssignExpr) IOAuthProviderDo
	Joins(fields ...field.RelationField) IOAuthProviderDo
	Preload(fields ...field.RelationField) IOAuthProviderDo
	FirstOrInit() (*models.OAuthProvider, error)
	FirstOrCreate() (*models.OAuthProvider, error)
	FindByPage(offset int, limit int) (result []*models.OAuthProvider, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOAuthProviderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o oAuthProviderDo) Debug() IOAuthProviderDo {
	return o.withDO(o.DO.Debug())
}

func (o oAuthProviderDo) WithContext(ctx context.Context) IOAuthProviderDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o oAuthProviderDo) ReadDB() IOAuthProviderDo {
	return o.Clauses(dbresolver.Read)
}

func (o oAuthProviderDo) WriteDB() IOAuthProviderDo {
	return o.Clauses(dbresolver.Write)
}

func (o oAuthProviderDo) Session(config *gorm.Session) IOAuthProviderDo {
	return o.withDO(o.DO.Session(config))
}

func (o oAuthProviderDo) Clauses(conds ...clause.Expression) IOAuthProviderDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o oAuthProviderDo) Returning(value interface{}, columns ...string) IOAuthProviderDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o oAuthProviderDo) Not(conds ...gen.Condition) IOAuthProviderDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o oAuthProviderDo) Or(conds ...gen.Condition) IOAuthProviderDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o oAuthProviderDo) Select(conds ...field.Expr) IOAuthProviderDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o oAuthProviderDo) Where(conds ...gen.Condition) IOAuthProviderDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o oAuthProviderDo) Order(conds ...field.Expr) IOAuthProviderDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o oAuthProviderDo) Distinct(cols ...field.Expr) IOAuthProviderDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o oAuthProviderDo) Omit(cols ...field.Expr) IOAuthProviderDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o oAuthProviderDo) Join(table schema.Tabler, on ...field.Expr) IOAuthProviderDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o oAuthProviderDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOAuthProviderDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o oAuthProviderDo) RightJoin(table schema.Tabler, on ...field.Expr) IOAuthProviderDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o oAuthProviderDo) Group(cols ...field.Expr) IOAuthProviderDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o oAuthProviderDo) Having(conds ...gen.Condition) IOAuthProviderDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o oAuthProviderDo) Limit(limit int) IOAuthProviderDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o oAuthProviderDo) Offset(offset int) IOAuthProviderDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o oAuthProviderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOAuthProviderDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o oAuthProviderDo) Unscoped() IOAuthProviderDo {
	return o.withDO(o.DO.Unscoped())
}

func (o oAuthProviderDo) Create(values ...*models.OAuthProvider) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o oAuthProviderDo) CreateInBatches(values []*models.OAuthProvider, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o oAuthProviderDo) Save(values ...*models.OAuthProvider) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o oAuthProviderDo) First() (*models.OAuthProvider, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.OAuthProvider), nil
	}
}

func (o oAuthProviderDo) Take() (*models.OAuthProvider, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.OAuthProvider), nil
	}
}

func (o oAuthProviderDo) Last() (*models.OAuthProvider, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.OAuthProvider), nil
	}
}

func (o oAuthProviderDo) Find() ([]*models.OAuthProvider, error) {
	result, err := o.DO.Find()
	return result.([]*models.OAuthProvider), err
}

func (o oAuthProviderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.OAuthProvider, err error) {
	buf := make([]*models.OAuthProvider, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o oAuthProviderDo) FindInBatches(result *[]*models.OAuthProvider, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o oAuthProviderDo) Attrs(attrs ...field.AssignExpr) IOAuthProviderDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o oAuthProviderDo) Assign(attrs ...field.AssignExpr) IOAuthProviderDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o oAuthProviderDo) Joins(fields ...field.RelationField) IOAuthProviderDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o oAuthProviderDo) Preload(fields ...field.RelationField) IOAuthProviderDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o oAuthProviderDo) FirstOrInit() (*models.OAuthProvider, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.OAuthProvider), nil
	}
}

func (o oAuthProviderDo) FirstOrCreate() (*models.OAuthProvider, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.OAuthProvider), nil
	}
}

func (o oAuthProviderDo) FindByPage(offset int, limit int) (result []*models.OAuthProvider, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o oAuthProviderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o oAuthProviderDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o oAuthProviderDo) Delete(models ...*models.OAuthProvider) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *oAuthProviderDo) withDO(do gen.Dao) *oAuthProviderDo {
	o.DO = *do.(*gen.DO)
	return o
}
