// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HendraaaIrwn/honda-leasing-api/internal/domain/models"
)

func newPaymentSchedule(db *gorm.DB, opts ...gen.DOOption) paymentSchedule {
	_paymentSchedule := paymentSchedule{}

	_paymentSchedule.paymentScheduleDo.UseDB(db, opts...)
	_paymentSchedule.paymentScheduleDo.UseModel(&models.PaymentSchedule{})

	tableName := _paymentSchedule.paymentScheduleDo.TableName()
	_paymentSchedule.ALL = field.NewAsterisk(tableName)
	_paymentSchedule.ScheduleID = field.NewInt64(tableName, "schedule_id")
	_paymentSchedule.AngsuranKe = field.NewInt16(tableName, "angsuran_ke")
	_paymentSchedule.JatuhTempo = field.NewTime(tableName, "jatuh_tempo")
	_paymentSchedule.Pokok = field.NewFloat64(tableName, "pokok")
	_paymentSchedule.Margin = field.NewFloat64(tableName, "margin")
	_paymentSchedule.TotalTagihan = field.NewFloat64(tableName, "total_tagihan")
	_paymentSchedule.StatusPembayaran = field.NewString(tableName, "status_pembayaran")
	_paymentSchedule.TanggalBayar = field.NewTime(tableName, "tanggal_bayar")
	_paymentSchedule.CreatedAt = field.NewTime(tableName, "created_at")
	_paymentSchedule.ContractID = field.NewInt64(tableName, "contract_id")
	_paymentSchedule.Contract = paymentScheduleHasOneContract{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Contract", "models.LeasingContract"),
		Customer: struct {
			field.RelationField
			Location struct {
				field.RelationField
				Kelurahan struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}
			}
			LeasingContracts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Contract.Customer", "models.Customer"),
			Location: struct {
				field.RelationField
				Kelurahan struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Contract.Customer.Location", "models.Location"),
				Kelurahan: struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan", "models.Kelurahan"),
					Kecamatan: struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan", "models.Kecamatan"),
						Kabupaten: struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten", "models.Kabupaten"),
							Province: struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Province", "models.Province"),
								Kabupaten: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Province.Kabupaten", "models.Kabupaten"),
								},
							},
							Kecamatan: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Kecamatan", "models.Kecamatan"),
							},
						},
						Kelurahan: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kelurahan", "models.Kelurahan"),
						},
					},
					Locations: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Locations", "models.Location"),
					},
				},
			},
			LeasingContracts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.Customer.LeasingContracts", "models.LeasingContract"),
			},
		},
		Motor: struct {
			field.RelationField
			MotorTypeRef struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}
			MotorAssets struct {
				field.RelationField
				Motor struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Contract.Motor", "models.Motor"),
			MotorTypeRef: struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.Motor.MotorTypeRef", "models.MotorType"),
				Motors: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.Motor.MotorTypeRef.Motors", "models.Motor"),
				},
			},
			MotorAssets: struct {
				field.RelationField
				Motor struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.Motor.MotorAssets", "models.MotorAsset"),
				Motor: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.Motor.MotorAssets.Motor", "models.Motor"),
				},
			},
		},
		Product: struct {
			field.RelationField
			LeasingContracts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Contract.Product", "models.LeasingProduct"),
			LeasingContracts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.Product.LeasingContracts", "models.LeasingContract"),
			},
		},
		LeasingTasks: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Role struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}
			LeasingAttribute struct {
				field.RelationField
				Task struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Contract.LeasingTasks", "models.LeasingTask"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.LeasingTasks.Contract", "models.LeasingContract"),
			},
			Role: struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("Contract.LeasingTasks.Role", "models.Role"),
				UserRoles: struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles", "models.UserRole"),
					User: struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User", "models.User"),
						UserOAuthProviders: struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}{
							RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders", "models.UserOAuthProvider"),
							User: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.User", "models.User"),
							},
							Provider: struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.Provider", "models.OAuthProvider"),
								UserOAuthProviders: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.Provider.UserOAuthProviders", "models.UserOAuthProvider"),
								},
							},
						},
						UserRoles: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserRoles", "models.UserRole"),
						},
					},
					Role: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.Role", "models.Role"),
					},
				},
				RolePermissions: struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions", "models.RolePermission"),
					Role: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions.Role", "models.Role"),
					},
					Permission: struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions.Permission", "models.Permission"),
						RolePermissions: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions.Permission.RolePermissions", "models.RolePermission"),
						},
					},
				},
			},
			LeasingAttribute: struct {
				field.RelationField
				Task struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.LeasingTasks.LeasingAttribute", "models.LeasingTaskAttribute"),
				Task: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.LeasingTasks.LeasingAttribute.Task", "models.LeasingTask"),
				},
			},
		},
		PaymentSchedules: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Payments struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Schedule struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Contract.PaymentSchedules", "models.PaymentSchedule"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.PaymentSchedules.Contract", "models.LeasingContract"),
			},
			Payments: struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Schedule struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.PaymentSchedules.Payments", "models.Payment"),
				Contract: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.PaymentSchedules.Payments.Contract", "models.LeasingContract"),
				},
				Schedule: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.PaymentSchedules.Payments.Schedule", "models.PaymentSchedule"),
				},
			},
		},
		Payments: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Contract.Payments", "models.Payment"),
		},
		ContractDocuments: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Contract.ContractDocuments", "models.LeasingContractDocument"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.ContractDocuments.Contract", "models.LeasingContract"),
			},
		},
	}

	_paymentSchedule.Payments = paymentScheduleHasManyPayments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Payments", "models.Payment"),
	}

	_paymentSchedule.fillFieldMap()

	return _paymentSchedule
}

type paymentSchedule struct {
	paymentScheduleDo

	ALL              field.Asterisk
	ScheduleID       field.Int64
	AngsuranKe       field.Int16
	JatuhTempo       field.Time
	Pokok            field.Float64
	Margin           field.Float64
	TotalTagihan     field.Float64
	StatusPembayaran field.String
	TanggalBayar     field.Time
	CreatedAt        field.Time
	ContractID       field.Int64
	Contract         paymentScheduleHasOneContract

	Payments paymentScheduleHasManyPayments

	fieldMap map[string]field.Expr
}

func (p paymentSchedule) Table(newTableName string) *paymentSchedule {
	p.paymentScheduleDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentSchedule) As(alias string) *paymentSchedule {
	p.paymentScheduleDo.DO = *(p.paymentScheduleDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentSchedule) updateTableName(table string) *paymentSchedule {
	p.ALL = field.NewAsterisk(table)
	p.ScheduleID = field.NewInt64(table, "schedule_id")
	p.AngsuranKe = field.NewInt16(table, "angsuran_ke")
	p.JatuhTempo = field.NewTime(table, "jatuh_tempo")
	p.Pokok = field.NewFloat64(table, "pokok")
	p.Margin = field.NewFloat64(table, "margin")
	p.TotalTagihan = field.NewFloat64(table, "total_tagihan")
	p.StatusPembayaran = field.NewString(table, "status_pembayaran")
	p.TanggalBayar = field.NewTime(table, "tanggal_bayar")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.ContractID = field.NewInt64(table, "contract_id")

	p.fillFieldMap()

	return p
}

func (p *paymentSchedule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentSchedule) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 12)
	p.fieldMap["schedule_id"] = p.ScheduleID
	p.fieldMap["angsuran_ke"] = p.AngsuranKe
	p.fieldMap["jatuh_tempo"] = p.JatuhTempo
	p.fieldMap["pokok"] = p.Pokok
	p.fieldMap["margin"] = p.Margin
	p.fieldMap["total_tagihan"] = p.TotalTagihan
	p.fieldMap["status_pembayaran"] = p.StatusPembayaran
	p.fieldMap["tanggal_bayar"] = p.TanggalBayar
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["contract_id"] = p.ContractID

}

func (p paymentSchedule) clone(db *gorm.DB) paymentSchedule {
	p.paymentScheduleDo.ReplaceConnPool(db.Statement.ConnPool)
	p.Contract.db = db.Session(&gorm.Session{Initialized: true})
	p.Contract.db.Statement.ConnPool = db.Statement.ConnPool
	p.Payments.db = db.Session(&gorm.Session{Initialized: true})
	p.Payments.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p paymentSchedule) replaceDB(db *gorm.DB) paymentSchedule {
	p.paymentScheduleDo.ReplaceDB(db)
	p.Contract.db = db.Session(&gorm.Session{})
	p.Payments.db = db.Session(&gorm.Session{})
	return p
}

type paymentScheduleHasOneContract struct {
	db *gorm.DB

	field.RelationField

	Customer struct {
		field.RelationField
		Location struct {
			field.RelationField
			Kelurahan struct {
				field.RelationField
				Kecamatan struct {
					field.RelationField
					Kabupaten struct {
						field.RelationField
						Province struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
							}
						}
						Kecamatan struct {
							field.RelationField
						}
					}
					Kelurahan struct {
						field.RelationField
					}
				}
				Locations struct {
					field.RelationField
				}
			}
		}
		LeasingContracts struct {
			field.RelationField
		}
	}
	Motor struct {
		field.RelationField
		MotorTypeRef struct {
			field.RelationField
			Motors struct {
				field.RelationField
			}
		}
		MotorAssets struct {
			field.RelationField
			Motor struct {
				field.RelationField
			}
		}
	}
	Product struct {
		field.RelationField
		LeasingContracts struct {
			field.RelationField
		}
	}
	LeasingTasks struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
		Role struct {
			field.RelationField
			UserRoles struct {
				field.RelationField
				User struct {
					field.RelationField
					UserOAuthProviders struct {
						field.RelationField
						User struct {
							field.RelationField
						}
						Provider struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}
					}
					UserRoles struct {
						field.RelationField
					}
				}
				Role struct {
					field.RelationField
				}
			}
			RolePermissions struct {
				field.RelationField
				Role struct {
					field.RelationField
				}
				Permission struct {
					field.RelationField
					RolePermissions struct {
						field.RelationField
					}
				}
			}
		}
		LeasingAttribute struct {
			field.RelationField
			Task struct {
				field.RelationField
			}
		}
	}
	PaymentSchedules struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
		Payments struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Schedule struct {
				field.RelationField
			}
		}
	}
	Payments struct {
		field.RelationField
	}
	ContractDocuments struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
	}
}

func (a paymentScheduleHasOneContract) Where(conds ...field.Expr) *paymentScheduleHasOneContract {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a paymentScheduleHasOneContract) WithContext(ctx context.Context) *paymentScheduleHasOneContract {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a paymentScheduleHasOneContract) Session(session *gorm.Session) *paymentScheduleHasOneContract {
	a.db = a.db.Session(session)
	return &a
}

func (a paymentScheduleHasOneContract) Model(m *models.PaymentSchedule) *paymentScheduleHasOneContractTx {
	return &paymentScheduleHasOneContractTx{a.db.Model(m).Association(a.Name())}
}

func (a paymentScheduleHasOneContract) Unscoped() *paymentScheduleHasOneContract {
	a.db = a.db.Unscoped()
	return &a
}

type paymentScheduleHasOneContractTx struct{ tx *gorm.Association }

func (a paymentScheduleHasOneContractTx) Find() (result *models.LeasingContract, err error) {
	return result, a.tx.Find(&result)
}

func (a paymentScheduleHasOneContractTx) Append(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a paymentScheduleHasOneContractTx) Replace(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a paymentScheduleHasOneContractTx) Delete(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a paymentScheduleHasOneContractTx) Clear() error {
	return a.tx.Clear()
}

func (a paymentScheduleHasOneContractTx) Count() int64 {
	return a.tx.Count()
}

func (a paymentScheduleHasOneContractTx) Unscoped() *paymentScheduleHasOneContractTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type paymentScheduleHasManyPayments struct {
	db *gorm.DB

	field.RelationField
}

func (a paymentScheduleHasManyPayments) Where(conds ...field.Expr) *paymentScheduleHasManyPayments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a paymentScheduleHasManyPayments) WithContext(ctx context.Context) *paymentScheduleHasManyPayments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a paymentScheduleHasManyPayments) Session(session *gorm.Session) *paymentScheduleHasManyPayments {
	a.db = a.db.Session(session)
	return &a
}

func (a paymentScheduleHasManyPayments) Model(m *models.PaymentSchedule) *paymentScheduleHasManyPaymentsTx {
	return &paymentScheduleHasManyPaymentsTx{a.db.Model(m).Association(a.Name())}
}

func (a paymentScheduleHasManyPayments) Unscoped() *paymentScheduleHasManyPayments {
	a.db = a.db.Unscoped()
	return &a
}

type paymentScheduleHasManyPaymentsTx struct{ tx *gorm.Association }

func (a paymentScheduleHasManyPaymentsTx) Find() (result []*models.Payment, err error) {
	return result, a.tx.Find(&result)
}

func (a paymentScheduleHasManyPaymentsTx) Append(values ...*models.Payment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a paymentScheduleHasManyPaymentsTx) Replace(values ...*models.Payment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a paymentScheduleHasManyPaymentsTx) Delete(values ...*models.Payment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a paymentScheduleHasManyPaymentsTx) Clear() error {
	return a.tx.Clear()
}

func (a paymentScheduleHasManyPaymentsTx) Count() int64 {
	return a.tx.Count()
}

func (a paymentScheduleHasManyPaymentsTx) Unscoped() *paymentScheduleHasManyPaymentsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type paymentScheduleDo struct{ gen.DO }

type IPaymentScheduleDo interface {
	gen.SubQuery
	Debug() IPaymentScheduleDo
	WithContext(ctx context.Context) IPaymentScheduleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPaymentScheduleDo
	WriteDB() IPaymentScheduleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPaymentScheduleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPaymentScheduleDo
	Not(conds ...gen.Condition) IPaymentScheduleDo
	Or(conds ...gen.Condition) IPaymentScheduleDo
	Select(conds ...field.Expr) IPaymentScheduleDo
	Where(conds ...gen.Condition) IPaymentScheduleDo
	Order(conds ...field.Expr) IPaymentScheduleDo
	Distinct(cols ...field.Expr) IPaymentScheduleDo
	Omit(cols ...field.Expr) IPaymentScheduleDo
	Join(table schema.Tabler, on ...field.Expr) IPaymentScheduleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentScheduleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPaymentScheduleDo
	Group(cols ...field.Expr) IPaymentScheduleDo
	Having(conds ...gen.Condition) IPaymentScheduleDo
	Limit(limit int) IPaymentScheduleDo
	Offset(offset int) IPaymentScheduleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentScheduleDo
	Unscoped() IPaymentScheduleDo
	Create(values ...*models.PaymentSchedule) error
	CreateInBatches(values []*models.PaymentSchedule, batchSize int) error
	Save(values ...*models.PaymentSchedule) error
	First() (*models.PaymentSchedule, error)
	Take() (*models.PaymentSchedule, error)
	Last() (*models.PaymentSchedule, error)
	Find() ([]*models.PaymentSchedule, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.PaymentSchedule, err error)
	FindInBatches(result *[]*models.PaymentSchedule, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.PaymentSchedule) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPaymentScheduleDo
	Assign(attrs ...field.AssignExpr) IPaymentScheduleDo
	Joins(fields ...field.RelationField) IPaymentScheduleDo
	Preload(fields ...field.RelationField) IPaymentScheduleDo
	FirstOrInit() (*models.PaymentSchedule, error)
	FirstOrCreate() (*models.PaymentSchedule, error)
	FindByPage(offset int, limit int) (result []*models.PaymentSchedule, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPaymentScheduleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p paymentScheduleDo) Debug() IPaymentScheduleDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentScheduleDo) WithContext(ctx context.Context) IPaymentScheduleDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentScheduleDo) ReadDB() IPaymentScheduleDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentScheduleDo) WriteDB() IPaymentScheduleDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentScheduleDo) Session(config *gorm.Session) IPaymentScheduleDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentScheduleDo) Clauses(conds ...clause.Expression) IPaymentScheduleDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentScheduleDo) Returning(value interface{}, columns ...string) IPaymentScheduleDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentScheduleDo) Not(conds ...gen.Condition) IPaymentScheduleDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentScheduleDo) Or(conds ...gen.Condition) IPaymentScheduleDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentScheduleDo) Select(conds ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentScheduleDo) Where(conds ...gen.Condition) IPaymentScheduleDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentScheduleDo) Order(conds ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentScheduleDo) Distinct(cols ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentScheduleDo) Omit(cols ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentScheduleDo) Join(table schema.Tabler, on ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentScheduleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentScheduleDo) RightJoin(table schema.Tabler, on ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentScheduleDo) Group(cols ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentScheduleDo) Having(conds ...gen.Condition) IPaymentScheduleDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentScheduleDo) Limit(limit int) IPaymentScheduleDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentScheduleDo) Offset(offset int) IPaymentScheduleDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentScheduleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentScheduleDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentScheduleDo) Unscoped() IPaymentScheduleDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentScheduleDo) Create(values ...*models.PaymentSchedule) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentScheduleDo) CreateInBatches(values []*models.PaymentSchedule, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentScheduleDo) Save(values ...*models.PaymentSchedule) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentScheduleDo) First() (*models.PaymentSchedule, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.PaymentSchedule), nil
	}
}

func (p paymentScheduleDo) Take() (*models.PaymentSchedule, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.PaymentSchedule), nil
	}
}

func (p paymentScheduleDo) Last() (*models.PaymentSchedule, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.PaymentSchedule), nil
	}
}

func (p paymentScheduleDo) Find() ([]*models.PaymentSchedule, error) {
	result, err := p.DO.Find()
	return result.([]*models.PaymentSchedule), err
}

func (p paymentScheduleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.PaymentSchedule, err error) {
	buf := make([]*models.PaymentSchedule, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentScheduleDo) FindInBatches(result *[]*models.PaymentSchedule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentScheduleDo) Attrs(attrs ...field.AssignExpr) IPaymentScheduleDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentScheduleDo) Assign(attrs ...field.AssignExpr) IPaymentScheduleDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentScheduleDo) Joins(fields ...field.RelationField) IPaymentScheduleDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentScheduleDo) Preload(fields ...field.RelationField) IPaymentScheduleDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentScheduleDo) FirstOrInit() (*models.PaymentSchedule, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.PaymentSchedule), nil
	}
}

func (p paymentScheduleDo) FirstOrCreate() (*models.PaymentSchedule, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.PaymentSchedule), nil
	}
}

func (p paymentScheduleDo) FindByPage(offset int, limit int) (result []*models.PaymentSchedule, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentScheduleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentScheduleDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentScheduleDo) Delete(models ...*models.PaymentSchedule) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentScheduleDo) withDO(do gen.Dao) *paymentScheduleDo {
	p.DO = *do.(*gen.DO)
	return p
}
