// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HendraaaIrwn/honda-leasing-api/internal/domain/models"
)

func newPayment(db *gorm.DB, opts ...gen.DOOption) payment {
	_payment := payment{}

	_payment.paymentDo.UseDB(db, opts...)
	_payment.paymentDo.UseModel(&models.Payment{})

	tableName := _payment.paymentDo.TableName()
	_payment.ALL = field.NewAsterisk(tableName)
	_payment.PaymentID = field.NewInt64(tableName, "payment_id")
	_payment.NomorBukti = field.NewString(tableName, "nomor_bukti")
	_payment.JumlahBayar = field.NewFloat64(tableName, "jumlah_bayar")
	_payment.TanggalBayar = field.NewTime(tableName, "tanggal_bayar")
	_payment.MetodePembayaran = field.NewString(tableName, "metode_pembayaran")
	_payment.Provider = field.NewString(tableName, "provider")
	_payment.CreatedAt = field.NewTime(tableName, "created_at")
	_payment.ContractID = field.NewInt64(tableName, "contract_id")
	_payment.ScheduleID = field.NewInt64(tableName, "schedule_id")
	_payment.Contract = paymentHasOneContract{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Contract", "models.LeasingContract"),
		Customer: struct {
			field.RelationField
			Location struct {
				field.RelationField
				Kelurahan struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}
			}
			LeasingContracts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Contract.Customer", "models.Customer"),
			Location: struct {
				field.RelationField
				Kelurahan struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Contract.Customer.Location", "models.Location"),
				Kelurahan: struct {
					field.RelationField
					Kecamatan struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}
					Locations struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan", "models.Kelurahan"),
					Kecamatan: struct {
						field.RelationField
						Kabupaten struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}
						Kelurahan struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan", "models.Kecamatan"),
						Kabupaten: struct {
							field.RelationField
							Province struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}
							Kecamatan struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten", "models.Kabupaten"),
							Province: struct {
								field.RelationField
								Kabupaten struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Province", "models.Province"),
								Kabupaten: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Province.Kabupaten", "models.Kabupaten"),
								},
							},
							Kecamatan: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kabupaten.Kecamatan", "models.Kecamatan"),
							},
						},
						Kelurahan: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Kecamatan.Kelurahan", "models.Kelurahan"),
						},
					},
					Locations: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Contract.Customer.Location.Kelurahan.Locations", "models.Location"),
					},
				},
			},
			LeasingContracts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.Customer.LeasingContracts", "models.LeasingContract"),
			},
		},
		Motor: struct {
			field.RelationField
			MotorTypeRef struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}
			MotorAssets struct {
				field.RelationField
				Motor struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Contract.Motor", "models.Motor"),
			MotorTypeRef: struct {
				field.RelationField
				Motors struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.Motor.MotorTypeRef", "models.MotorType"),
				Motors: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.Motor.MotorTypeRef.Motors", "models.Motor"),
				},
			},
			MotorAssets: struct {
				field.RelationField
				Motor struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.Motor.MotorAssets", "models.MotorAsset"),
				Motor: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.Motor.MotorAssets.Motor", "models.Motor"),
				},
			},
		},
		Product: struct {
			field.RelationField
			LeasingContracts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Contract.Product", "models.LeasingProduct"),
			LeasingContracts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.Product.LeasingContracts", "models.LeasingContract"),
			},
		},
		LeasingTasks: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Role struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}
			LeasingAttribute struct {
				field.RelationField
				Task struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Contract.LeasingTasks", "models.LeasingTask"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.LeasingTasks.Contract", "models.LeasingContract"),
			},
			Role: struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("Contract.LeasingTasks.Role", "models.Role"),
				UserRoles: struct {
					field.RelationField
					User struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}
					Role struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles", "models.UserRole"),
					User: struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}
						UserRoles struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User", "models.User"),
						UserOAuthProviders: struct {
							field.RelationField
							User struct {
								field.RelationField
							}
							Provider struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}
						}{
							RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders", "models.UserOAuthProvider"),
							User: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.User", "models.User"),
							},
							Provider: struct {
								field.RelationField
								UserOAuthProviders struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.Provider", "models.OAuthProvider"),
								UserOAuthProviders: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserOAuthProviders.Provider.UserOAuthProviders", "models.UserOAuthProvider"),
								},
							},
						},
						UserRoles: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.User.UserRoles", "models.UserRole"),
						},
					},
					Role: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.UserRoles.Role", "models.Role"),
					},
				},
				RolePermissions: struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions", "models.RolePermission"),
					Role: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions.Role", "models.Role"),
					},
					Permission: struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions.Permission", "models.Permission"),
						RolePermissions: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Contract.LeasingTasks.Role.RolePermissions.Permission.RolePermissions", "models.RolePermission"),
						},
					},
				},
			},
			LeasingAttribute: struct {
				field.RelationField
				Task struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.LeasingTasks.LeasingAttribute", "models.LeasingTaskAttribute"),
				Task: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.LeasingTasks.LeasingAttribute.Task", "models.LeasingTask"),
				},
			},
		},
		PaymentSchedules: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Payments struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Schedule struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Contract.PaymentSchedules", "models.PaymentSchedule"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.PaymentSchedules.Contract", "models.LeasingContract"),
			},
			Payments: struct {
				field.RelationField
				Contract struct {
					field.RelationField
				}
				Schedule struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Contract.PaymentSchedules.Payments", "models.Payment"),
				Contract: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.PaymentSchedules.Payments.Contract", "models.LeasingContract"),
				},
				Schedule: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Contract.PaymentSchedules.Payments.Schedule", "models.PaymentSchedule"),
				},
			},
		},
		Payments: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Contract.Payments", "models.Payment"),
		},
		ContractDocuments: struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Contract.ContractDocuments", "models.LeasingContractDocument"),
			Contract: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Contract.ContractDocuments.Contract", "models.LeasingContract"),
			},
		},
	}

	_payment.Schedule = paymentHasOneSchedule{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Schedule", "models.PaymentSchedule"),
	}

	_payment.fillFieldMap()

	return _payment
}

type payment struct {
	paymentDo

	ALL              field.Asterisk
	PaymentID        field.Int64
	NomorBukti       field.String
	JumlahBayar      field.Float64
	TanggalBayar     field.Time
	MetodePembayaran field.String
	Provider         field.String
	CreatedAt        field.Time
	ContractID       field.Int64
	ScheduleID       field.Int64
	Contract         paymentHasOneContract

	Schedule paymentHasOneSchedule

	fieldMap map[string]field.Expr
}

func (p payment) Table(newTableName string) *payment {
	p.paymentDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p payment) As(alias string) *payment {
	p.paymentDo.DO = *(p.paymentDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *payment) updateTableName(table string) *payment {
	p.ALL = field.NewAsterisk(table)
	p.PaymentID = field.NewInt64(table, "payment_id")
	p.NomorBukti = field.NewString(table, "nomor_bukti")
	p.JumlahBayar = field.NewFloat64(table, "jumlah_bayar")
	p.TanggalBayar = field.NewTime(table, "tanggal_bayar")
	p.MetodePembayaran = field.NewString(table, "metode_pembayaran")
	p.Provider = field.NewString(table, "provider")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.ContractID = field.NewInt64(table, "contract_id")
	p.ScheduleID = field.NewInt64(table, "schedule_id")

	p.fillFieldMap()

	return p
}

func (p *payment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *payment) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 11)
	p.fieldMap["payment_id"] = p.PaymentID
	p.fieldMap["nomor_bukti"] = p.NomorBukti
	p.fieldMap["jumlah_bayar"] = p.JumlahBayar
	p.fieldMap["tanggal_bayar"] = p.TanggalBayar
	p.fieldMap["metode_pembayaran"] = p.MetodePembayaran
	p.fieldMap["provider"] = p.Provider
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["contract_id"] = p.ContractID
	p.fieldMap["schedule_id"] = p.ScheduleID

}

func (p payment) clone(db *gorm.DB) payment {
	p.paymentDo.ReplaceConnPool(db.Statement.ConnPool)
	p.Contract.db = db.Session(&gorm.Session{Initialized: true})
	p.Contract.db.Statement.ConnPool = db.Statement.ConnPool
	p.Schedule.db = db.Session(&gorm.Session{Initialized: true})
	p.Schedule.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p payment) replaceDB(db *gorm.DB) payment {
	p.paymentDo.ReplaceDB(db)
	p.Contract.db = db.Session(&gorm.Session{})
	p.Schedule.db = db.Session(&gorm.Session{})
	return p
}

type paymentHasOneContract struct {
	db *gorm.DB

	field.RelationField

	Customer struct {
		field.RelationField
		Location struct {
			field.RelationField
			Kelurahan struct {
				field.RelationField
				Kecamatan struct {
					field.RelationField
					Kabupaten struct {
						field.RelationField
						Province struct {
							field.RelationField
							Kabupaten struct {
								field.RelationField
							}
						}
						Kecamatan struct {
							field.RelationField
						}
					}
					Kelurahan struct {
						field.RelationField
					}
				}
				Locations struct {
					field.RelationField
				}
			}
		}
		LeasingContracts struct {
			field.RelationField
		}
	}
	Motor struct {
		field.RelationField
		MotorTypeRef struct {
			field.RelationField
			Motors struct {
				field.RelationField
			}
		}
		MotorAssets struct {
			field.RelationField
			Motor struct {
				field.RelationField
			}
		}
	}
	Product struct {
		field.RelationField
		LeasingContracts struct {
			field.RelationField
		}
	}
	LeasingTasks struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
		Role struct {
			field.RelationField
			UserRoles struct {
				field.RelationField
				User struct {
					field.RelationField
					UserOAuthProviders struct {
						field.RelationField
						User struct {
							field.RelationField
						}
						Provider struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}
					}
					UserRoles struct {
						field.RelationField
					}
				}
				Role struct {
					field.RelationField
				}
			}
			RolePermissions struct {
				field.RelationField
				Role struct {
					field.RelationField
				}
				Permission struct {
					field.RelationField
					RolePermissions struct {
						field.RelationField
					}
				}
			}
		}
		LeasingAttribute struct {
			field.RelationField
			Task struct {
				field.RelationField
			}
		}
	}
	PaymentSchedules struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
		Payments struct {
			field.RelationField
			Contract struct {
				field.RelationField
			}
			Schedule struct {
				field.RelationField
			}
		}
	}
	Payments struct {
		field.RelationField
	}
	ContractDocuments struct {
		field.RelationField
		Contract struct {
			field.RelationField
		}
	}
}

func (a paymentHasOneContract) Where(conds ...field.Expr) *paymentHasOneContract {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a paymentHasOneContract) WithContext(ctx context.Context) *paymentHasOneContract {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a paymentHasOneContract) Session(session *gorm.Session) *paymentHasOneContract {
	a.db = a.db.Session(session)
	return &a
}

func (a paymentHasOneContract) Model(m *models.Payment) *paymentHasOneContractTx {
	return &paymentHasOneContractTx{a.db.Model(m).Association(a.Name())}
}

func (a paymentHasOneContract) Unscoped() *paymentHasOneContract {
	a.db = a.db.Unscoped()
	return &a
}

type paymentHasOneContractTx struct{ tx *gorm.Association }

func (a paymentHasOneContractTx) Find() (result *models.LeasingContract, err error) {
	return result, a.tx.Find(&result)
}

func (a paymentHasOneContractTx) Append(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a paymentHasOneContractTx) Replace(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a paymentHasOneContractTx) Delete(values ...*models.LeasingContract) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a paymentHasOneContractTx) Clear() error {
	return a.tx.Clear()
}

func (a paymentHasOneContractTx) Count() int64 {
	return a.tx.Count()
}

func (a paymentHasOneContractTx) Unscoped() *paymentHasOneContractTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type paymentHasOneSchedule struct {
	db *gorm.DB

	field.RelationField
}

func (a paymentHasOneSchedule) Where(conds ...field.Expr) *paymentHasOneSchedule {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a paymentHasOneSchedule) WithContext(ctx context.Context) *paymentHasOneSchedule {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a paymentHasOneSchedule) Session(session *gorm.Session) *paymentHasOneSchedule {
	a.db = a.db.Session(session)
	return &a
}

func (a paymentHasOneSchedule) Model(m *models.Payment) *paymentHasOneScheduleTx {
	return &paymentHasOneScheduleTx{a.db.Model(m).Association(a.Name())}
}

func (a paymentHasOneSchedule) Unscoped() *paymentHasOneSchedule {
	a.db = a.db.Unscoped()
	return &a
}

type paymentHasOneScheduleTx struct{ tx *gorm.Association }

func (a paymentHasOneScheduleTx) Find() (result *models.PaymentSchedule, err error) {
	return result, a.tx.Find(&result)
}

func (a paymentHasOneScheduleTx) Append(values ...*models.PaymentSchedule) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a paymentHasOneScheduleTx) Replace(values ...*models.PaymentSchedule) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a paymentHasOneScheduleTx) Delete(values ...*models.PaymentSchedule) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a paymentHasOneScheduleTx) Clear() error {
	return a.tx.Clear()
}

func (a paymentHasOneScheduleTx) Count() int64 {
	return a.tx.Count()
}

func (a paymentHasOneScheduleTx) Unscoped() *paymentHasOneScheduleTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type paymentDo struct{ gen.DO }

type IPaymentDo interface {
	gen.SubQuery
	Debug() IPaymentDo
	WithContext(ctx context.Context) IPaymentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPaymentDo
	WriteDB() IPaymentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPaymentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPaymentDo
	Not(conds ...gen.Condition) IPaymentDo
	Or(conds ...gen.Condition) IPaymentDo
	Select(conds ...field.Expr) IPaymentDo
	Where(conds ...gen.Condition) IPaymentDo
	Order(conds ...field.Expr) IPaymentDo
	Distinct(cols ...field.Expr) IPaymentDo
	Omit(cols ...field.Expr) IPaymentDo
	Join(table schema.Tabler, on ...field.Expr) IPaymentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPaymentDo
	Group(cols ...field.Expr) IPaymentDo
	Having(conds ...gen.Condition) IPaymentDo
	Limit(limit int) IPaymentDo
	Offset(offset int) IPaymentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentDo
	Unscoped() IPaymentDo
	Create(values ...*models.Payment) error
	CreateInBatches(values []*models.Payment, batchSize int) error
	Save(values ...*models.Payment) error
	First() (*models.Payment, error)
	Take() (*models.Payment, error)
	Last() (*models.Payment, error)
	Find() ([]*models.Payment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Payment, err error)
	FindInBatches(result *[]*models.Payment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Payment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPaymentDo
	Assign(attrs ...field.AssignExpr) IPaymentDo
	Joins(fields ...field.RelationField) IPaymentDo
	Preload(fields ...field.RelationField) IPaymentDo
	FirstOrInit() (*models.Payment, error)
	FirstOrCreate() (*models.Payment, error)
	FindByPage(offset int, limit int) (result []*models.Payment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPaymentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p paymentDo) Debug() IPaymentDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentDo) WithContext(ctx context.Context) IPaymentDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentDo) ReadDB() IPaymentDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentDo) WriteDB() IPaymentDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentDo) Session(config *gorm.Session) IPaymentDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentDo) Clauses(conds ...clause.Expression) IPaymentDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentDo) Returning(value interface{}, columns ...string) IPaymentDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentDo) Not(conds ...gen.Condition) IPaymentDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentDo) Or(conds ...gen.Condition) IPaymentDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentDo) Select(conds ...field.Expr) IPaymentDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentDo) Where(conds ...gen.Condition) IPaymentDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentDo) Order(conds ...field.Expr) IPaymentDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentDo) Distinct(cols ...field.Expr) IPaymentDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentDo) Omit(cols ...field.Expr) IPaymentDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentDo) Join(table schema.Tabler, on ...field.Expr) IPaymentDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentDo) RightJoin(table schema.Tabler, on ...field.Expr) IPaymentDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentDo) Group(cols ...field.Expr) IPaymentDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentDo) Having(conds ...gen.Condition) IPaymentDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentDo) Limit(limit int) IPaymentDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentDo) Offset(offset int) IPaymentDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentDo) Unscoped() IPaymentDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentDo) Create(values ...*models.Payment) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentDo) CreateInBatches(values []*models.Payment, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentDo) Save(values ...*models.Payment) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentDo) First() (*models.Payment, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Payment), nil
	}
}

func (p paymentDo) Take() (*models.Payment, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Payment), nil
	}
}

func (p paymentDo) Last() (*models.Payment, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Payment), nil
	}
}

func (p paymentDo) Find() ([]*models.Payment, error) {
	result, err := p.DO.Find()
	return result.([]*models.Payment), err
}

func (p paymentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Payment, err error) {
	buf := make([]*models.Payment, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentDo) FindInBatches(result *[]*models.Payment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentDo) Attrs(attrs ...field.AssignExpr) IPaymentDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentDo) Assign(attrs ...field.AssignExpr) IPaymentDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentDo) Joins(fields ...field.RelationField) IPaymentDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentDo) Preload(fields ...field.RelationField) IPaymentDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentDo) FirstOrInit() (*models.Payment, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Payment), nil
	}
}

func (p paymentDo) FirstOrCreate() (*models.Payment, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Payment), nil
	}
}

func (p paymentDo) FindByPage(offset int, limit int) (result []*models.Payment, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentDo) Delete(models ...*models.Payment) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentDo) withDO(do gen.Dao) *paymentDo {
	p.DO = *do.(*gen.DO)
	return p
}
