// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HendraaaIrwn/honda-leasing-api/internal/domain/models"
)

func newProvince(db *gorm.DB, opts ...gen.DOOption) province {
	_province := province{}

	_province.provinceDo.UseDB(db, opts...)
	_province.provinceDo.UseModel(&models.Province{})

	tableName := _province.provinceDo.TableName()
	_province.ALL = field.NewAsterisk(tableName)
	_province.ProvID = field.NewInt64(tableName, "prov_id")
	_province.ProvName = field.NewString(tableName, "prov_name")
	_province.Kabupaten = provinceHasManyKabupaten{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Kabupaten", "models.Kabupaten"),
		Province: struct {
			field.RelationField
			Kabupaten struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Kabupaten.Province", "models.Province"),
			Kabupaten: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Kabupaten.Province.Kabupaten", "models.Kabupaten"),
			},
		},
		Kecamatan: struct {
			field.RelationField
			Kabupaten struct {
				field.RelationField
			}
			Kelurahan struct {
				field.RelationField
				Kecamatan struct {
					field.RelationField
				}
				Locations struct {
					field.RelationField
					Kelurahan struct {
						field.RelationField
					}
				}
			}
		}{
			RelationField: field.NewRelation("Kabupaten.Kecamatan", "models.Kecamatan"),
			Kabupaten: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Kabupaten.Kecamatan.Kabupaten", "models.Kabupaten"),
			},
			Kelurahan: struct {
				field.RelationField
				Kecamatan struct {
					field.RelationField
				}
				Locations struct {
					field.RelationField
					Kelurahan struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Kabupaten.Kecamatan.Kelurahan", "models.Kelurahan"),
				Kecamatan: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Kabupaten.Kecamatan.Kelurahan.Kecamatan", "models.Kecamatan"),
				},
				Locations: struct {
					field.RelationField
					Kelurahan struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Kabupaten.Kecamatan.Kelurahan.Locations", "models.Location"),
					Kelurahan: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Kabupaten.Kecamatan.Kelurahan.Locations.Kelurahan", "models.Kelurahan"),
					},
				},
			},
		},
	}

	_province.fillFieldMap()

	return _province
}

type province struct {
	provinceDo

	ALL       field.Asterisk
	ProvID    field.Int64
	ProvName  field.String
	Kabupaten provinceHasManyKabupaten

	fieldMap map[string]field.Expr
}

func (p province) Table(newTableName string) *province {
	p.provinceDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p province) As(alias string) *province {
	p.provinceDo.DO = *(p.provinceDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *province) updateTableName(table string) *province {
	p.ALL = field.NewAsterisk(table)
	p.ProvID = field.NewInt64(table, "prov_id")
	p.ProvName = field.NewString(table, "prov_name")

	p.fillFieldMap()

	return p
}

func (p *province) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *province) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["prov_id"] = p.ProvID
	p.fieldMap["prov_name"] = p.ProvName

}

func (p province) clone(db *gorm.DB) province {
	p.provinceDo.ReplaceConnPool(db.Statement.ConnPool)
	p.Kabupaten.db = db.Session(&gorm.Session{Initialized: true})
	p.Kabupaten.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p province) replaceDB(db *gorm.DB) province {
	p.provinceDo.ReplaceDB(db)
	p.Kabupaten.db = db.Session(&gorm.Session{})
	return p
}

type provinceHasManyKabupaten struct {
	db *gorm.DB

	field.RelationField

	Province struct {
		field.RelationField
		Kabupaten struct {
			field.RelationField
		}
	}
	Kecamatan struct {
		field.RelationField
		Kabupaten struct {
			field.RelationField
		}
		Kelurahan struct {
			field.RelationField
			Kecamatan struct {
				field.RelationField
			}
			Locations struct {
				field.RelationField
				Kelurahan struct {
					field.RelationField
				}
			}
		}
	}
}

func (a provinceHasManyKabupaten) Where(conds ...field.Expr) *provinceHasManyKabupaten {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a provinceHasManyKabupaten) WithContext(ctx context.Context) *provinceHasManyKabupaten {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a provinceHasManyKabupaten) Session(session *gorm.Session) *provinceHasManyKabupaten {
	a.db = a.db.Session(session)
	return &a
}

func (a provinceHasManyKabupaten) Model(m *models.Province) *provinceHasManyKabupatenTx {
	return &provinceHasManyKabupatenTx{a.db.Model(m).Association(a.Name())}
}

func (a provinceHasManyKabupaten) Unscoped() *provinceHasManyKabupaten {
	a.db = a.db.Unscoped()
	return &a
}

type provinceHasManyKabupatenTx struct{ tx *gorm.Association }

func (a provinceHasManyKabupatenTx) Find() (result []*models.Kabupaten, err error) {
	return result, a.tx.Find(&result)
}

func (a provinceHasManyKabupatenTx) Append(values ...*models.Kabupaten) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a provinceHasManyKabupatenTx) Replace(values ...*models.Kabupaten) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a provinceHasManyKabupatenTx) Delete(values ...*models.Kabupaten) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a provinceHasManyKabupatenTx) Clear() error {
	return a.tx.Clear()
}

func (a provinceHasManyKabupatenTx) Count() int64 {
	return a.tx.Count()
}

func (a provinceHasManyKabupatenTx) Unscoped() *provinceHasManyKabupatenTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type provinceDo struct{ gen.DO }

type IProvinceDo interface {
	gen.SubQuery
	Debug() IProvinceDo
	WithContext(ctx context.Context) IProvinceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProvinceDo
	WriteDB() IProvinceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProvinceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProvinceDo
	Not(conds ...gen.Condition) IProvinceDo
	Or(conds ...gen.Condition) IProvinceDo
	Select(conds ...field.Expr) IProvinceDo
	Where(conds ...gen.Condition) IProvinceDo
	Order(conds ...field.Expr) IProvinceDo
	Distinct(cols ...field.Expr) IProvinceDo
	Omit(cols ...field.Expr) IProvinceDo
	Join(table schema.Tabler, on ...field.Expr) IProvinceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProvinceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProvinceDo
	Group(cols ...field.Expr) IProvinceDo
	Having(conds ...gen.Condition) IProvinceDo
	Limit(limit int) IProvinceDo
	Offset(offset int) IProvinceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProvinceDo
	Unscoped() IProvinceDo
	Create(values ...*models.Province) error
	CreateInBatches(values []*models.Province, batchSize int) error
	Save(values ...*models.Province) error
	First() (*models.Province, error)
	Take() (*models.Province, error)
	Last() (*models.Province, error)
	Find() ([]*models.Province, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Province, err error)
	FindInBatches(result *[]*models.Province, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Province) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProvinceDo
	Assign(attrs ...field.AssignExpr) IProvinceDo
	Joins(fields ...field.RelationField) IProvinceDo
	Preload(fields ...field.RelationField) IProvinceDo
	FirstOrInit() (*models.Province, error)
	FirstOrCreate() (*models.Province, error)
	FindByPage(offset int, limit int) (result []*models.Province, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProvinceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p provinceDo) Debug() IProvinceDo {
	return p.withDO(p.DO.Debug())
}

func (p provinceDo) WithContext(ctx context.Context) IProvinceDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p provinceDo) ReadDB() IProvinceDo {
	return p.Clauses(dbresolver.Read)
}

func (p provinceDo) WriteDB() IProvinceDo {
	return p.Clauses(dbresolver.Write)
}

func (p provinceDo) Session(config *gorm.Session) IProvinceDo {
	return p.withDO(p.DO.Session(config))
}

func (p provinceDo) Clauses(conds ...clause.Expression) IProvinceDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p provinceDo) Returning(value interface{}, columns ...string) IProvinceDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p provinceDo) Not(conds ...gen.Condition) IProvinceDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p provinceDo) Or(conds ...gen.Condition) IProvinceDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p provinceDo) Select(conds ...field.Expr) IProvinceDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p provinceDo) Where(conds ...gen.Condition) IProvinceDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p provinceDo) Order(conds ...field.Expr) IProvinceDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p provinceDo) Distinct(cols ...field.Expr) IProvinceDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p provinceDo) Omit(cols ...field.Expr) IProvinceDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p provinceDo) Join(table schema.Tabler, on ...field.Expr) IProvinceDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p provinceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProvinceDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p provinceDo) RightJoin(table schema.Tabler, on ...field.Expr) IProvinceDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p provinceDo) Group(cols ...field.Expr) IProvinceDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p provinceDo) Having(conds ...gen.Condition) IProvinceDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p provinceDo) Limit(limit int) IProvinceDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p provinceDo) Offset(offset int) IProvinceDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p provinceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProvinceDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p provinceDo) Unscoped() IProvinceDo {
	return p.withDO(p.DO.Unscoped())
}

func (p provinceDo) Create(values ...*models.Province) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p provinceDo) CreateInBatches(values []*models.Province, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p provinceDo) Save(values ...*models.Province) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p provinceDo) First() (*models.Province, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Province), nil
	}
}

func (p provinceDo) Take() (*models.Province, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Province), nil
	}
}

func (p provinceDo) Last() (*models.Province, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Province), nil
	}
}

func (p provinceDo) Find() ([]*models.Province, error) {
	result, err := p.DO.Find()
	return result.([]*models.Province), err
}

func (p provinceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Province, err error) {
	buf := make([]*models.Province, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p provinceDo) FindInBatches(result *[]*models.Province, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p provinceDo) Attrs(attrs ...field.AssignExpr) IProvinceDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p provinceDo) Assign(attrs ...field.AssignExpr) IProvinceDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p provinceDo) Joins(fields ...field.RelationField) IProvinceDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p provinceDo) Preload(fields ...field.RelationField) IProvinceDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p provinceDo) FirstOrInit() (*models.Province, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Province), nil
	}
}

func (p provinceDo) FirstOrCreate() (*models.Province, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Province), nil
	}
}

func (p provinceDo) FindByPage(offset int, limit int) (result []*models.Province, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p provinceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p provinceDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p provinceDo) Delete(models ...*models.Province) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *provinceDo) withDO(do gen.Dao) *provinceDo {
	p.DO = *do.(*gen.DO)
	return p
}
