// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HendraaaIrwn/honda-leasing-api/internal/domain/models"
)

func newTemplateTaskAttribute(db *gorm.DB, opts ...gen.DOOption) templateTaskAttribute {
	_templateTaskAttribute := templateTaskAttribute{}

	_templateTaskAttribute.templateTaskAttributeDo.UseDB(db, opts...)
	_templateTaskAttribute.templateTaskAttributeDo.UseModel(&models.TemplateTaskAttribute{})

	tableName := _templateTaskAttribute.templateTaskAttributeDo.TableName()
	_templateTaskAttribute.ALL = field.NewAsterisk(tableName)
	_templateTaskAttribute.TetatID = field.NewInt64(tableName, "tetat_id")
	_templateTaskAttribute.TetatName = field.NewString(tableName, "tetat_name")
	_templateTaskAttribute.TetatTetaID = field.NewInt64(tableName, "tetat_teta_id")
	_templateTaskAttribute.TemplateTask = templateTaskAttributeBelongsToTemplateTask{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("TemplateTask", "models.TemplateTask"),
		Role: struct {
			field.RelationField
			UserRoles struct {
				field.RelationField
				User struct {
					field.RelationField
					UserOAuthProviders struct {
						field.RelationField
						User struct {
							field.RelationField
						}
						Provider struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}
					}
					UserRoles struct {
						field.RelationField
					}
				}
				Role struct {
					field.RelationField
				}
			}
			RolePermissions struct {
				field.RelationField
				Role struct {
					field.RelationField
				}
				Permission struct {
					field.RelationField
					RolePermissions struct {
						field.RelationField
					}
				}
			}
		}{
			RelationField: field.NewRelation("TemplateTask.Role", "models.Role"),
			UserRoles: struct {
				field.RelationField
				User struct {
					field.RelationField
					UserOAuthProviders struct {
						field.RelationField
						User struct {
							field.RelationField
						}
						Provider struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}
					}
					UserRoles struct {
						field.RelationField
					}
				}
				Role struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("TemplateTask.Role.UserRoles", "models.UserRole"),
				User: struct {
					field.RelationField
					UserOAuthProviders struct {
						field.RelationField
						User struct {
							field.RelationField
						}
						Provider struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}
					}
					UserRoles struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("TemplateTask.Role.UserRoles.User", "models.User"),
					UserOAuthProviders: struct {
						field.RelationField
						User struct {
							field.RelationField
						}
						Provider struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}
					}{
						RelationField: field.NewRelation("TemplateTask.Role.UserRoles.User.UserOAuthProviders", "models.UserOAuthProvider"),
						User: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("TemplateTask.Role.UserRoles.User.UserOAuthProviders.User", "models.User"),
						},
						Provider: struct {
							field.RelationField
							UserOAuthProviders struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("TemplateTask.Role.UserRoles.User.UserOAuthProviders.Provider", "models.OAuthProvider"),
							UserOAuthProviders: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("TemplateTask.Role.UserRoles.User.UserOAuthProviders.Provider.UserOAuthProviders", "models.UserOAuthProvider"),
							},
						},
					},
					UserRoles: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("TemplateTask.Role.UserRoles.User.UserRoles", "models.UserRole"),
					},
				},
				Role: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("TemplateTask.Role.UserRoles.Role", "models.Role"),
				},
			},
			RolePermissions: struct {
				field.RelationField
				Role struct {
					field.RelationField
				}
				Permission struct {
					field.RelationField
					RolePermissions struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("TemplateTask.Role.RolePermissions", "models.RolePermission"),
				Role: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("TemplateTask.Role.RolePermissions.Role", "models.Role"),
				},
				Permission: struct {
					field.RelationField
					RolePermissions struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("TemplateTask.Role.RolePermissions.Permission", "models.Permission"),
					RolePermissions: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("TemplateTask.Role.RolePermissions.Permission.RolePermissions", "models.RolePermission"),
					},
				},
			},
		},
		Attributes: struct {
			field.RelationField
			TemplateTask struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("TemplateTask.Attributes", "models.TemplateTaskAttribute"),
			TemplateTask: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("TemplateTask.Attributes.TemplateTask", "models.TemplateTask"),
			},
		},
	}

	_templateTaskAttribute.fillFieldMap()

	return _templateTaskAttribute
}

type templateTaskAttribute struct {
	templateTaskAttributeDo

	ALL          field.Asterisk
	TetatID      field.Int64
	TetatName    field.String
	TetatTetaID  field.Int64
	TemplateTask templateTaskAttributeBelongsToTemplateTask

	fieldMap map[string]field.Expr
}

func (t templateTaskAttribute) Table(newTableName string) *templateTaskAttribute {
	t.templateTaskAttributeDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t templateTaskAttribute) As(alias string) *templateTaskAttribute {
	t.templateTaskAttributeDo.DO = *(t.templateTaskAttributeDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *templateTaskAttribute) updateTableName(table string) *templateTaskAttribute {
	t.ALL = field.NewAsterisk(table)
	t.TetatID = field.NewInt64(table, "tetat_id")
	t.TetatName = field.NewString(table, "tetat_name")
	t.TetatTetaID = field.NewInt64(table, "tetat_teta_id")

	t.fillFieldMap()

	return t
}

func (t *templateTaskAttribute) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *templateTaskAttribute) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 4)
	t.fieldMap["tetat_id"] = t.TetatID
	t.fieldMap["tetat_name"] = t.TetatName
	t.fieldMap["tetat_teta_id"] = t.TetatTetaID

}

func (t templateTaskAttribute) clone(db *gorm.DB) templateTaskAttribute {
	t.templateTaskAttributeDo.ReplaceConnPool(db.Statement.ConnPool)
	t.TemplateTask.db = db.Session(&gorm.Session{Initialized: true})
	t.TemplateTask.db.Statement.ConnPool = db.Statement.ConnPool
	return t
}

func (t templateTaskAttribute) replaceDB(db *gorm.DB) templateTaskAttribute {
	t.templateTaskAttributeDo.ReplaceDB(db)
	t.TemplateTask.db = db.Session(&gorm.Session{})
	return t
}

type templateTaskAttributeBelongsToTemplateTask struct {
	db *gorm.DB

	field.RelationField

	Role struct {
		field.RelationField
		UserRoles struct {
			field.RelationField
			User struct {
				field.RelationField
				UserOAuthProviders struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					Provider struct {
						field.RelationField
						UserOAuthProviders struct {
							field.RelationField
						}
					}
				}
				UserRoles struct {
					field.RelationField
				}
			}
			Role struct {
				field.RelationField
			}
		}
		RolePermissions struct {
			field.RelationField
			Role struct {
				field.RelationField
			}
			Permission struct {
				field.RelationField
				RolePermissions struct {
					field.RelationField
				}
			}
		}
	}
	Attributes struct {
		field.RelationField
		TemplateTask struct {
			field.RelationField
		}
	}
}

func (a templateTaskAttributeBelongsToTemplateTask) Where(conds ...field.Expr) *templateTaskAttributeBelongsToTemplateTask {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a templateTaskAttributeBelongsToTemplateTask) WithContext(ctx context.Context) *templateTaskAttributeBelongsToTemplateTask {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a templateTaskAttributeBelongsToTemplateTask) Session(session *gorm.Session) *templateTaskAttributeBelongsToTemplateTask {
	a.db = a.db.Session(session)
	return &a
}

func (a templateTaskAttributeBelongsToTemplateTask) Model(m *models.TemplateTaskAttribute) *templateTaskAttributeBelongsToTemplateTaskTx {
	return &templateTaskAttributeBelongsToTemplateTaskTx{a.db.Model(m).Association(a.Name())}
}

func (a templateTaskAttributeBelongsToTemplateTask) Unscoped() *templateTaskAttributeBelongsToTemplateTask {
	a.db = a.db.Unscoped()
	return &a
}

type templateTaskAttributeBelongsToTemplateTaskTx struct{ tx *gorm.Association }

func (a templateTaskAttributeBelongsToTemplateTaskTx) Find() (result *models.TemplateTask, err error) {
	return result, a.tx.Find(&result)
}

func (a templateTaskAttributeBelongsToTemplateTaskTx) Append(values ...*models.TemplateTask) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a templateTaskAttributeBelongsToTemplateTaskTx) Replace(values ...*models.TemplateTask) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a templateTaskAttributeBelongsToTemplateTaskTx) Delete(values ...*models.TemplateTask) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a templateTaskAttributeBelongsToTemplateTaskTx) Clear() error {
	return a.tx.Clear()
}

func (a templateTaskAttributeBelongsToTemplateTaskTx) Count() int64 {
	return a.tx.Count()
}

func (a templateTaskAttributeBelongsToTemplateTaskTx) Unscoped() *templateTaskAttributeBelongsToTemplateTaskTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type templateTaskAttributeDo struct{ gen.DO }

type ITemplateTaskAttributeDo interface {
	gen.SubQuery
	Debug() ITemplateTaskAttributeDo
	WithContext(ctx context.Context) ITemplateTaskAttributeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITemplateTaskAttributeDo
	WriteDB() ITemplateTaskAttributeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITemplateTaskAttributeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITemplateTaskAttributeDo
	Not(conds ...gen.Condition) ITemplateTaskAttributeDo
	Or(conds ...gen.Condition) ITemplateTaskAttributeDo
	Select(conds ...field.Expr) ITemplateTaskAttributeDo
	Where(conds ...gen.Condition) ITemplateTaskAttributeDo
	Order(conds ...field.Expr) ITemplateTaskAttributeDo
	Distinct(cols ...field.Expr) ITemplateTaskAttributeDo
	Omit(cols ...field.Expr) ITemplateTaskAttributeDo
	Join(table schema.Tabler, on ...field.Expr) ITemplateTaskAttributeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITemplateTaskAttributeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITemplateTaskAttributeDo
	Group(cols ...field.Expr) ITemplateTaskAttributeDo
	Having(conds ...gen.Condition) ITemplateTaskAttributeDo
	Limit(limit int) ITemplateTaskAttributeDo
	Offset(offset int) ITemplateTaskAttributeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITemplateTaskAttributeDo
	Unscoped() ITemplateTaskAttributeDo
	Create(values ...*models.TemplateTaskAttribute) error
	CreateInBatches(values []*models.TemplateTaskAttribute, batchSize int) error
	Save(values ...*models.TemplateTaskAttribute) error
	First() (*models.TemplateTaskAttribute, error)
	Take() (*models.TemplateTaskAttribute, error)
	Last() (*models.TemplateTaskAttribute, error)
	Find() ([]*models.TemplateTaskAttribute, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TemplateTaskAttribute, err error)
	FindInBatches(result *[]*models.TemplateTaskAttribute, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.TemplateTaskAttribute) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITemplateTaskAttributeDo
	Assign(attrs ...field.AssignExpr) ITemplateTaskAttributeDo
	Joins(fields ...field.RelationField) ITemplateTaskAttributeDo
	Preload(fields ...field.RelationField) ITemplateTaskAttributeDo
	FirstOrInit() (*models.TemplateTaskAttribute, error)
	FirstOrCreate() (*models.TemplateTaskAttribute, error)
	FindByPage(offset int, limit int) (result []*models.TemplateTaskAttribute, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITemplateTaskAttributeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t templateTaskAttributeDo) Debug() ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Debug())
}

func (t templateTaskAttributeDo) WithContext(ctx context.Context) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t templateTaskAttributeDo) ReadDB() ITemplateTaskAttributeDo {
	return t.Clauses(dbresolver.Read)
}

func (t templateTaskAttributeDo) WriteDB() ITemplateTaskAttributeDo {
	return t.Clauses(dbresolver.Write)
}

func (t templateTaskAttributeDo) Session(config *gorm.Session) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Session(config))
}

func (t templateTaskAttributeDo) Clauses(conds ...clause.Expression) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t templateTaskAttributeDo) Returning(value interface{}, columns ...string) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t templateTaskAttributeDo) Not(conds ...gen.Condition) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t templateTaskAttributeDo) Or(conds ...gen.Condition) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t templateTaskAttributeDo) Select(conds ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t templateTaskAttributeDo) Where(conds ...gen.Condition) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t templateTaskAttributeDo) Order(conds ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t templateTaskAttributeDo) Distinct(cols ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t templateTaskAttributeDo) Omit(cols ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t templateTaskAttributeDo) Join(table schema.Tabler, on ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t templateTaskAttributeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t templateTaskAttributeDo) RightJoin(table schema.Tabler, on ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t templateTaskAttributeDo) Group(cols ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t templateTaskAttributeDo) Having(conds ...gen.Condition) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t templateTaskAttributeDo) Limit(limit int) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t templateTaskAttributeDo) Offset(offset int) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t templateTaskAttributeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t templateTaskAttributeDo) Unscoped() ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Unscoped())
}

func (t templateTaskAttributeDo) Create(values ...*models.TemplateTaskAttribute) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t templateTaskAttributeDo) CreateInBatches(values []*models.TemplateTaskAttribute, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t templateTaskAttributeDo) Save(values ...*models.TemplateTaskAttribute) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t templateTaskAttributeDo) First() (*models.TemplateTaskAttribute, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.TemplateTaskAttribute), nil
	}
}

func (t templateTaskAttributeDo) Take() (*models.TemplateTaskAttribute, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.TemplateTaskAttribute), nil
	}
}

func (t templateTaskAttributeDo) Last() (*models.TemplateTaskAttribute, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.TemplateTaskAttribute), nil
	}
}

func (t templateTaskAttributeDo) Find() ([]*models.TemplateTaskAttribute, error) {
	result, err := t.DO.Find()
	return result.([]*models.TemplateTaskAttribute), err
}

func (t templateTaskAttributeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TemplateTaskAttribute, err error) {
	buf := make([]*models.TemplateTaskAttribute, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t templateTaskAttributeDo) FindInBatches(result *[]*models.TemplateTaskAttribute, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t templateTaskAttributeDo) Attrs(attrs ...field.AssignExpr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t templateTaskAttributeDo) Assign(attrs ...field.AssignExpr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t templateTaskAttributeDo) Joins(fields ...field.RelationField) ITemplateTaskAttributeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t templateTaskAttributeDo) Preload(fields ...field.RelationField) ITemplateTaskAttributeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t templateTaskAttributeDo) FirstOrInit() (*models.TemplateTaskAttribute, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.TemplateTaskAttribute), nil
	}
}

func (t templateTaskAttributeDo) FirstOrCreate() (*models.TemplateTaskAttribute, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.TemplateTaskAttribute), nil
	}
}

func (t templateTaskAttributeDo) FindByPage(offset int, limit int) (result []*models.TemplateTaskAttribute, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t templateTaskAttributeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t templateTaskAttributeDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t templateTaskAttributeDo) Delete(models ...*models.TemplateTaskAttribute) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *templateTaskAttributeDo) withDO(do gen.Dao) *templateTaskAttributeDo {
	t.DO = *do.(*gen.DO)
	return t
}
