// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HendraaaIrwn/honda-leasing-api/internal/domain/models"
)

func newUserOAuthProvider(db *gorm.DB, opts ...gen.DOOption) userOAuthProvider {
	_userOAuthProvider := userOAuthProvider{}

	_userOAuthProvider.userOAuthProviderDo.UseDB(db, opts...)
	_userOAuthProvider.userOAuthProviderDo.UseModel(&models.UserOAuthProvider{})

	tableName := _userOAuthProvider.userOAuthProviderDo.TableName()
	_userOAuthProvider.ALL = field.NewAsterisk(tableName)
	_userOAuthProvider.UserOAuthID = field.NewInt64(tableName, "user_oauth_id")
	_userOAuthProvider.AccessToken = field.NewString(tableName, "access_token")
	_userOAuthProvider.RefreshToken = field.NewString(tableName, "refresh_token")
	_userOAuthProvider.ExpiresAt = field.NewTime(tableName, "expires_at")
	_userOAuthProvider.CreatedAt = field.NewTime(tableName, "created_at")
	_userOAuthProvider.UserID = field.NewInt64(tableName, "user_id")
	_userOAuthProvider.ProviderID = field.NewInt64(tableName, "provider_id")
	_userOAuthProvider.User = userOAuthProviderHasOneUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "models.User"),
		UserOAuthProviders: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Provider struct {
				field.RelationField
				UserOAuthProviders struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("User.UserOAuthProviders", "models.UserOAuthProvider"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.UserOAuthProviders.User", "models.User"),
			},
			Provider: struct {
				field.RelationField
				UserOAuthProviders struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("User.UserOAuthProviders.Provider", "models.OAuthProvider"),
				UserOAuthProviders: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.UserOAuthProviders.Provider.UserOAuthProviders", "models.UserOAuthProvider"),
				},
			},
		},
		UserRoles: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Role struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}
		}{
			RelationField: field.NewRelation("User.UserRoles", "models.UserRole"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.UserRoles.User", "models.User"),
			},
			Role: struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("User.UserRoles.Role", "models.Role"),
				UserRoles: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.UserRoles.Role.UserRoles", "models.UserRole"),
				},
				RolePermissions: struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("User.UserRoles.Role.RolePermissions", "models.RolePermission"),
					Role: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("User.UserRoles.Role.RolePermissions.Role", "models.Role"),
					},
					Permission: struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("User.UserRoles.Role.RolePermissions.Permission", "models.Permission"),
						RolePermissions: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("User.UserRoles.Role.RolePermissions.Permission.RolePermissions", "models.RolePermission"),
						},
					},
				},
			},
		},
	}

	_userOAuthProvider.Provider = userOAuthProviderHasOneProvider{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Provider", "models.OAuthProvider"),
	}

	_userOAuthProvider.fillFieldMap()

	return _userOAuthProvider
}

type userOAuthProvider struct {
	userOAuthProviderDo

	ALL          field.Asterisk
	UserOAuthID  field.Int64
	AccessToken  field.String
	RefreshToken field.String
	ExpiresAt    field.Time
	CreatedAt    field.Time
	UserID       field.Int64
	ProviderID   field.Int64
	User         userOAuthProviderHasOneUser

	Provider userOAuthProviderHasOneProvider

	fieldMap map[string]field.Expr
}

func (u userOAuthProvider) Table(newTableName string) *userOAuthProvider {
	u.userOAuthProviderDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userOAuthProvider) As(alias string) *userOAuthProvider {
	u.userOAuthProviderDo.DO = *(u.userOAuthProviderDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userOAuthProvider) updateTableName(table string) *userOAuthProvider {
	u.ALL = field.NewAsterisk(table)
	u.UserOAuthID = field.NewInt64(table, "user_oauth_id")
	u.AccessToken = field.NewString(table, "access_token")
	u.RefreshToken = field.NewString(table, "refresh_token")
	u.ExpiresAt = field.NewTime(table, "expires_at")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UserID = field.NewInt64(table, "user_id")
	u.ProviderID = field.NewInt64(table, "provider_id")

	u.fillFieldMap()

	return u
}

func (u *userOAuthProvider) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userOAuthProvider) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 9)
	u.fieldMap["user_oauth_id"] = u.UserOAuthID
	u.fieldMap["access_token"] = u.AccessToken
	u.fieldMap["refresh_token"] = u.RefreshToken
	u.fieldMap["expires_at"] = u.ExpiresAt
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["provider_id"] = u.ProviderID

}

func (u userOAuthProvider) clone(db *gorm.DB) userOAuthProvider {
	u.userOAuthProviderDo.ReplaceConnPool(db.Statement.ConnPool)
	u.User.db = db.Session(&gorm.Session{Initialized: true})
	u.User.db.Statement.ConnPool = db.Statement.ConnPool
	u.Provider.db = db.Session(&gorm.Session{Initialized: true})
	u.Provider.db.Statement.ConnPool = db.Statement.ConnPool
	return u
}

func (u userOAuthProvider) replaceDB(db *gorm.DB) userOAuthProvider {
	u.userOAuthProviderDo.ReplaceDB(db)
	u.User.db = db.Session(&gorm.Session{})
	u.Provider.db = db.Session(&gorm.Session{})
	return u
}

type userOAuthProviderHasOneUser struct {
	db *gorm.DB

	field.RelationField

	UserOAuthProviders struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		Provider struct {
			field.RelationField
			UserOAuthProviders struct {
				field.RelationField
			}
		}
	}
	UserRoles struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		Role struct {
			field.RelationField
			UserRoles struct {
				field.RelationField
			}
			RolePermissions struct {
				field.RelationField
				Role struct {
					field.RelationField
				}
				Permission struct {
					field.RelationField
					RolePermissions struct {
						field.RelationField
					}
				}
			}
		}
	}
}

func (a userOAuthProviderHasOneUser) Where(conds ...field.Expr) *userOAuthProviderHasOneUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userOAuthProviderHasOneUser) WithContext(ctx context.Context) *userOAuthProviderHasOneUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userOAuthProviderHasOneUser) Session(session *gorm.Session) *userOAuthProviderHasOneUser {
	a.db = a.db.Session(session)
	return &a
}

func (a userOAuthProviderHasOneUser) Model(m *models.UserOAuthProvider) *userOAuthProviderHasOneUserTx {
	return &userOAuthProviderHasOneUserTx{a.db.Model(m).Association(a.Name())}
}

func (a userOAuthProviderHasOneUser) Unscoped() *userOAuthProviderHasOneUser {
	a.db = a.db.Unscoped()
	return &a
}

type userOAuthProviderHasOneUserTx struct{ tx *gorm.Association }

func (a userOAuthProviderHasOneUserTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a userOAuthProviderHasOneUserTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userOAuthProviderHasOneUserTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userOAuthProviderHasOneUserTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userOAuthProviderHasOneUserTx) Clear() error {
	return a.tx.Clear()
}

func (a userOAuthProviderHasOneUserTx) Count() int64 {
	return a.tx.Count()
}

func (a userOAuthProviderHasOneUserTx) Unscoped() *userOAuthProviderHasOneUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userOAuthProviderHasOneProvider struct {
	db *gorm.DB

	field.RelationField
}

func (a userOAuthProviderHasOneProvider) Where(conds ...field.Expr) *userOAuthProviderHasOneProvider {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userOAuthProviderHasOneProvider) WithContext(ctx context.Context) *userOAuthProviderHasOneProvider {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userOAuthProviderHasOneProvider) Session(session *gorm.Session) *userOAuthProviderHasOneProvider {
	a.db = a.db.Session(session)
	return &a
}

func (a userOAuthProviderHasOneProvider) Model(m *models.UserOAuthProvider) *userOAuthProviderHasOneProviderTx {
	return &userOAuthProviderHasOneProviderTx{a.db.Model(m).Association(a.Name())}
}

func (a userOAuthProviderHasOneProvider) Unscoped() *userOAuthProviderHasOneProvider {
	a.db = a.db.Unscoped()
	return &a
}

type userOAuthProviderHasOneProviderTx struct{ tx *gorm.Association }

func (a userOAuthProviderHasOneProviderTx) Find() (result *models.OAuthProvider, err error) {
	return result, a.tx.Find(&result)
}

func (a userOAuthProviderHasOneProviderTx) Append(values ...*models.OAuthProvider) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userOAuthProviderHasOneProviderTx) Replace(values ...*models.OAuthProvider) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userOAuthProviderHasOneProviderTx) Delete(values ...*models.OAuthProvider) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userOAuthProviderHasOneProviderTx) Clear() error {
	return a.tx.Clear()
}

func (a userOAuthProviderHasOneProviderTx) Count() int64 {
	return a.tx.Count()
}

func (a userOAuthProviderHasOneProviderTx) Unscoped() *userOAuthProviderHasOneProviderTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userOAuthProviderDo struct{ gen.DO }

type IUserOAuthProviderDo interface {
	gen.SubQuery
	Debug() IUserOAuthProviderDo
	WithContext(ctx context.Context) IUserOAuthProviderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserOAuthProviderDo
	WriteDB() IUserOAuthProviderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserOAuthProviderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserOAuthProviderDo
	Not(conds ...gen.Condition) IUserOAuthProviderDo
	Or(conds ...gen.Condition) IUserOAuthProviderDo
	Select(conds ...field.Expr) IUserOAuthProviderDo
	Where(conds ...gen.Condition) IUserOAuthProviderDo
	Order(conds ...field.Expr) IUserOAuthProviderDo
	Distinct(cols ...field.Expr) IUserOAuthProviderDo
	Omit(cols ...field.Expr) IUserOAuthProviderDo
	Join(table schema.Tabler, on ...field.Expr) IUserOAuthProviderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserOAuthProviderDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserOAuthProviderDo
	Group(cols ...field.Expr) IUserOAuthProviderDo
	Having(conds ...gen.Condition) IUserOAuthProviderDo
	Limit(limit int) IUserOAuthProviderDo
	Offset(offset int) IUserOAuthProviderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserOAuthProviderDo
	Unscoped() IUserOAuthProviderDo
	Create(values ...*models.UserOAuthProvider) error
	CreateInBatches(values []*models.UserOAuthProvider, batchSize int) error
	Save(values ...*models.UserOAuthProvider) error
	First() (*models.UserOAuthProvider, error)
	Take() (*models.UserOAuthProvider, error)
	Last() (*models.UserOAuthProvider, error)
	Find() ([]*models.UserOAuthProvider, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.UserOAuthProvider, err error)
	FindInBatches(result *[]*models.UserOAuthProvider, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.UserOAuthProvider) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserOAuthProviderDo
	Assign(attrs ...field.AssignExpr) IUserOAuthProviderDo
	Joins(fields ...field.RelationField) IUserOAuthProviderDo
	Preload(fields ...field.RelationField) IUserOAuthProviderDo
	FirstOrInit() (*models.UserOAuthProvider, error)
	FirstOrCreate() (*models.UserOAuthProvider, error)
	FindByPage(offset int, limit int) (result []*models.UserOAuthProvider, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserOAuthProviderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userOAuthProviderDo) Debug() IUserOAuthProviderDo {
	return u.withDO(u.DO.Debug())
}

func (u userOAuthProviderDo) WithContext(ctx context.Context) IUserOAuthProviderDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userOAuthProviderDo) ReadDB() IUserOAuthProviderDo {
	return u.Clauses(dbresolver.Read)
}

func (u userOAuthProviderDo) WriteDB() IUserOAuthProviderDo {
	return u.Clauses(dbresolver.Write)
}

func (u userOAuthProviderDo) Session(config *gorm.Session) IUserOAuthProviderDo {
	return u.withDO(u.DO.Session(config))
}

func (u userOAuthProviderDo) Clauses(conds ...clause.Expression) IUserOAuthProviderDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userOAuthProviderDo) Returning(value interface{}, columns ...string) IUserOAuthProviderDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userOAuthProviderDo) Not(conds ...gen.Condition) IUserOAuthProviderDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userOAuthProviderDo) Or(conds ...gen.Condition) IUserOAuthProviderDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userOAuthProviderDo) Select(conds ...field.Expr) IUserOAuthProviderDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userOAuthProviderDo) Where(conds ...gen.Condition) IUserOAuthProviderDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userOAuthProviderDo) Order(conds ...field.Expr) IUserOAuthProviderDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userOAuthProviderDo) Distinct(cols ...field.Expr) IUserOAuthProviderDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userOAuthProviderDo) Omit(cols ...field.Expr) IUserOAuthProviderDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userOAuthProviderDo) Join(table schema.Tabler, on ...field.Expr) IUserOAuthProviderDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userOAuthProviderDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserOAuthProviderDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userOAuthProviderDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserOAuthProviderDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userOAuthProviderDo) Group(cols ...field.Expr) IUserOAuthProviderDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userOAuthProviderDo) Having(conds ...gen.Condition) IUserOAuthProviderDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userOAuthProviderDo) Limit(limit int) IUserOAuthProviderDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userOAuthProviderDo) Offset(offset int) IUserOAuthProviderDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userOAuthProviderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserOAuthProviderDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userOAuthProviderDo) Unscoped() IUserOAuthProviderDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userOAuthProviderDo) Create(values ...*models.UserOAuthProvider) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userOAuthProviderDo) CreateInBatches(values []*models.UserOAuthProvider, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userOAuthProviderDo) Save(values ...*models.UserOAuthProvider) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userOAuthProviderDo) First() (*models.UserOAuthProvider, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserOAuthProvider), nil
	}
}

func (u userOAuthProviderDo) Take() (*models.UserOAuthProvider, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserOAuthProvider), nil
	}
}

func (u userOAuthProviderDo) Last() (*models.UserOAuthProvider, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserOAuthProvider), nil
	}
}

func (u userOAuthProviderDo) Find() ([]*models.UserOAuthProvider, error) {
	result, err := u.DO.Find()
	return result.([]*models.UserOAuthProvider), err
}

func (u userOAuthProviderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.UserOAuthProvider, err error) {
	buf := make([]*models.UserOAuthProvider, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userOAuthProviderDo) FindInBatches(result *[]*models.UserOAuthProvider, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userOAuthProviderDo) Attrs(attrs ...field.AssignExpr) IUserOAuthProviderDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userOAuthProviderDo) Assign(attrs ...field.AssignExpr) IUserOAuthProviderDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userOAuthProviderDo) Joins(fields ...field.RelationField) IUserOAuthProviderDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userOAuthProviderDo) Preload(fields ...field.RelationField) IUserOAuthProviderDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userOAuthProviderDo) FirstOrInit() (*models.UserOAuthProvider, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserOAuthProvider), nil
	}
}

func (u userOAuthProviderDo) FirstOrCreate() (*models.UserOAuthProvider, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserOAuthProvider), nil
	}
}

func (u userOAuthProviderDo) FindByPage(offset int, limit int) (result []*models.UserOAuthProvider, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userOAuthProviderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userOAuthProviderDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userOAuthProviderDo) Delete(models ...*models.UserOAuthProvider) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userOAuthProviderDo) withDO(do gen.Dao) *userOAuthProviderDo {
	u.DO = *do.(*gen.DO)
	return u
}
