// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HendraaaIrwn/honda-leasing-api/internal/domain/models"
)

func newUserRole(db *gorm.DB, opts ...gen.DOOption) userRole {
	_userRole := userRole{}

	_userRole.userRoleDo.UseDB(db, opts...)
	_userRole.userRoleDo.UseModel(&models.UserRole{})

	tableName := _userRole.userRoleDo.TableName()
	_userRole.ALL = field.NewAsterisk(tableName)
	_userRole.UserRoleID = field.NewInt64(tableName, "user_role_id")
	_userRole.AssignedAt = field.NewTime(tableName, "assigned_at")
	_userRole.AssignedBy = field.NewInt64(tableName, "assigned_by")
	_userRole.UserID = field.NewInt64(tableName, "user_id")
	_userRole.RoleID = field.NewInt64(tableName, "role_id")
	_userRole.User = userRoleHasOneUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "models.User"),
		UserOAuthProviders: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Provider struct {
				field.RelationField
				UserOAuthProviders struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("User.UserOAuthProviders", "models.UserOAuthProvider"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.UserOAuthProviders.User", "models.User"),
			},
			Provider: struct {
				field.RelationField
				UserOAuthProviders struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("User.UserOAuthProviders.Provider", "models.OAuthProvider"),
				UserOAuthProviders: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.UserOAuthProviders.Provider.UserOAuthProviders", "models.UserOAuthProvider"),
				},
			},
		},
		UserRoles: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Role struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}
		}{
			RelationField: field.NewRelation("User.UserRoles", "models.UserRole"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.UserRoles.User", "models.User"),
			},
			Role: struct {
				field.RelationField
				UserRoles struct {
					field.RelationField
				}
				RolePermissions struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("User.UserRoles.Role", "models.Role"),
				UserRoles: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.UserRoles.Role.UserRoles", "models.UserRole"),
				},
				RolePermissions: struct {
					field.RelationField
					Role struct {
						field.RelationField
					}
					Permission struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("User.UserRoles.Role.RolePermissions", "models.RolePermission"),
					Role: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("User.UserRoles.Role.RolePermissions.Role", "models.Role"),
					},
					Permission: struct {
						field.RelationField
						RolePermissions struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("User.UserRoles.Role.RolePermissions.Permission", "models.Permission"),
						RolePermissions: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("User.UserRoles.Role.RolePermissions.Permission.RolePermissions", "models.RolePermission"),
						},
					},
				},
			},
		},
	}

	_userRole.Role = userRoleHasOneRole{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Role", "models.Role"),
	}

	_userRole.fillFieldMap()

	return _userRole
}

type userRole struct {
	userRoleDo

	ALL        field.Asterisk
	UserRoleID field.Int64
	AssignedAt field.Time
	AssignedBy field.Int64
	UserID     field.Int64
	RoleID     field.Int64
	User       userRoleHasOneUser

	Role userRoleHasOneRole

	fieldMap map[string]field.Expr
}

func (u userRole) Table(newTableName string) *userRole {
	u.userRoleDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userRole) As(alias string) *userRole {
	u.userRoleDo.DO = *(u.userRoleDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userRole) updateTableName(table string) *userRole {
	u.ALL = field.NewAsterisk(table)
	u.UserRoleID = field.NewInt64(table, "user_role_id")
	u.AssignedAt = field.NewTime(table, "assigned_at")
	u.AssignedBy = field.NewInt64(table, "assigned_by")
	u.UserID = field.NewInt64(table, "user_id")
	u.RoleID = field.NewInt64(table, "role_id")

	u.fillFieldMap()

	return u
}

func (u *userRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userRole) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 7)
	u.fieldMap["user_role_id"] = u.UserRoleID
	u.fieldMap["assigned_at"] = u.AssignedAt
	u.fieldMap["assigned_by"] = u.AssignedBy
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["role_id"] = u.RoleID

}

func (u userRole) clone(db *gorm.DB) userRole {
	u.userRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	u.User.db = db.Session(&gorm.Session{Initialized: true})
	u.User.db.Statement.ConnPool = db.Statement.ConnPool
	u.Role.db = db.Session(&gorm.Session{Initialized: true})
	u.Role.db.Statement.ConnPool = db.Statement.ConnPool
	return u
}

func (u userRole) replaceDB(db *gorm.DB) userRole {
	u.userRoleDo.ReplaceDB(db)
	u.User.db = db.Session(&gorm.Session{})
	u.Role.db = db.Session(&gorm.Session{})
	return u
}

type userRoleHasOneUser struct {
	db *gorm.DB

	field.RelationField

	UserOAuthProviders struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		Provider struct {
			field.RelationField
			UserOAuthProviders struct {
				field.RelationField
			}
		}
	}
	UserRoles struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		Role struct {
			field.RelationField
			UserRoles struct {
				field.RelationField
			}
			RolePermissions struct {
				field.RelationField
				Role struct {
					field.RelationField
				}
				Permission struct {
					field.RelationField
					RolePermissions struct {
						field.RelationField
					}
				}
			}
		}
	}
}

func (a userRoleHasOneUser) Where(conds ...field.Expr) *userRoleHasOneUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userRoleHasOneUser) WithContext(ctx context.Context) *userRoleHasOneUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userRoleHasOneUser) Session(session *gorm.Session) *userRoleHasOneUser {
	a.db = a.db.Session(session)
	return &a
}

func (a userRoleHasOneUser) Model(m *models.UserRole) *userRoleHasOneUserTx {
	return &userRoleHasOneUserTx{a.db.Model(m).Association(a.Name())}
}

func (a userRoleHasOneUser) Unscoped() *userRoleHasOneUser {
	a.db = a.db.Unscoped()
	return &a
}

type userRoleHasOneUserTx struct{ tx *gorm.Association }

func (a userRoleHasOneUserTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a userRoleHasOneUserTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userRoleHasOneUserTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userRoleHasOneUserTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userRoleHasOneUserTx) Clear() error {
	return a.tx.Clear()
}

func (a userRoleHasOneUserTx) Count() int64 {
	return a.tx.Count()
}

func (a userRoleHasOneUserTx) Unscoped() *userRoleHasOneUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userRoleHasOneRole struct {
	db *gorm.DB

	field.RelationField
}

func (a userRoleHasOneRole) Where(conds ...field.Expr) *userRoleHasOneRole {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userRoleHasOneRole) WithContext(ctx context.Context) *userRoleHasOneRole {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userRoleHasOneRole) Session(session *gorm.Session) *userRoleHasOneRole {
	a.db = a.db.Session(session)
	return &a
}

func (a userRoleHasOneRole) Model(m *models.UserRole) *userRoleHasOneRoleTx {
	return &userRoleHasOneRoleTx{a.db.Model(m).Association(a.Name())}
}

func (a userRoleHasOneRole) Unscoped() *userRoleHasOneRole {
	a.db = a.db.Unscoped()
	return &a
}

type userRoleHasOneRoleTx struct{ tx *gorm.Association }

func (a userRoleHasOneRoleTx) Find() (result *models.Role, err error) {
	return result, a.tx.Find(&result)
}

func (a userRoleHasOneRoleTx) Append(values ...*models.Role) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userRoleHasOneRoleTx) Replace(values ...*models.Role) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userRoleHasOneRoleTx) Delete(values ...*models.Role) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userRoleHasOneRoleTx) Clear() error {
	return a.tx.Clear()
}

func (a userRoleHasOneRoleTx) Count() int64 {
	return a.tx.Count()
}

func (a userRoleHasOneRoleTx) Unscoped() *userRoleHasOneRoleTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userRoleDo struct{ gen.DO }

type IUserRoleDo interface {
	gen.SubQuery
	Debug() IUserRoleDo
	WithContext(ctx context.Context) IUserRoleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserRoleDo
	WriteDB() IUserRoleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserRoleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserRoleDo
	Not(conds ...gen.Condition) IUserRoleDo
	Or(conds ...gen.Condition) IUserRoleDo
	Select(conds ...field.Expr) IUserRoleDo
	Where(conds ...gen.Condition) IUserRoleDo
	Order(conds ...field.Expr) IUserRoleDo
	Distinct(cols ...field.Expr) IUserRoleDo
	Omit(cols ...field.Expr) IUserRoleDo
	Join(table schema.Tabler, on ...field.Expr) IUserRoleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserRoleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserRoleDo
	Group(cols ...field.Expr) IUserRoleDo
	Having(conds ...gen.Condition) IUserRoleDo
	Limit(limit int) IUserRoleDo
	Offset(offset int) IUserRoleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserRoleDo
	Unscoped() IUserRoleDo
	Create(values ...*models.UserRole) error
	CreateInBatches(values []*models.UserRole, batchSize int) error
	Save(values ...*models.UserRole) error
	First() (*models.UserRole, error)
	Take() (*models.UserRole, error)
	Last() (*models.UserRole, error)
	Find() ([]*models.UserRole, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.UserRole, err error)
	FindInBatches(result *[]*models.UserRole, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.UserRole) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserRoleDo
	Assign(attrs ...field.AssignExpr) IUserRoleDo
	Joins(fields ...field.RelationField) IUserRoleDo
	Preload(fields ...field.RelationField) IUserRoleDo
	FirstOrInit() (*models.UserRole, error)
	FirstOrCreate() (*models.UserRole, error)
	FindByPage(offset int, limit int) (result []*models.UserRole, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserRoleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userRoleDo) Debug() IUserRoleDo {
	return u.withDO(u.DO.Debug())
}

func (u userRoleDo) WithContext(ctx context.Context) IUserRoleDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userRoleDo) ReadDB() IUserRoleDo {
	return u.Clauses(dbresolver.Read)
}

func (u userRoleDo) WriteDB() IUserRoleDo {
	return u.Clauses(dbresolver.Write)
}

func (u userRoleDo) Session(config *gorm.Session) IUserRoleDo {
	return u.withDO(u.DO.Session(config))
}

func (u userRoleDo) Clauses(conds ...clause.Expression) IUserRoleDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userRoleDo) Returning(value interface{}, columns ...string) IUserRoleDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userRoleDo) Not(conds ...gen.Condition) IUserRoleDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userRoleDo) Or(conds ...gen.Condition) IUserRoleDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userRoleDo) Select(conds ...field.Expr) IUserRoleDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userRoleDo) Where(conds ...gen.Condition) IUserRoleDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userRoleDo) Order(conds ...field.Expr) IUserRoleDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userRoleDo) Distinct(cols ...field.Expr) IUserRoleDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userRoleDo) Omit(cols ...field.Expr) IUserRoleDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userRoleDo) Join(table schema.Tabler, on ...field.Expr) IUserRoleDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserRoleDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserRoleDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userRoleDo) Group(cols ...field.Expr) IUserRoleDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userRoleDo) Having(conds ...gen.Condition) IUserRoleDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userRoleDo) Limit(limit int) IUserRoleDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userRoleDo) Offset(offset int) IUserRoleDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserRoleDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userRoleDo) Unscoped() IUserRoleDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userRoleDo) Create(values ...*models.UserRole) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userRoleDo) CreateInBatches(values []*models.UserRole, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userRoleDo) Save(values ...*models.UserRole) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userRoleDo) First() (*models.UserRole, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserRole), nil
	}
}

func (u userRoleDo) Take() (*models.UserRole, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserRole), nil
	}
}

func (u userRoleDo) Last() (*models.UserRole, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserRole), nil
	}
}

func (u userRoleDo) Find() ([]*models.UserRole, error) {
	result, err := u.DO.Find()
	return result.([]*models.UserRole), err
}

func (u userRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.UserRole, err error) {
	buf := make([]*models.UserRole, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userRoleDo) FindInBatches(result *[]*models.UserRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userRoleDo) Attrs(attrs ...field.AssignExpr) IUserRoleDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userRoleDo) Assign(attrs ...field.AssignExpr) IUserRoleDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userRoleDo) Joins(fields ...field.RelationField) IUserRoleDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userRoleDo) Preload(fields ...field.RelationField) IUserRoleDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userRoleDo) FirstOrInit() (*models.UserRole, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserRole), nil
	}
}

func (u userRoleDo) FirstOrCreate() (*models.UserRole, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserRole), nil
	}
}

func (u userRoleDo) FindByPage(offset int, limit int) (result []*models.UserRole, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userRoleDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userRoleDo) Delete(models ...*models.UserRole) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userRoleDo) withDO(do gen.Dao) *userRoleDo {
	u.DO = *do.(*gen.DO)
	return u
}
